### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`

### ISSUE THREAD

**Issue by ChauVV** [awslabs/aws-sdk-ios-samples#100]
-swift demo: when i touch upload or download button, there is a error:
at this line: 
`let s3 = AWSS3.defaultS3()`

>  app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `Info.plist` or set `defaultServiceConfiguration` before using this method.'

**Comment by wdane** [comment]
Which sample app are you trying to run? Looking at the S3TransferUtility example, there are instructions for updating the Info.plist. Did you do this?

**Comment by TomasRejhons** [comment]
I have the same issue when trying to run the S3TransferManagerSampleSwift on iOS10. Uploading works fine, but download immediately fails in listObjects() with the exception described above.

I believe I did the Info.plist setup correctly:
<img width="411" alt="screen shot 2016-10-02 at 15 53 50" src="https://cloud.githubusercontent.com/assets/3966763/19021051/040eec40-88b9-11e6-9ddc-df8c6cd41827.png">

**Comment by ImranIB** [comment]
I am also facing the same issue. Any one can resolve that?

**Comment by TijenderSingh** [comment]
Add below code in didFinishLaunchingWithOptions

   AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:AWS_POOLKEY];
    
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];
    
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;

**Comment by raymondyyy** [comment]
Add below code in AppDelegate.swift:
```
let credentialsProvider = AWSCognitoCredentialsProvider(regionType: "Your Region Type", identityPoolId: "Your Identity Pool ID")
let configuration = AWSServiceConfiguration(region: "Your Region Type", credentialsProvider: credentialsProvider)
AWSServiceManager.default().defaultServiceConfiguration = configuration
```

**Comment by cbommas** [comment]
Closing issue as it appears to have been address by @raymondyyy and @TijenderSingh
