### ISSUE TITLE
Issue while authenticating without clientSecret 

### ISSUE THREAD

**Issue by aniketgw47** [awslabs/aws-sdk-ios-samples#102]
We have not opted for app secret key in our user pool. 
When configuring  AWSCognitoIdentityUserPoolConfiguration we set clientSecret to **nil** and then tried login but, provided sample application did not work correctly. [CognitoYourUserPools-Sample]
When we set clientSecret  to [blank] It gives exception "_Not opted for client secret but it is provided_".

**Response headers**
{
    Connection = "keep-alive";
    "Content-Length" = 142;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "xxxxxxxx";
    "x-amzn-ErrorMessage" = "Client xxxxxxxxxxx is not configured for secret but secret hash was received";
    "x-amzn-ErrorType" = "InvalidParameterException:";
    "x-amzn-RequestId" = "xxxxxxxxx";
}

please help.

**Comment by jbailey2010** [comment]
Setting it to nil would be the way to go. The example given is for when it was passed as blank, what response were you seeing when you ran it as nil?

**Comment by aniketgw47** [comment]
Thanks for replay @jbailey2010 , We did try it with nil, but with that application is crashing ( in getSession function).

**Comment by jbailey2010** [comment]
Understood, but can you share any stacktrace or exception message that you saw?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If there's still an issue, please open it in the aws/aws-sdk-ios repo.
