### ISSUE TITLE
Use of AWSCognitoIdentityUserAttributeType

### ISSUE THREAD

**Issue by BruceBuckland** [awslabs/aws-sdk-ios-samples#103]
Under what circumstances do you intend the developer use **AWSCognitoIdentityUserAttributeType** vs **AWSCognitoIdentityProviderAttributeType**? 

**Background:**

It could be that I am misunderstanding, but it would appear that the **getDetails** method of **AWSCognitoIdentityUser** would return a response containing attributes of **AWSCognitoIdentityUserAttributeType** but instead the response contains **AWSCognitoIdentityProviderAttributeType**.

Similarly the **updateAttributes** method of **AWSCognitoIdentityUser** expects a **AWSCognitoIdentityUserAttributeType** but the response contains attributes of the type  **AWSCognitoIdentityProviderAttributeType**.

I realize that **AWSCognitoIdentityUserAttributeType** is declared as a **AWSCognitoIdentityProviderAttributeType**, but  In Swift (a type safe language) this leaves me to do type coercion to make the types compatible.  

Update:  This is not so bad when taking the **AWSCognitoIdentityProviderAttributeType** and using it.  But when I go to update attributes the API wants a **AWSCognitoIdentityUserAttributeType** and that requires me to upcast, which does not work.  So i have to re-create the array, just to create a storage equivalent array that has the right type.

A consistent use of the types, or better yet eliminating one of the types, would make the code read better.    Why does **AWSCognitoIdentityUserAttributeType** exist at all?

**Comment by behrooziAWS** [comment]
The intent here was to have AWSCognitoIdentityUserAttributeType be the developer facing type and for it to be used in all interactions with the AWSCognitoIdentityUser class.  It appears that it was only set up correctly as input and there is no translation being done for output limiting its usefulness.  I'll see if there is any way to make it consistent without introducing a breaking change.

**Comment by desokroshan** [comment]
This is being tracked as [SDK issue#1105](https://github.com/aws-amplify/aws-sdk-ios/issues/1105).
