### ISSUE TITLE
Get a list of active download tasks from AWSS3TransferUtility in IOS

### ISSUE THREAD

**Issue by briankeane** [awslabs/aws-sdk-ios-samples#105]
I need to retrieve a list of active downloads from the AWSS3TransferUtility.  As per the docs here:

http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html#//api/name/getAllTasks

it seems that getDownloadTasks() is supposed to return what I want (an array of tasks), but instead it's giving me a single task.  getAllTasks() and getUploadTasks() also return a single task.  Is this expected behavior?

Thanks for your time!

**Comment by kvasukib** [comment]
Hi @briankeane,

Thanks for reporting to us. 

1. Can you provide a snippet of code showing how you call getDownloadTasks()?
2. Which version of SDK are you using?

**Comment by briankeane** [comment]
9 months ago I would have been so happy to receive this response.  At this point, though, my codebase has moved on.

**Comment by kvasukib** [comment]
Hi @briankeane,

We are sorry for having missed responding to your query timely.
