### ISSUE TITLE
Getting CognitoID when using User Pool

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#106]
So following the CognitoYourUserPoolsSample I read the docs to combine this into the cognito identity to get the cognito identity out.

I find that in the samples refresh method I can do

```
        let pool = AWSCognitoIdentityUserPool(forKey: "UserPool")
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .usEast1, identityPoolId: Constants.identityPoolId, identityProviderManager:pool)
        credentialsProvider.getIdentityId().continue ({ (task) -> Any? in
            if let result = task.result {
                print("coginto id \(result)")
            }
            else {
                print(task.error?.localizedDescription)
            }

            return nil
        })

```

This will then trigger the AppDelegates 

`startPasswordAuthentication() -> AWSCognitoIdentityPasswordAuthentication`

And the callback comes back to the refresh method with the cognitoID once I logged in.

However, after doing this, the self.pool?.currentUser().isSignedIn is still set to false?

And if I instead try and do the way the sample code is doing it

```
        self.user?.getDetails().continue(successBlock: { (task) -> Any? in
            DispatchQueue.main.async {
                self.response = task.result
                self.usernameLabel.text = self.user?.username
            }
            return nil
        })
```

The credentialsProvider.getIdentityId() won't work.

Question is, how do I retrieve the cognitoID with the sample code?

**Comment by behrooziAWS** [comment]
If signedIn is false, where are you executing that line?  It is likely that you are executing that line before you are actually signed in.  If you put self.pool?.currentUser().isSignedIn after setting the self.usernameLabel.text = self.user?.username in the refresh method, it should be YES.

"And if I instead try and do the way the sample code is doing it."  To be clear, the sample code only makes service calls to Cognito Your User Pools. Everything you see in getDetails comes from Cognito Your User Pools.  Identity ids come from Cognito Federated Identity.  If you are trying to obtain an identity id using the sample, you need to do something like you mention, it will not make any calls to Cognito Federate Identity on it's own.

**Comment by helloniklas** [comment]
@behrooziAWS ok works now when I test on the device rather than the simulator. The problem I was seeing is that on the simulator the sign in doesn't work, although it think it does. So when I then called credentialsProvider.getIdentityId() it was calling the startPasswordAuthentication() again.

Is it normal that it won't work in the simulator? I'm running Xcode-beta with iOS10 and Swift 3, I guess that might be the problem.

In any case, works on the device now. Thanks.

**Comment by helloniklas** [comment]
@behrooziAWS So after successfully login and then getting the cognitoIdentity id back with getIdentityId() I then attempt to load a DyanmoDB object with the AWSDynamoDBObjectMapper but it then says

> {"__type":"com.amazon.coral.service#MissingAuthenticationTokenException","message":"Request is missing Authentication Token"}

I have set up roles to allow the Cognito Auth role to access the table.

What am I missing? Do I need to explicitly say what the auth role is?

**Comment by behrooziAWS** [comment]
I have not had issues running in the simulator with Xcode 7.3 and iOS 9.3.  I have not tried with the beta and iOS 10 yet.  There is no synchronization logic in the user pools SDK to only run one authentication ui at a time.  When I was testing the sample earlier, it doesn't gracefully handle displaying the authentication ui while it is already showing and will crash. If you are explicitly calling getIdentityId make sure it is done in a place where the app already has a valid user pools session, like in the success block of self.user?.getDetails().

You do not need to specify the auth role other than in your identity pool configuration in the AWS console.  How are you configuring the credentials provider for your AWSDynamoDBObjectMapper?  Are you setting the default AWSServiceConfiguration to the credentials provider that has your user pool object as the identityProviderManager?

```
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"IDENTITY_POOL_ID" identityProviderManager:pool];

AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:credentialsProvider];

AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

**Comment by helloniklas** [comment]
@behrooziAWS Thanks, got it working now, seems it wasn't setting the configuration properly after auth.
