### ISSUE TITLE
CognitoYourUserPoolsSample does not persist user?

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#107]
Do I manually have to store the password in the keychain then log the user in behind the scenes overtime the app runs? Or is there no built in way that caches this for me?

I find I have to log in again every time I run the code.

**Comment by behrooziAWS** [comment]
As long as you don't sign out, the sample will authenticate the last logged in user without prompting for a password.  You should only be prompted for a password if you sign out or your refresh token expires which by default is 30 days since you last supplied your username/password.

**Comment by helloniklas** [comment]
@behrooziAWS right, seems this only work if running on the device. I was testing in the simulator with Xcode-beta running iOS10 and Swift 3, in which case it doesn't work.
