### ISSUE TITLE
How do you get HTTP status code from API Gateway?

### ISSUE THREAD

**Issue by biogerm** [awslabs/aws-sdk-ios-samples#109]
Hi,

While most success responses from API gateway have 200 as HTTP status code, failed requests would have something else instead, e.g. 400, 404, 410, etc.

How can I get such a response HTTP status code from generated iOS SDK during a failure?
**continueWithBlock** returns **AWSTask** after execution. If Lambda reports failure, AWSTask will have **nil** task.result but a task.**error**. However in this **error**, which is **NSError**, it has code = 1 rather than HTTP status code.

The best I can do so far is to pass message from Lambda through Body Mapping then get it from NSError.userInfo["HTTPBody"].description. I can't find an intuitive way of doing it. Even though you can map the **Method Response** with **Model** defined in API Gateway, while failing, AWSTask doesn't have a **result** therefore you cannot use **Model**.

Any help is appreciated.

BR
An Chin

**Comment by karthiksaligrama** [comment]
At this point we do not support returning the response headers in API gateway. We are considering adding this feature.

**Comment by biogerm** [comment]
@karthiksaligrama so what's the suggested way to handle error cases? Is there anyway to map error into Model?

**Comment by biogerm** [comment]
@karthiksaligrama In my application, I would need to return different error from API Gateway and handle them differently in iOS application.

**Comment by mlshon** [comment]
You can use the generic invoker to achieve this. It's available in the latest SDK.

**Comment by pkassonss** [comment]
biogerm - just hitting the same/similar issue you are describing.  I want to not only return internal messages from a Lambda call, even if the HTTP call to the API Gateway is 200, Lambda may have puked.  But, I think I have a model mapper just fine for the integration response and method response, but I am not clear on how to invoke the method using the generated API and handle the error directly.
