### ISSUE TITLE
How to install without pods

### ISSUE THREAD

**Issue by freynolds** [awslabs/aws-sdk-ios-samples#11]
Hi, I have a Phonegap project and it does colide with how Pods are installed, is there any instructions on how could I work with this without using Pods to install the requriements?
Thank you

**Comment by yosuke-matsuda** [comment]
[AWS Mobile SDK for iOS Developer Guide](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/index.html) should help.

**Comment by freynolds** [comment]
It was hard but it worked! Thank you!
