### ISSUE TITLE
How to use User Pool with DynamoDB access control

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#110]
How can set the access control of a DynmoDB item to only be accessed by the logged in user in my user pool. Reading the docs on this they say only Web Identity Federation is supported?

> This condition key allows users to access only the items where the partition key value matches their user ID. This ID, ${www.amazon.com:user_id}, is a substitution 

Surely this must be supported by using auth with a User Pool? What substitution ID can I use?

**Comment by karthiksaligrama** [comment]
You can hook up Cognito User Pools to Cognito Identity and use something like for fine grained access control

```
"Condition": {
        "ForAllValues:StringEquals": {
          "dynamodb:LeadingKeys": ["${cognito-identity.amazonaws.com:sub}"]
        }
   }
```
