### ISSUE TITLE
Best way to check for confirmed email at login

### ISSUE THREAD

**Issue by hmehran** [awslabs/aws-sdk-ios-samples#113]
Hi I was wondering what the best way to check for confirmed email at login is.

I found these exceptions but do not know where or how to handle them:

UserNotConfirmedException - User tries to login but hasn't yet confirmed
PasswordResetRequiredException - A password reset command has been issued on this users account.
NotAuthorizedException - Password is incorrect (It will say Username or Password is incorrect in the message)
ResourceNotFoundException - User not found

Thanks
hm

**Comment by rachitdhall** [comment]
When a user successfully signs in, you can do a GetUser call which will return an attribute 'email_verified'. This attribute is set to true if the customer has verified the email.

Regarding how to handle the exceptions above

UserNotConfirmedException - If you are using email/phone verification, then you can direct the user to a screen where they can request the code again(ResendConfirmationCode) or enter if they have one (ConfirmSignUp API)
PasswordResetRequiredException - User is in a state where the password has to be changed, so you can direct them to a screen where they can request a code (ForgotPassword) and then have them enter the code  (ConfirmForgotPassword)
NotAuthorizedException - Have the user re-enter the password. [If the exception message says the user is temporarily locked out of authentication attempts, display this to the user]
ResourceNotFoundException - User not found, so direct them to sign up page.

**Comment by hmehran** [comment]
Hello again,
The part I did not understand is how or where to catch the exceptions in code. 

For example I get this from the debug: 
(But I do not know the appropriate methods to call to either catch this exception or view them by myself.
I saw that the javascript sdk had a way to do this but not sure with ios. 
Thanks

AWSiOSSDK v2.4.7 [Debug] AWSURLSessionManager.m line:553 | -[AWSURLSessionManager printHTTPHeadersForResponse:] | Response headers:
{
    Connection = "keep-alive";
    "Content-Length" = 73;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Mon, 26 Sep 2016 23:40:02 GMT";
    "x-amzn-ErrorMessage" = "User is not confirmed.";
    "x-amzn-ErrorType" = "UserNotConfirmedException:";
    "x-amzn-RequestId" = "8bccc718-8442-11e6-a744-19d28d1fd098";
}
2016-09-26 16:40:03.064 ALT CULT[5080:138547] AWSiOSSDK v2.4.7 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"__type":"UserNotConfirmedException","message":"User is not confirmed."}

**Comment by chetanme** [comment]
`you can only log in if user email is verified. `

This is not entirely true. Email/ Phone number verification is just a by product of user account confirmation through codes. Whatever medium user confirms his account through, service treats that medium as verified. By default, developers must use one of these mediums for user account confirmation.

If you do not want your users to go through this additional confirmation step, you can `autoConfirm` users on SignUp using the [PreSignUp trigger](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-pools-lambda-trigger-syntax-pre-signup). Once the user is confirmed, he will be allowed to sign in.

**Comment by hmehran** [comment]
Ok thanks. But for me I want them to validate before using the app. So to do that the only way to test for email validation would be through the use of UserNotConfirmedException correct? How and where do I catch this exception? Or even what methods can i call to check for this. 
Thanks
hm

**Comment by itrestian** [comment]
That exception is thrown when you try to authenticate the user.
