### ISSUE TITLE
DynamoDBSampleSwift build failed after conversion to Swift 3.0

### ISSUE THREAD

**Issue by pkrakow** [awslabs/aws-sdk-ios-samples#116]
I recently updated Xcode to version 8.0. I let Xcode convert my copy of DynamoDBSampleSwift to swift 3.0 (no other changes) and now the build fails with 12 errors (see attached screenshot.)

I am facing similar problems with other projects that use the AWS SDK for iOS. I'm submitting this ticket since the problem is with a bone-stock version of the tutorial app.

![screen shot 2016-09-18 at 7 09 49 pm](https://cloud.githubusercontent.com/assets/737031/18621129/e4c0146c-7dd3-11e6-9f29-fa6159e95f69.png)

**Comment by rohandubal** [comment]
The sample apps are built for Swift 2 and not Swift 3. If you intend to use Swift 2 version of the apps, you could set the "Use Legacy Swift" flag in "Swift Compiler Settings" to use the older version of Swift on Xcode 8. We will update the thread when we update the sample apps to Swift 3.

**Comment by pkrakow** [comment]
OK - please do update the thread when the examples have been updated to Support Swift 3.

**Comment by pkrakow** [comment]
I tried changing the Swift Compiler Setting to Use Legacy Swift on a clone of the DynamoDBSampleSwift app that compiled and ran prior to the Xcode 8.0 upgrade, and it did not work. The build fails with the following error message: Command /Applications/XCode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/bin/swiftc failed with exit code 1

The only change that I made to the clone was to set the Swift Compiler Setting to Use Legacy Swift. I did not accept any of Xcode's offers the convert the code.

**Comment by pkrakow** [comment]
I tried the same, using the latest version of the sample code, and that worked:
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/DynamoDBObjectMapper-Sample/Swift

The issue must be with the version of the sample code I had in my original project. I'll upgrade.

**Comment by minbi** [comment]
I assume this issue has been resolved, reopen if this is not the case. :)
