### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by arshu-dev** [awslabs/aws-sdk-ios-samples#121]
The current SDK & samples are not working with Swift 3.0. Please update asap as we are unable to compile the code even though the library is using legacy version 2.2. 

All the methods are forming like `transferManager.upload(uploadRequest).continue(<#T##block: (AWSTask<AnyObject>) -> Any?##(AWSTask<AnyObject>) -> Any?#>)`

As in Swift 3.0 all the methods are converted to `continue` & continue being a reserved word, we cannot compile the source code.

**Comment by Domsware** [comment]
I think the issue #130 have the same origin.

**Comment by arshu-dev** [comment]
I found a solution for this continue keyword issue. This works only for Swift 3.0 reserved word issue.

All you need to do is add round brackets outside the block inside the continue function. Earlier it was `continue { (task) }`, change it to `continue ( { (task) } )`.

Change the function to something like the below:
transferManager?.upload(uploadRequest).continue ({(task) -> AnyObject! in ....... })

**Comment by minbi** [comment]
Samples have been updated to Swift 3 using version 2.5.0 of the SDK. Note that Swift naming translations have been added and will break many Swift uses.

You may use XCode's autocomplete to see the new methods for AWSTask.
