### ISSUE TITLE
Recommended pattern for API Gateway failure handling

### ISSUE THREAD

**Issue by jhewitt** [awslabs/aws-sdk-ios-samples#123]
Hi,

We are using the API Gateway to access several lambda services that we have written.  The preferred method for checking the success or failure of these restfull calls is to check the HTTP status code.  It appears as though this status code is not exposed in the iOS SDK however.  What is your recommended solution for returning specific error information from a Gateway Lambda service?

Thanks

**Comment by karthiksaligrama** [comment]
you can map different http code status to an output model.
