### ISSUE TITLE
CognitoSync-Sample not updated for library version 2.4.x

### ISSUE THREAD

**Issue by kdbertel** [awslabs/aws-sdk-ios-samples#124]
The only sample project for using Amazon Cognito Identity that demonstrates how to use other login providers (such as Facebook) is CognitoSync-Sample.

However, the Podfile for CognitoSync-Sample indicates that `AWSCognito` should be at `2.2.x`:

```
pod 'AWSCognito', '~> 2.2.0'
```

The `AWSCognito` pod is now at `2.4.x`, and in the process between the two minor versions, the `logins` dictionary has been deprecated on an `AWSCognitoCredentialsProvider`. However, the current CognitoSync-Sample code relies on using and modifying that `logins` dictionary.

There is a branch for showing one small part of the sample in `2.4.x`, but it does not fully translate.

The CognitoSync-Sample code needs to be updated to the `2.4.x` branch of `AWCognito` to demonstrate how we developers are expected to now work with the updated objects and protocols. Version `2.4.0` of the SDK was released on April 19th of this year; it has been nearly six months.

The documentation [here](http://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html) also appears out of date to how the SDK was updated nearly six months ago.

**Comment by karthiksaligrama** [comment]
Please refer the branch developer-authenticated-identities-2-4 for updated sample.

**Comment by kdbertel** [comment]
As I said, that branch does not fully translate. The `developer-authenticated-identities-2-4` branch only demonstrates how to do developer authenticated identities. It does not include any code for using other login providers (such as Facebook).

**Comment by behrooziAWS** [comment]
There is a pull request here: https://github.com/awslabs/aws-sdk-ios-samples/pull/114 That we are reviewing for inclusion.

**Comment by kdbertel** [comment]
It has been 3 months since that pull request was made and 2 months since the comment about it being reviewed. What is the status of this?

**Comment by kdbertel** [comment]
It's been 27 days since my comment requesting status. What is the status of this?

**Comment by muellerfr** [comment]
Hello @kdbertel ,

Please use [AWS AppSync](https://aws.amazon.com/appsync/resources/) instead of Amazon Cognito Sync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.

It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

Please let us know if you have any questions about AppSync.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
