### ISSUE TITLE
User signedIn false after successful login request and session token?

### ISSUE THREAD

**Issue by jalleyne** [awslabs/aws-sdk-ios-samples#125]
I followed the objective c sample code for cognito ios user pools and can successfully register, confirm a user and get a session, but `[pool currentUser].signedIn)` is always `false` even after i get a token back from `[[pool currentUser] getSession:email password:password ...]`.

Any suggestions on what my be going wrong?

_Update_: Works on my device but not in the simulator... shouldnt this be able to work in the simulator also?

**Comment by behrooziAWS** [comment]
Enable the keychain sharing entitlement and it should work in the simulator.  https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html

**Comment by jalleyne** [comment]
@behrooziAWS thank you that worked perfectly..
