### ISSUE TITLE
Unable to verify a UserPool user if app shuts down in between

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#127]
So, I'm able to verify a user with the code after signing up if it's done in the same run of the app. But, if a user sign ups, then the app shuts down and restarts (for instance battery drains or for whatever reason the user doesn't verify user right away) I then retrieve that user by user name and do the verify in the same way

`user.confirmSignUp(code, forceAliasCreation: true).continue({ (task) -> Any? in`

But I then just get back the error AWSCognitoIdentityProviderErrorDomain.codeMismatch despite the code being the correct one?

**Comment by behrooziAWS** [comment]
Closing as Dup of https://github.com/aws/aws-sdk-ios/issues/497
