### ISSUE TITLE
How to install without pods?

### ISSUE THREAD

**Issue by Domsware** [awslabs/aws-sdk-ios-samples#129]
I cannot use CocoaPods in my projects. So could you please describe how to make samples run without this tool?

There is an old issue about this point but it have no details...

**Comment by karthiksaligrama** [comment]
you can use carthage, or you can directly download the framework from https://aws.amazon.com/mobile/sdk

**Comment by Domsware** [comment]
There is a misunderstanding as I want to run sample project without using Cocoapods. Of course I can use Carthage and that is exactly what I have done. But there are errors!

**Comment by Domsware** [comment]
None of you solution work.
Today I tried to use SDK from MobileHub. It does not work due to others compilation errors.
