### ISSUE TITLE
debug info

### ISSUE THREAD

**Issue by gadphly** [awslabs/aws-sdk-ios-samples#13]
Hello,

CognitoSyncDemo has debug logs that show the way the AWS messages are constructed and sent  and the responses. It was really helpful to understand what is going on.

How can I turn on the debug logs for the other projects (such as DynamoDBSample)?

Also are there examples of DynamoDBSamples that actually use authenticated logins? I want to build an app where an authenticated user can add DynamoDB entries which are private only to him.

Thanks for your help.

**Comment by yosuke-matsuda** [comment]
You can turn on the verbose logging by following [AWS Mobile SDK for iOS Developer Guide](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html#logging). Currently, we do not have a sample app using the fine-grain access control feature in Amazon DynamoDB, but you can take a look at [Amazon DynamoDB Developer Guide](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/FGAC_DDB.html) to get started.

**Comment by gadphly** [comment]
Thank you!
