### ISSUE TITLE
Tips for running IoT-Sample on iOS 10.1.1 

### ISSUE THREAD

**Issue by maxzou2015** [awslabs/aws-sdk-ios-samples#132]
This is not really an issue but hope it's helpful for new comers as I struggled a while to figure out how do run it and to be honest the readme is not clear enough if you haven't got a lot of experiences.

My environment: Xcode 8.1, iOS 10.1.1, iPhone 6+/5S

* step 1/2 are fine
* step 3: 
In the Amazon Cognito console, use Amazon Cognito to create a new **identity pool**. **In the Cognito console, it's not called 'identity pool' but called 'Federated identities'. If you click 'manage your user pools' that's wrong! and in that case you won't have unauthenticated roles automatically created for you in the IAM console** Obtain the PoolID constant. Make sure that the policy attached to the unauthenticated role has permissions to access the required AWS IoT APIs. More information about AWS IAM roles and policies can be found here. **after creating the identity pool you can go to the IAM console and you should see an '...Unauth_role' over there and then you can attach the 'AWSIoTFullAccess' to it**
* step 4 is fine
* step 5: 
** let AwsRegion = AWSRegionType.Unknown **Must be changed to an actual region!**
** let CognitoIdentityPoolId = "YourCognitoIdentityPoolId" **the pool id you just created**
** let CertificateSigningRequestCommonName = "IoTSampleSwift Application" **not really need to change**
** let CertificateSigningRequestCountryName = "Your Country" **not really need to change**
** let CertificateSigningRequestOrganizationName = "Your Organization" **not really need to change**
** let CertificateSigningRequestOrganizationalUnitName = "Your Organizational Unit" **not really need to change**
** let PolicyName = "YourPolicyName" **!!Big pitfall here: this policy is not the policy you can see in the IAM console but the policy you need to create in the IoT console!! otherwise if you use a policy from those you can see in IAM console it will report 'policy not found'** (actually I don' know why IoT manages its own set of policies)
* step 6/7/8 all fine

Xcode and iOS side:
* Opening the project in Xcode 8.1 - the project is based on swift 2.2 so when you open it the first time Xcode will ask you to upgrade and you have to otherwise you won't be able to compile. However for IoT-Sample upgrading to swift 2.3 is quite smooth and it shouldn't bring too much trouble.
** for the IoTTemperatureControlSample it's not as easy since it uses SwiftyJSON without specifying a version so if you use pod to update to the latest version SwiftyJSON will require swift 3.0 however other parts of the project is not that easy to be upgraded to swift 3.0 yet... the easiest workaround is before 'pod update' change the Podfile first and change the line for SwiftyJSON to **pod 'SwiftyJSON', '~> 2.4.0'**
* Regarding iOS 10 simulator, if you don't use your own certificate (i.e. skipping step 8) you can't run it correctly on simulators (didn't try if it works if you do step 8), that's because the sample app tries to use keychain to store the certificate and keys but because of the change of iOS 10 simulator you can't access keychain simply as before. there is workaround if you really want to use the simulator (https://forums.developer.apple.com/thread/60617) but I haven't tried it personally

Now if you have two phones you can see one of them can subscribe to the topic published by the other phone

**Comment by mlshon** [comment]
Thank you for letting us know.  We will look into making improvements to our instructions.

**Comment by Moeez007** [comment]
Thanks @maxzou2015  
Your info helped me to run the iot samples both the simple one and also the temperature one.

**Comment by zwang-solpad** [comment]
Thanks, this really helps.

**Comment by hpc33** [comment]
sorry, but I remake this sample app many times but still got

2018-06-10 05:09:28.528685+0800 IoTSampleSwift[25607:3173578] CFNetwork SSLHandshake failed (-9829)

2018-06-10 05:09:28.528863+0800 IoTSampleSwift[25607:3173578] TCP Conn 0x600000360d80 SSLHandshake failed (-9829)

I have no idea how to fix it, I was searched many topics but still can't fix this problem, would anyone help me? 

thanks

**Comment by cbommas** [comment]
@hpc33 

Sorry to hear that you are running into issues. 9829 error  is errSSLPeerCertUnknown, unknown certificate. A few questions to help debug this issue.

1) Are you using a pre-existing certificate or are you creating one on the fly in the sample?
2) Do you see the certificate listed and in an active state on the AWS Console? (To see the list of certs, navigate to the AWS Console, choose IOT Core and click on secure on the left nav in IOT Core). 
3) If you see the certificate, then click on it. In the page that shows up, click on Policies in the left hand side and make sure that it contains a policy named "pubsub".

Please let me know

**Comment by hpc33** [comment]
@cbommas thanks for your reply, I've solved this problem, just erase all content and settings, and it runs well :)

**Comment by cbommas** [comment]
Good to hear! Thank you for confirming. Please feel free to post back on this thread if you run into further issues.
