### ISSUE TITLE
IoT Sample / Swift - Unable to read p12

### ISSUE THREAD

**Issue by AaronBaker** [awslabs/aws-sdk-ios-samples#133]
Hello AWS,

I'm encountering an error when I try to load my own p12 file into the IoT Example:

    IoTSampleSwift[50368:4512258] AWSiOSSDK v2.4.9 [Error] AWSIoTManager.m line:233 | +[AWSIoTManager importIdentityFromPKCS12Data:passPhrase:certificateId:] | Unable to add private key

Any help would be appreciated,
Aaron

**Comment by gkwicker** [comment]
Hi @AaronBaker,

We're sorry you're having issues running the sample; that error message means that it's not able to find the private key in the .p12 file you've given it.  Make sure that you are creating the .p12 file from a valid AWS IoT client certificate and private key using the following command (this example uses a client certificate named 'certificate.pem.crt' and a private key named 'private.pem.key', and places the result in 'awsiot-identity.p12'):

```sh
openssl pkcs12 -export -in certificate.pem.crt -inkey private.pem.key -out awsiot-identity.p12
```

openssl will prompt you for an 'Export Password' when you do this; you don't have to add one (you can just hit <kbd>Enter</kbd> to bypass this), but if you do add a password you'll want to remember it.  To dump the contents of the .p12 file you just created, you can do an:

```sh
openssl pkcs12 -in awsiot-identity.p12
```

You should see sections which begin with ```-----BEGIN CERTIFICATE-----``` and ```-----BEGIN RSA PRIVATE KEY-----```

__NOTE:__ If you're prompted to ```Enter PEM pass phrase:```, you'll need to enter a pass phrase even if your private key doesn't have one (AWS IoT private keys don't).  Just enter any 4 characters (e.g. 1234) twice and it will display the private key section if your .p12 file has one.

Can you check to make sure your .p12 file contains both the ```-----BEGIN CERTIFICATE-----``` and ```-----BEGIN RSA PRIVATE KEY-----``` sections?  If not, can you try creating another .p12 file using the above command?  Let us know if that helps, and thanks for using AWS IoT.

**Comment by AaronBaker** [comment]
Hello Gary,

Thank you for your quick reply. I was able to view the contents of the .p12 file and it definitely has both a `-----BEGIN CERTIFICATE-----` and `-----BEGIN RSA PRIVATE KEY-----` sections.

Do you know of anything else that could be causing this issue?

Thanks again,
Aaron

**Comment by gkwicker** [comment]
Hi @AaronBaker, was your .p12 file created from an AWS IoT certificate and private key?  If so, you should see something like this right before the ```-----BEGIN CERTIFICATE-----```:

```sh
subject=/CN=AWS IoT Certificate
issuer=/OU=Amazon Web Services O=Amazon.com Inc. L=Seattle ST=Washington C=US
```
Have you tried creating a new certificate/private key on the [AWS IoT console](https://console.aws.amazon.com/iot) and then using the openssl commands from the previous post to create the .p12 file?  If that doesn't work for you, can you post your Xcode version and the version of the AWS SDK that you're using?

**Comment by AaronBaker** [comment]
Hello @gkwicker,

I created a new certificate in the AWS IoT console and created a new .p12 file. I'm still having the same issue. Here's more information about my configuration:

- Xcode Version 8.0
-  AWSCore (2.4.9)
- AWSIoT (2.4.9)

In addition, when I opened the project, XCode asked made me update the source code to a new version of swift. I had the option of updating the source code to Swift 2.3 or Swift 3. I chose Swift 2.3.

Thank you for your help,
Aaron

**Comment by gkwicker** [comment]
Hi @AaronBaker, the root cause of this issue is a change in Xcode 8 which requires that Keychain Sharing be enabled in the application in order for it to run in the simulator.  A couple of good posts on this can be found [here](https://forums.developer.apple.com/thread/60617) and [here](http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator).  Let us know if that takes care of the problem, and thanks for using AWS IoT.

**Comment by minbi** [comment]
IoT sample has been update for Swift 3 and runs on XCode 8.2

**Comment by paultwin0202** [comment]
I can't test it for Swift 3 and runs on XCode 8.2
