### ISSUE TITLE
Cognito Integration error in Objective-C project

### ISSUE THREAD

**Issue by billy84** [awslabs/aws-sdk-ios-samples#137]
Hi,

I have tried to launch the Cognito sample project.
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Objective-C
By the way, I have got this error.

No type or protocol named 'AWSCognitoIdentityNewPasswordRequired'
Cannot find protocol declaration for 'AWSCognitoIdentityRememberDevice'

How can I fix this error?
I have installed pod and I am using xCode 8.0

**Comment by behrooziAWS** [comment]
@billy84 seems like you have an older version of the AWSCognitoIdentityProvider pod, try doing a `pod update`
