### ISSUE TITLE
IoT Sample / Swift - Stuck Connecting...

### ISSUE THREAD

**Issue by alexlavr** [awslabs/aws-sdk-ios-samples#141]
I am using Xcode 8.0, when I tap Connect, the screen gets stuck on "Connecting...".

How can this be debugged/fixed?

Thanks!
> 2016-11-30 17:38:32.075 IoTSampleSwift[5124:258213] AWSiOSSDK v2.4.12 [Info] AWSIoTDataManager.m line:244 | -[AWSIoTDataManager connectWithClientId:cleanSession:certificateId:statusCallback:] | hostName: data.iot.us-east-1.amazonaws.com
2016-11-30 17:38:32.076 IoTSampleSwift[5124:258213] AWSiOSSDK v2.4.12 [Info] AWSIoTDataManager.m line:245 | -[AWSIoTDataManager connectWithClientId:cleanSession:certificateId:statusCallback:] | URL: https://data.iot.us-east-1.amazonaws.com
2016-11-30 17:38:32.079 IoTSampleSwift[5124:258213] AWSiOSSDK v2.4.12 [Info] MQTTMessage.m line:104 | +[MQTTMessage connectMessageWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetain:] | <00044d51 54540402 003c0024 33394131 36354630 2d444338 342d3446 33302d41 3232382d 39414138 42323835 35433843>
connection status = 1
Connecting...

 ---
Update:
Websocket works ok
> iotDataManager.connectUsingWebSocketWithClientId(uuid, cleanSession: true, statusCallback: mqttEventCallback);

**Comment by muthuyml** [comment]
I'm facing this same issue. Could you please guide me on the same using certificate id approach...

**Comment by MuthurajMuthulingam** [comment]
I'm facing this same issue. Could you please guide me on the same using certificate id approach...

**Comment by chaurah** [comment]
Hi @alexlavr/@MuthurajMuthulingam,
   At first glance, the problem could be related to a change in XCode 8.0 which requires that Keychain Sharing be enabled in the application in order for it to run in the simulator. Please check the reasoning and some further information in [this](https://github.com/awslabs/aws-sdk-ios-samples/issues/133) issue.

Please let us know if that solves your issue. Thank you for using AWS IoT and the AWS iOS SDK.

Rahul

**Comment by homieseven** [comment]
Hi all! 
I've had the same issue despite the fact that allowed Keychain sharing. 
I was using AWS created certificates and real device.
The problem in my case was that I've been using wrong client ID in Policy settings in AWS console.
You can easily skip this check by using following connect statement in the Policy settings: 

{
     "Effect": "Allow",
      "Action": ["iot:Connect"],
      "Resource": ["*"]
},
As far as I understand "*" value allows to connect any device with installed certificates.

**Comment by rjpcal** [comment]
My team ran into the same symptoms when trying to migrate the sample MQTT connection code into a real app (a React Native app). From debugging and packet captures we saw that, although the 3-way TCP handshake was successful, no data was being sent subsequently (including no TLS handshake). This seems to be because the default runLoop within our app did not work for processing I/O events.

We found that we could get a successful MQTT connection by overriding the runLoop in the AWSIoTDataManager's mqttConfiguration, like this:

```
iotDataManager = AWSIoTDataManager.default()
iotDataManager.mqttConfiguration.runLoop = RunLoop.main
```

This was with Xcode 8.3, and same behavior using either AWSIoT SDK version 2.4.19 or 2.5.3.

**Comment by pccole** [comment]
I have run into the same issue after updating to 2.5.10.
My configuration is below:
`		credentialsProvider = AWSCognitoCredentialsProvider(regionType: Cognito.awsRegion, identityPoolId: Cognito.federatedIdentityPoolId)
		
		let iotEndPoint = AWSEndpoint(urlString: Cognito.iotENDPOINT)
		let iotConfiguration = AWSServiceConfiguration(region: Cognito.awsRegion, credentialsProvider: credentialsProvider)
		let iotDataConfiguration = AWSServiceConfiguration(region: Cognito.awsRegion, endpoint: iotEndPoint, credentialsProvider: credentialsProvider)
		let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: Cognito.clientId, clientSecret: Cognito.clientSecret, poolId: Cognito.poolId)
		
		AWSServiceManager.default().defaultServiceConfiguration = iotConfiguration
		AWSCognitoIdentityUserPool.register(with: iotConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: Cognito.userPoolKey)
		pool = AWSCognitoIdentityUserPool(forKey: Cognito.userPoolKey)
		
		
		iotManager = AWSIoTManager.default()
		iot = AWSIoT.default()
		
		AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: Cognito.dataManagerKey)
		iotDataManager = AWSIoTDataManager(forKey: Cognito.dataManagerKey)
		
		AWSIoTData.register(with: iotDataConfiguration!, forKey: Cognito.iotDataKey)
		iotData = AWSIoTData(forKey: Cognito.iotDataKey)
`
Any help in resolving this issue would be much appreciated!

**Comment by jhchong92** [comment]
@alexlavr is right.. 

change the line 
`iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:certificateId!, statusCallback: mqttEventCallback)`
with 
`iotDataManager.connectUsingWebSocket( withClientId: uuid, cleanSession:true, statusCallback: mqttEventCallback)`
solved the problem..

**Comment by kvasukib** [comment]
Closing the issue. Please open a new one if the issue still persists.

To sum up,
1. You should attach the policy to the certificate after creation.
2. Use WebSockets or plain MQTT as per the requirement.
3. Override runLoop as needed.

**Comment by King-Kira** [comment]
@rjpcal When I type `iotDataManager.mqttConfiguration.runLoop = RunLoop.main`, XCode says
> Cannot assign to property: 'runLoop' is a get-only property
