### ISSUE TITLE
Restarts the upload on network reachability

### ISSUE THREAD

**Issue by hanush-vijay** [awslabs/aws-sdk-ios-samples#142]
Hi,
AWS Transferutility Restarts the uploads on network reachability,
kindly reply to this issue asap.

**Comment by minbi** [comment]
Hi hanush-vijay,

What are the steps to reproduce? What is the expected behavior here?

**Comment by hanush-vijay** [comment]
HI minbi ,
Thank you for your response
steps to reproduce
1.upload a video.
2.While upload progress is in middle try to disconnect ur network
3 Again reconnect your network
Its Restarting the upload progress

**Expected behaviour**  
it should resume the upload progress

**Comment by desokroshan** [comment]
@hanush-vijay This expected behavior is implemented in multi-part uploads using TransferUtility. Please upgrade to the latest version of the sdk and retry uploads with network disconnect.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
