### ISSUE TITLE
Background Uploads hangs up for larger files

### ISSUE THREAD

**Issue by hanush-vijay** [awslabs/aws-sdk-ios-samples#143]
USING AWS Transferutility When i try to Upload more then 100mb of file and put the app in background 
it hangs up the Upload progress. 
kindly respond ASAP

**Comment by rohandubal** [comment]
Hi, can you provide some more details?

-What version of SDK you are using?
-Does it happen only on simulators / devices?
-Can you provide with a snippet to reproduce the issue?

Thanks,
Rohan

**Comment by hanush-vijay** [comment]
Hi rohandubal
Thank you for ur response

here is the code snippet
<code>

    func uploadVideoToS3Bucket1(){



        self.tabBarItemsEnableAndDisable(false)

        let _:NSData!

        self.uploadVideoCollectionView.userInteractionEnabled = false



        let keyName = defaults.objectForKey("UPLOADTOKENKEY") as! String



        let S3BucketName: String = "11buploaded"

        S3UploadKeyName = String(keyName) + ".MOV"

        print("S3UploadKeyName:\(S3UploadKeyName)")



        let expression = AWSS3TransferUtilityUploadExpression()



        expression.uploadProgress = {(task:AWSS3TransferUtilityTask,
bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64) in



            dispatch_async(dispatch_get_main_queue(), {



                self.tabBarItemsEnableAndDisable(false)

                self.uploadVideoCollectionView.userInteractionEnabled =
false

                let progress = Float(totalBytesSent) / Float
(totalBytesExpectedToSend)

                self.progressView.progress = progress

                // self.statusLabel.text = "Uploading..."

                self.uploadTask = task

                NSLog("Progress is: %f",progress)



                self.uplodCancelButton.hidden =  false



            })



        }



        self.uploadCompletionHandler = { (task, error) -> Void in

            dispatch_async(dispatch_get_main_queue(), {

                if ((error) != nil){



                    self.stopAnimating()

                    self.tabBarItemsEnableAndDisable(true)



                    if(self.uploadingProcess == false){

                        self.defaults.setObject(nil, forKey:"UPLOADTOKENKEY"
)

                        UIUtilities.showAlertWithMessage("Upload Canceled")

                        self.progressBgView.hidden =  true

                    }else{

                         //UIUtilities.showAlertWithMessage("Upload
restart!")

                    }

                    self.uploadVideoCollectionView.userInteractionEnabled =
true



                   // NSLog("Failed with error")

                  //  NSLog("Error: %@",error!)

                }



                else if(self.progressView.progress != 1.0) {

                    //    self.statusLabel.text = "Failed"

                    NSLog("Error: Failed - Likely due to invalid region /
filename(Video)")



                }



                else{





                    print("Sucess")



                    //self.uploadVideoCollectionView.userInteractionEnabled
= true

                    self.progressBgViewYConstrain.constant =  -50.0

                    self.progressBgView.hidden =  true

                    self.collectionViewYConstraint.constant =  0.0



                     self.submitVideoAPI()







                }

            })

        }



        print("uploadFileURL:\(imagePathURL)")



        let transferUtility = AWSS3TransferUtility.defaultS3TransferUtility
()



        if uploadFileURL != nil && S3UploadKeyName != nil{

            transferUtility!.uploadFile((uploadFileURL)!, bucket:
S3BucketName, key: S3UploadKeyName, contentType:"video/mp4", expression:
expression, completionHander: uploadCompletionHandler).continueWithBlock {
(task) -> AnyObject! in

                if let error = task.error {







                   // NSLog("Error: %@",error.localizedDescription)



                    self.tabBarItemsEnableAndDisable(true)

                    UIUtilities.showAlertWithMessage("Upload Canceled")

                   // self.uploadVideoCollectionView.userInteractionEnabled
= true

                    self.stopAnimating()

                    //  self.statusLabel.text = "Failed"

                }

                if let exception = task.exception {





                    NSLog("Exception: %@",exception.description);

                    self.tabBarItemsEnableAndDisable(true)

                    UIUtilities.showAlertWithMessage("Upload Canceled")

                    self.uploadVideoCollectionView.userInteractionEnabled =
true

                    self.stopAnimating()

                    //   self.statusLabel.text = "Failed"

                }

                if let _ = task.result {

                    // self.statusLabel.text = "Generating Upload File"

                    NSLog("Upload Starting!")

                    // Do something with uploadTask.

                }



                return nil;

            }

        }



        //end if photo library upload

        self.dismissViewControllerAnimated(true, completion: nil);



    }

<code ends>

*HANUSH VIJAY V*
Boston Technology Corporation

**Comment by rohandubal** [comment]
Hi @hanush-vijay 

Have you done the background download setup step as specified here:
http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html#configuring-the-application-delegate

Thanks,
Rohan

**Comment by hanush-vijay** [comment]
Hi Rohan,
yeah i followed all the instruction given by AWS
and Upload is working fine in the background.
but the issue is with larger files(>100MB)

Regards
Hanush



*HANUSH VIJAY V*
Boston Technology Corporation

**Comment by Laeyoung** [comment]
@hanush-vijay I got the same issue. I tried this solution using above article, but I didn't get success...

http://www.mobdesignapps.fr/blog/2016/10/26/uploading-large-file-to-aws-s3-in-the-background?utm_source=stackoverflow&utm_medium=response&utm_campaign=awareness

**Comment by Laeyoung** [comment]
@rohandubal I reported wrong info. 

Is there any plan to support multipartUpload on AWSS3TransferUtility like Android SDK?
