### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by hmehran** [awslabs/aws-sdk-ios-samples#144]
Hi guys there seems to be a bug or major slow down when i try to verify the email address of the user.  Its the part where you provide the username and the verification code [that was sent to the email of the user]. 

```
[[self.user confirmSignUp:verificationCode] continueWithSuccessBlock:^id _Nullable(AWSTask<AWSCognitoIdentityProviderConfirmSignUpResponse *> * _Nonnull task)
    {
        return nil;
    }];
```

It is either very slow to process or I have to continuously click the button multiple times for it to work properly. 
Also it completely doesn't work on older ipad minis 2.

Thanks
hm

**Comment by hmehran** [comment]
This is still an issue. 
Here is an error code I am getting:

-[AWSURLSessionManager printHTTPHeadersForResponse:] | Response headers:
{
    Connection = "keep-alive";
    "Content-Length" = 97;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Mon, 09 Jan 2017 22:20:07 GMT";
    "x-amzn-ErrorMessage" = "Invalid code provided, please request a code again.";
    "x-amzn-ErrorType" = "ExpiredCodeException:";
    "x-amzn-RequestId" = "c77c13f8-d6b9-11e6-9199-a58dc66d5687";
}
2017-01-09 14:20:08.630507 ALT CULT[3781:697729] AWSiOSSDK v2.4.12 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"__type":"ExpiredCodeException","message":"Invalid code provided, please request a code again."}

**Comment by hmehran** [comment]
Even when I removed "Do you want to require verification of emails or phone numbers?" both checkboxes, I still can't sign in. This is a big issue guys.

**Comment by hmehran** [comment]
Here is the error code I get when I try to sign in (without email or phone verification being required):


AWSiOSSDK v2.4.16 [Debug] AWSURLSessionManager.m line:566 | -[AWSURLSessionManager printHTTPHeadersForResponse:] | Response headers:
{
    Connection = "keep-alive";
    "Content-Length" = 73;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "Wed, 11 Jan 2017 20:14:00 GMT";
    "x-amzn-ErrorMessage" = "User is not confirmed.";
    "x-amzn-ErrorType" = "UserNotConfirmedException:";
    "x-amzn-RequestId" = "7d221ff8-d83a-11e6-a9c1-53c48a702fad";
}
2017-01-11 12:14:00.149480 ALT CULT[4598:839130] AWSiOSSDK v2.4.16 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"__type":"UserNotConfirmedException","message":"User is not confirmed."}

**Comment by behrooziAWS** [comment]
If you create a user with confirmation required and then uncheck the confirmation checkbox at the user pool level you still need to confirm the user.  You can do so in the console for that user.

As for your initial issue, the confirmation code is valid for 24 hours.  It looks like 21 days may have elapsed since you got the confirmation code.  If you want to confirm the user on the device, you need to request a new confirmation code:

[[user resendConfirmationCode] continueWithSuccessBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserResendConfirmationCodeResponse *> * _Nonnull task) {
    //success
    return nil;
}];
