### ISSUE TITLE
Lex Unauthorized Error in Example project

### ISSUE THREAD

**Issue by btelintelo** [awslabs/aws-sdk-ios-samples#145]
What permissions does the congnito identity need to connect to lex?  I get the following error in the swift 3 example app for lex.

2016-12-20 09:19:45.047 LexSwift[11643:2327159] AWSiOSSDK v2.4.14 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"Message":"User: arn:aws:sts::713785744503:assumed-role/lex/CognitoIdentityCredentials is not authorized to perform: lex:PostContent"}
error Error Domain=com.amazonaws.AWSLexErrorDomain Code=0 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/}

With the following inline policy attached to the role:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "lex:*"
            ],
            "Resource": "arn:aws:lex:*::/*"
        }
    ]
}

Now mind you there are no example policies for lex, so I had to make that up.

**Comment by karthiksaligrama** [comment]
Good point i'll add the lex policies in the sample. In the meantime can you try with the following

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "lex:PostContent"
      ],
      "Resource": "arn:aws:lex:::/*"
    }
  ]
}
```

**Comment by btelintelo** [comment]
The chat bot is working for me now, but I get this error with voice:

Response body:
{"Message":"Access denied while invoking Polly synthesize speech API. Please check the permissions on the IAM policy used to create the bot"}

**Comment by Bhat123** [comment]
I do receive this error still.. Any solutions ? I have set the same policy details .

**Comment by Bhat123** [comment]
Everything is working fine now !! In Trust Relationships section we just need to modify a small section i.e, "Service": "lex.amazonaws.com", I followed this link:https://github.com/awslabs/amz-ai-building-better-bots

Happy coding 👍

**Comment by steve-taylor** [comment]
For those of us (like me) who are totally new to all this AWS stuff, can you please explain what an inline policy is and, most importantly, where it goes? That would be very much appreciated.

**Comment by vlkadusumilli** [comment]
I am using the default "AWSServiceRoleForLexBots" which has only "polly:SynthesizeSpeech", and don't have the ability to edit policy to add "lex:PostContent". Is there a way to add in line policy for "AWSServiceRoleForLexBots" or create a new policy and attach to the bot.

**Comment by girishnair12345** [comment]
I am having this same error too
