### ISSUE TITLE
Lex Swift 3 Example - Voice Chat Permissions Error

### ISSUE THREAD

**Issue by btelintelo** [awslabs/aws-sdk-ios-samples#147]
While the text chat works fine for me, the voice chat doesn't work:
 Response body:
{"Message":"Access denied while invoking Polly synthesize speech API. Please check the permissions on the IAM policy used to create the bot"}
error Error Domain=com.amazonaws.AWSLexErrorDomain Code=4 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=DependencyFailedException:http://internal.amazon.com/coral/com.amazonaws.deepsense.runtimeservice/}

I can't find anything in the lex docs to determine what permissions need to be granted to get access to the Polly synthesize speed api.

**Comment by karthiksaligrama** [comment]
when you create a bot you need to set the IAM permissions which allows the Lex Bot to make calls to polly on behalf of user. Its documented [here](https://docs.aws.amazon.com/lex/latest/dg/gs-bp-prep.html) but it seems to be missing polly permissions, will get that one fixed.

In the meantime you can update the permission to use 

```
{ 
  "Version": "2012-10-17", 
  "Statement": [ 
    { 
      "Action": [ 
        "lambda:InvokeFunction",
        "polly:SynthesizeSpeech"
      ], 
      "Effect": "Allow", 
      "Resource": "*" 
    } 
  ] 
}
```

**Comment by btelintelo** [comment]
Same error after adding that to policy...

**Comment by ysak-y** [comment]
Try to add all polly permissions to policy. It'll work.

```
{ 
  "Version": "2012-10-17", 
  "Statement": [ 
    { 
      "Action": [ 
        "lambda:InvokeFunction",
        "polly:*"
      ], 
      "Effect": "Allow", 
      "Resource": "*" 
    } 
  ] 
}
```

**Comment by btelintelo** [comment]
I've tried that and still get:
2017-01-17 10:24:58.798 LexSwift[31974:3249608] AWSiOSSDK v2.4.16 [Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"Message":"Access denied while invoking Polly synthesize speech API. Please check the permissions on the IAM policy used to create the bot"}



I really want to try out Lex on iOS/Android, but am spending a large amount of time guessing on permissions.....here is my policy file.  As I said before, the text chat bot works fine.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "lambda:InvokeFunction",
                "mobileanalytics:PutEvents",
                "cognito-sync:*",
                "lex:PostContent",
                "sts:AssumeRole",
                "polly:*"
            ],
            "Resource": [
                "*",
                "arn:aws:lex:::/*"
            ]
        }
    ]
}

**Comment by karthiksaligrama** [comment]
did you add the policy to the bot or to the cognito identity pool?
YOu need to add polly permissions to the bot when you create it.

**Comment by btelintelo** [comment]
ok that appears to have done the trick.  Adding the permission to the role after the face don't seem to work.  Also, I added/deleted roles and they dont appear from the IAM dropdown in Lex to change them.  Finally, I don't see a way to delete a Lex bot and my list is getting a bit long.

**Comment by snbaker** [comment]
I found rebuilding and republishing allowed me to change the role after the fact.

**Comment by Bhat123** [comment]
I too received the below error: 
{"Message":"Access denied while invoking Polly synthesize speech API. Please check the permissions on the IAM policy used to create the bot"}
error Error Domain=com.amazonaws.AWSLexErrorDomain Code=4 "null" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=DependencyFailedException:http://internal.amazon.com/coral/com.amazonaws.deepsense.runtimeservice/}

**Comment by Bhat123** [comment]
Everything is working fine now !!  In Trust Relationships section we just need to modify a small section i.e,                 "Service": "lex.amazonaws.com", I followed this link:https://github.com/awslabs/amz-ai-building-better-bots

Happy coding 👍
