### ISSUE TITLE
Readme is not applicable for current version

### ISSUE THREAD

**Issue by gerchicov-bp** [awslabs/aws-sdk-ios-samples#149]
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Objective-C/

What to do with step 5?
CognitoIdentityUserPoolRegion - doesn't even exist in this app

**Comment by behrooziAWS** [comment]
I'm not sure what the confusion is, you edit the Constants file like it says: https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample/Constants.m
