### ISSUE TITLE
Lex BOT not returning fulfillment response

### ISSUE THREAD

**Issue by sujeeth16** [awslabs/aws-sdk-ios-samples#156]
My Lex BOT is configured to return the parameters to client in Fulfillment section, however in my android app, it does not invoke "onReadyForFulfillment" of InteractionListener. It triggers  "promptUserToRespond" during the conversion, but fulfillment does not trigger. This is in TextActivity.

Log

02-10 19:24:47.436 8343-8343/com.amazonaws.sample.lex D/TextActivity: promptUserToRespond:What type of flowers would you like to order?
02-10 19:24:48.697 8343-8343/com.amazonaws.sample.lex D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
02-10 19:24:51.040 8343-8343/com.amazonaws.sample.lex D/TextActivity:  -- Responding with text: roses
02-10 19:24:51.070 8343-9179/com.amazonaws.sample.lex I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-10 19:24:51.110 8343-8343/com.amazonaws.sample.lex W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
02-10 19:24:51.370 8343-8343/com.amazonaws.sample.lex D/TextActivity: promptUserToRespond:What day do you want the roses to be picked up?
02-10 19:24:52.992 8343-8343/com.amazonaws.sample.lex D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
02-10 19:24:55.344 8343-8343/com.amazonaws.sample.lex D/TextActivity:  -- Responding with text: today
02-10 19:24:55.354 8343-8343/com.amazonaws.sample.lex W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
02-10 19:24:55.364 8343-9269/com.amazonaws.sample.lex I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-10 19:24:55.654 8343-8343/com.amazonaws.sample.lex D/TextActivity: promptUserToRespond:Deliver the roses at what time on 2017-02-11?
02-10 19:24:56.575 8343-8343/com.amazonaws.sample.lex D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
02-10 19:24:58.367 8343-8343/com.amazonaws.sample.lex D/TextActivity:  -- Responding with text: now
02-10 19:24:58.387 8343-9332/com.amazonaws.sample.lex I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-10 19:24:58.467 8343-8343/com.amazonaws.sample.lex W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
02-10 19:24:58.717 8343-8343/com.amazonaws.sample.lex D/TextActivity: promptUserToRespond:Deliver the roses at what time on 2017-02-11?
02-10 19:25:00.549 8343-8343/com.amazonaws.sample.lex D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
02-10 19:25:05.484 8343-8343/com.amazonaws.sample.lex D/TextActivity:  -- Responding with text: 7 
02-10 19:25:05.514 8343-9454/com.amazonaws.sample.lex I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-10 19:25:05.624 8343-8357/com.amazonaws.sample.lex I/art: Background partial concurrent mark sweep GC freed 22788(1347KB) AllocSpace objects, 7(448KB) LOS objects, 40% free, 6MB/10MB, paused 5.554ms total 94.512ms
02-10 19:25:05.634 8343-8343/com.amazonaws.sample.lex W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
02-10 19:25:06.104 8343-8343/com.amazonaws.sample.lex D/TextActivity: promptUserToRespond:Okay, your roses will be ready for pickup by 07:00 on 2017-02-11.  Does this sound okay?
02-10 19:25:17.726 8343-8343/com.amazonaws.sample.lex D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
02-10 19:25:22.120 8343-8343/com.amazonaws.sample.lex D/TextActivity:  -- Responding with text: yes
02-10 19:25:22.160 8343-9706/com.amazonaws.sample.lex I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-10 19:25:22.220 8343-8343/com.amazonaws.sample.lex W/IInputConnectionWrapper: getCursorCapsMode on inactive InputConnection
02-10 19:25:22.400 8343-8343/com.amazonaws.sample.lex D/TextActivity: promptUserToRespond:null

**Comment by mlshon** [comment]
Are you using our Lex sample? Have you made any modifications to it?

**Comment by sujeeth16** [comment]
Yes its Lex Sample, Android. Only changes I did are bot_name and identity_id_test.

**Comment by mlshon** [comment]
You could alternatively try using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/) to create an Android sample app using the 'Conversational Bots' feature.

**Comment by minbi** [comment]
Please re-open if the issues still persists after using MobileHub
