### ISSUE TITLE
Push mobile alalytics sample -swift 3.0 convert error

### ISSUE THREAD

**Issue by paultwin0202** [awslabs/aws-sdk-ios-samples#159]
when I open push mobile alaytics sample , I have to convert Swift 3.0.

but it has compile error.

sns.createPlatformEndpoint(request!).continueWith(executor: AWSExecutor.mainThreadExecutor(), block: { (task: AWSTask!) -> AnyObject! in

-> Generic parameter  'ResultType' could not inferred.

**Comment by mlshon** [comment]
Hi,
This sample has not been updated yet for Swift 3 compatibility. 
You can alternatively use [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/) to generate a Swift 3 sample app that uses SNS and Mobile Analytics.
