### ISSUE TITLE
SNS-Mobile-Analytics (Object C) no valid 'aps-environment' entitlement string found for application

### ISSUE THREAD

**Issue by paultwin0202** [awslabs/aws-sdk-ios-samples#161]
Hi I have some issue for SNS-Mobile-Analytics sample.

It shows the error as following.

Failed to register with error: Error Domain=NSCocoaErrorDomain Code=3000 "no valid 'aps-environment' entitlement string found for application" UserInfo={NSLocalizedDescription=no valid 'aps-environment' entitlement string found for application}

https://gitbhub.com/awslabs/aws-sdk-ios-samples/tree/master/SNS-MobileAnalytics-Sample/Objective-C/

I have followed the guide .

1. Getting started with Apple Push Notification Service and Amazone SNS Mobile Push
   -  Through snsmobilepush ->  Get Device Token -> OK
   -  Register Your Mobile App with AWS -> Go to https://console.aws.amazon.com/sns/v2/home and click Create platform application. -> Create PlatformApp -> In the Push notification platform box, select the platform that the app is registered with and then enter the appropriate credentials.  (*.p12)  -> 
Create platform endpoint ->
           ->  Type 1. Device token that I got , 
                          2. Userdata->?? Where I get this -> Is it okay to leave?  -> Add endpoint -> Get ARN

3.  Type ARN in code  -> Appdelegate.m
4.  Type PoolID/ through Cognito
     Region / Cognito
    MobileAnaltics
      **Region : ??** -> where I get this
     
    IAM -> Cognito_SNS_MobileAnalytics_SampleUnauth_Role -> add policy AmazonMobileAnalyticsFullAccess and AmazonSNSFullAccess
     AppId :  From Mobile Analtics 

Thanks

**Comment by mlshon** [comment]
Hi,
You can turn `Push` **ON** in `Capabilities`. This will add the push notification entitlement to the entitlements file.
