### ISSUE TITLE
SNS-Mobile-Analytics (Object C) -- PAC Fetch failed with error [NSURLErrorDomain:-1003]

### ISSUE THREAD

**Issue by paultwin0202** [awslabs/aws-sdk-ios-samples#162]
Hi, I have different issue after I changed push notification in app.

Here is log file.  

It is shown ' SNS_MobileAnalytics_Sample[5012:1360796] PAC Fetch failed with error [NSURLErrorDomain:-1003]' in the log file.

THanks.

**Comment by mlshon** [comment]
Do you have Push and Keychain Access enabled in the Capabilities?

**Comment by paultwin0202** [comment]
Yes, Push notification and keychain Sharing are enabled.

When I test ‘snsmobilepush’ application , it is working as I expected.

I am wondering why ‘SNS_MobileAnalytics_Sample’ is different.


  1.  SNS Service
  2.  Create Platform application
  3.  Push notification platform – Apple development
  4.  Load p12 file
  5.  Create platform endpoint
  6.  Type Device token -  get from ‘snsmobilepush’ application , user data -> No input
  7.  Add endpoint
  8.  Type SNSPlatformApplicationArn = get from platform from SNS Service
  9.  Type Info.plist – PoolId, Region -> Cognito (USEast1)  , AppId, region -> Analytics service (USEast1)  SNS region -> USEast1

When I launch application , ‘SNS_MobileAnalytics_Sample’,  it shows ‘Device Token’ and ‘Endpoint ARN’
But even if I publish a message, there is no push message from service.  But when I test ‘snsmobilepush’, it works.

Thanks.

**Comment by mlshon** [comment]
Does the app have permission for push?
Are you using the sample app as is?

Do you have a debugger attached to show request and response data?

**Comment by paultwin0202** [comment]
Yes I did . I am using sample app as well.

I am wondering if this is right.


  1.  Get device token from ‘AmazoneMobilePush’ App .
  2.  In SNS service
     *   Create platform application
     *   Create platform endpoint   -> type device token from AmazoneMobilePush app
     *   Publish to endpoint -> Type  any letters in Message

        SNS_MobileAnalytics_sample app is still showing  ‘Device Token’ , ‘Endpoint ARN’ . Do not show push message .
        And then enabled value is changed into false. Also there is another token is generated by automatically.

        I am wondering why it is different behaviour compared to ‘AmazoneMobilePush’


Thanks.

**Comment by kredden** [comment]
Checking in to see if you were ever able to get this working.

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. It the problem persists please open an issue in aws/aws-sdk-ios.
