### ISSUE TITLE
IoT Sample

### ISSUE THREAD

**Issue by paultwin0202** [awslabs/aws-sdk-ios-samples#163]
It shows compile error as following.

AppDelegate.swift

let configuration = AWSServiceConfiguration(
            region: AwsRegion,
            credentialsProvider: credentialProvider)  

 -> **Compile error -> Cannot convert value of type '(regionType:AWSRegion, identityPooldId: String)' to expected argument type 'AWSCredentialProvider'**

**Comment by fengsongAWS** [comment]
Hi @paultwin0202 ,

The region is supposed to be the IoT Region in your AWS IoT console for example AWSRegionType.USWest2. The credentialsProvider is supposed to be the pool ID of your cognito for example "us-west-2:xxxxxxx-xxxx-xxxx-xx-xxx"
Thanks,
Fengyi

**Comment by minbi** [comment]
Please re-open if the issue still exists
