### ISSUE TITLE
issue when create AWSLexVoiceButton

### ISSUE THREAD

**Issue by kisskumam** [awslabs/aws-sdk-ios-samples#166]
Hi, 
I'm currently working on this sample code. I'm trying to add AWSLexVoiceButton into the left bar container of JSQ input tool bar.
### 1. Create an extension and implement AWSLexVoiceButtonDelegate
```

extension ChatViewController: AWSLexVoiceButtonDelegate{
    
    func voiceButton(_ button: AWSLexVoiceButton, on response: AWSLexVoiceButtonResponse) {
        DispatchQueue.main.async(execute: {
            
            print("on text output \(response.outputText)")
            //self.output.text = response.outputText
        })
    }
    
    public func voiceButton(_ button: AWSLexVoiceButton, onError error: Error) {
        print("error \(error)")
    }

}

```

### 2. create AWSLexVoiceButton instance and assign the delegate

```

 let voiceButton = AWSLexVoiceButton()
 override func viewDidLoad() {
        super.viewDidLoad()
        count = 0
        self.interactionKit = AWSLexInteractionKit.init(forKey: "chatConfig")
        self.interactionKit?.interactionDelegate = self
        
        self.showLoadEarlierMessagesHeader = false
        self.collectionView?.collectionViewLayout.incomingAvatarViewSize = CGSize.zero
        self.collectionView?.collectionViewLayout.outgoingAvatarViewSize = CGSize.zero
        
        self.inputToolbar.contentView?.textView?.keyboardType = UIKeyboardType.default
        self.messages = [JSQMessage]()
        
        let bubbleFactory = JSQMessagesBubbleImageFactory()
        self.outgoingBubbleImageData = bubbleFactory?.outgoingMessagesBubbleImage(with: UIColor.jsq_messageBubbleLightGray())
        self.incomingBubbleImageData = bubbleFactory?.incomingMessagesBubbleImage(with: UIColor.jsq_messageBubbleGreen())

        self.inputToolbar.contentView?.leftBarButtonItem = nil;
        **(self.voiceButton as AWSLexVoiceButton).delegate = self**
    }

```

### 3.  Add to the input tool bar on ViewDidLayoutSubviews
```

 override func viewDidLayoutSubviews() {
       self.inputToolbar.contentView?.leftBarButtonItemWidth = 60
       self.inputToolbar.contentView?.leftBarButtonContainerView.addSubview(self.voiceButton)
    }

```
But, at the result, it show nothing. Any help please!

Huge thanks!

**Comment by karthiksaligrama** [comment]
do you have some pic/diagram representation of what you are trying to do?

**Comment by kisskumam** [comment]
<img width="375" alt="screen shot 2017-03-07 at 9 37 39 am" src="https://cloud.githubusercontent.com/assets/7647142/23639355/c8a546d2-0319-11e7-8a0b-7ac754a18135.png">

I'm gonna do something like this. Voice button on the left bar of input view. 
In normal situation, I should create AWSLexVoiceButton programmatically and add like a subview onto self.inputToolbar.contentView?.leftBarButtonContainerView. But it doesnt work. Therefore, I have to create it by this way: 
` override func viewDidLayoutSubviews() {
        
        // Drop the AWSLexVoiceButton into a nib file
        let testView = TestViewController(nibName: "TestViewController", bundle: nil)
        testView.view.frame =  CGRect(x: 0, y: -10, width: 35, height: 35)
        
        // Get the lex voice button from the testview
        let voiceButton = testView.voiceButton
        voiceButton?.frame =  CGRect(x: 0, y: -10, width: 35, height: 35)
        voiceButton?.delegate = self
        
        // Assign the voice button to navigation bar -> lef bar button item
        let leftBarButton = UIBarButtonItem(customView: voiceButton!)
        self.navigationItem.leftBarButtonItem = leftBarButton
        
        // Add the lefbarbutton.customview into the input tool bar
        self.inputToolbar.contentView.addSubview(leftBarButton.customView!)
        
        // Finally, it will bring the left bar button from the navigation bar to the input tool bar
    }`

**Comment by kisskumam** [comment]
And please provide the way to resize this button. Thank you!

**Comment by karthiksaligrama** [comment]
I think for your use case you are better off implementing your custom view and use the same source code as the voice button because your use case is very specific, that way you can also share the interaction client and switch between voice modes and text modes more easily.

Even if we do provide a way to resize you will still have issues with animation etc.
