### ISSUE TITLE
Code=12 "The operation couldn’t be completed. ResourceNotFoundException 

### ISSUE THREAD

**Issue by patelrohan** [awslabs/aws-sdk-ios-samples#17]
I am getting this error after correctly putting constants in Constant.swift

```
Error: Error Domain=com.amazonaws.AWSDynamoDBErrorDomain Code=12 "The operation couldn’t be completed. (com.amazonaws.AWSDynamoDBErrorDomain error 12.)" UserInfo=0x7fd92bec6650 {__type=com.amazonaws.dynamodb.v20120810#ResourceNotFoundException, message=Requested resource not found}
```

Any suggestion what I might be doing wrong?

**Comment by yosuke-matsuda** [comment]
`ResourceNotFoundException` indicates some resource you are trying to access does not exist. (e.g. the table you are querying from does not exist.) Can you share the code snippet and detail steps to reproduce the issue?

**Comment by patelrohan** [comment]
Is it possible that the DynamoDB database is on different server from Cognito? 

Thanks,
Rohan.

**Comment by yosuke-matsuda** [comment]
They are separate and independent services (you can use them together, though).

**Comment by patelrohan** [comment]
Ok. Quick question: Will it fetch data from any table I have on DynamoDB or am I supposed to create the table with rows exactly same as it is given in `DDBDynamoDBManager.h` (i.e. UserId, GameTitle, TopScore,Wins, Losses)

**Comment by yosuke-matsuda** [comment]
The DynamoDB attribute names and the mapped object properties need to match.

**Comment by patelrohan** [comment]
Alright thanks. I think having same server for Conginto and DynamoDB solved the error.

**Comment by theonestep4** [comment]
Doesn't the 'createTable' function create the attribute names when it creates the table?

**Comment by patelrohan** [comment]
No. You need to match the attributes present in the table. The instruction given in readme is ambiguous.
