### ISSUE TITLE
No such module 'AWSCognitoIdentityProvider'

### ISSUE THREAD

**Issue by sindrevr** [awslabs/aws-sdk-ios-samples#170]
Hi,

After following the instructions and when hitting "Build" i get error "No such module 'AWSCognitoIdentityProvider'"

Xcode 8.2.1 , Swift
CognitoYourUserPools-Sample

Anyone experienced this issue when loading this sample project?

**Comment by rohandubal** [comment]
Hi, 

Could you please provide steps to reproduce this error? 

Did you run pod install and open the xcworkspace file?

Thanks,
Rohan

**Comment by sindrevr** [comment]
Hi rohandubal!

Thank you for your early reply.
No, I opened the "xcodeproj" file, when using the xcworkspace file it worked fine.
Cheers!

BR,
Sindre
