### ISSUE TITLE
Upload just hanging

### ISSUE THREAD

**Issue by cdowney102** [awslabs/aws-sdk-ios-samples#171]
Hi guys, 

Very new to S3 and loving these samples. However, whenever I run the code in UploadViewController, the status bar gets to about 90% every time and then just hangs for a few minutes before ultimately displaying the "Failed" status label. This is swift 3, xcode 8.2.1.

Any ideas why I can't get the upload to work?

Thank you!

**Comment by cdowney102** [comment]
Hi @mlshon ,

The sample found at https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/UploadViewController.swift

s3 background transfer in swift -> uploadviewcontroller

**Comment by mlshon** [comment]
Does the role associated with the identity pool have proper permissions? PutObject, GetObject, etc

**Comment by cdowney102** [comment]
Yes, it does have those roles (the putObject was missing but I have since then added it and re-tested). I don't always get an error. Most of the time it just hangs indefinitely. 

Thank you @mlshon

**Comment by mlshon** [comment]
I am unable to reproduce the error. Could you answer these questions for me?
What SDK version are you using? Are you using the sample as is or did you make any changes? Do you have some logs (requests, responses, etc)? Is this on a simulator or on a real device?

What is the size of the file you're uploading? What is the content type?

**Comment by cdowney102** [comment]
- aws mobile sdk for ios, whichever is newest..? I just downloaded it off AWS a week ago
-using sample completely as is
- xcode simulator
-i am choosing a photo from the default simulator photo library

Thank you

**Comment by mlshon** [comment]
It may be because of the role needs more permissions or you may be allowing permission on a wrong resource. Could you give me the policy? Or try attaching AmazonS3FullAccess policy and see if your uploads are working fine. If so, the issue is with the policy you're using.

**Comment by cdowney102** [comment]
It is finally working. I am not sure what the problem was, I did not change anything from yesterday. I just tried it again and it was hanging so I re-attempted to upload 3 times in a row and it finally worked...

Maybe this was an xcode thing....? Either way, I am relieved and really appreciate your help.

Thank you! @mlshon
