### ISSUE TITLE
AWS Cognito , logins method of AWSIdentityProviderManager protocol is not getting called for iOS using swift

### ISSUE THREAD

**Issue by abhishekstl** [awslabs/aws-sdk-ios-samples#174]
We are trying to use AWS Cognito for Facebook login, 
However when integrating with the code as per AWS documentation

    class FacebookProvider: NSObject, AWSIdentityProviderManager {
            
        func logins() -> AWSTask<NSDictionary> {
                    if let token = AccessToken.current?.authenticationToken {
                        return AWSTask(result: [AWSIdentityProviderFacebook:token])
                    }
                    return AWSTask(error:NSError(domain: "Facebook Login", code: -1 , userInfo: ["Facebook" : "No current Facebook access token"]))
                }
            }

below code we have written in AppDelegate.swift in didFinishLaunchingWithOptions method 

    FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
    
         let obj = FacebookProvider()
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1, identityPoolId:"somepoolid",identityProviderManager: obj)
        
        let configuration = AWSServiceConfiguration(region:.USEast1, credentialsProvider:credentialsProvider)
                
  AWSServiceManager.default().defaultServiceConfiguration = configuration

however as per documentation the logins method is not getting called

Since the logins method is not getting called we are not able to pass facebook authentication token to amazon cognito

Any help will be highly appreciated

**Comment by karpov3** [comment]
@abhishekstl did you find a solution? I have the same problem. Thank's

**Comment by yusufonderd** [comment]
same problem I'm waiting .

**Comment by paul-bonneville** [comment]
Same problem here. Did anyone find a work around?

**Comment by behrooziAWS** [comment]
Are you making any calls to an AWS service? The logins method is lazily called the first time credentials are needed.

Alternatively you could force it to get credentials by calling:

credentialsProvider.credentials().continueOnSuccessWith { (task:AWSTask<AWSCredentials>) -> Any? in
            print(task.result!)
        }

**Comment by paul-bonneville** [comment]
My main issue here is that I need Cognito to know about the login that was just completed through the Facebook login screen. The Facebook modal view pops up (after completely the Facebook Login SDK implementation), I log in and authenticate with Facebook and get back all the applicable session and user info from Facebook...but Cognito is not aware of the information. 

From the AWS Facebook documentation [here](http://docs.aws.amazon.com/cognito/latest/developerguide/facebook.html ) it sounds like the AWSIdentityProviderManager delegate is supposed to pick up the Facebook response but it never does. I have Facebook session data and an unauthenticated Cognito user, but the goal is to log in with Facebook data. 

I am sure I am not understanding something correctly here with regards to why the delegate is not getting called, but I can't get to the bottom of it.

**Comment by sweeneyapps** [comment]
@paul-bonneville  FB SDK is standalone, FB login response doesn't trigger AWSIdentityProviderManager delegate.  But when you are logging in Facebook on your app, FB SDK will save the token inside AccessToken or FBSDKAccessToken if you are bridging FB SDK w/ Objective C.   

When your app is accessing any AWS service, it will run the func logins in the AWSIdentityProviderManger delegate.   The delegate will load the token into Cognito.    

If you enabled FacebookID on your Authentication providers inside the Federated Identities, then the Facebook user who logged in your app will have an authenticated role.    You can grant access to the database and other AWS service using the policy statement attached to the role.

**Comment by mvpscottjon** [comment]
@abhishekstl 

try 
`credentialsProvider.credentials()`
after you success to login

I success to call "login" method and my federated identity get Fb login.

But I can't figure out how to map attributes to cognito user pool.....

------------------------------------------------------

my fb provider class:


```import UIKit  
import AWSCognitoIdentityProvider
import FacebookCore
class FacebookProvider: NSObject, AWSIdentityProviderManager {
    func logins() -> AWSTask<NSDictionary> {
        if let token = AccessToken.current?.authenticationToken {
            return AWSTask(result: [AWSIdentityProviderFacebook:token])
        }
        return AWSTask(error:NSError(domain: "Facebook Login", code: -1 , userInfo: ["Facebook" : "No current Facebook access token"]))
    }
} 
```

my fb credentailsProvider:
``` let fbProvider = FacebookProvider() 
 let fbcredentialsProvider = AWSCognitoCredentialsProvider(regionType: .APNortheast1, identityPoolId: "my federated id", identityProviderManager: fbProvider)
  let configuration = AWSServiceConfiguration(region: .APNortheast1, credentialsProvider:fbcredentialsProvider)
  AWSServiceManager.default().defaultServiceConfiguration = configuration
```



when I success login from Fb, I call this API,
` credentialsProvider.credentials()
`

federated identity settings:
<img width="497" alt="2017-11-23 10 35 46" src="https://user-images.githubusercontent.com/24777585/33157146-db6d0afe-d03a-11e7-9257-b65a269384d4.png">

user pool settings:
<img width="1138" alt="2017-11-23 10 43 24" src="https://user-images.githubusercontent.com/24777585/33157192-3b2994ee-d03b-11e7-9ac7-c9d04c738dc5.png">
mapping settings
<img width="1070" alt="2017-11-23 10 43 40" src="https://user-images.githubusercontent.com/24777585/33157191-3b028020-d03b-11e7-8f50-7aaec0ded936.png">


but I can't get new userPool user when I log in from Fb

**Comment by sourabhzynq** [comment]
Hi,

**Comment by sourabhzynq** [comment]
Hi,

I am facing similar issue, my code is in Objective C. I am using AWS Cognito Federated ID with my iOS app for social providers (Facebook, Google). After sign in with Facebook, user is getting error '_Token is not from a supported provider of this identity pool_'. If I allow unauthenticated ids in Fed IDs, then that user gets unauthenticated user id (linked logins = 0) in Identity browser and gets session key etc. 

I have added Facebook in Authenticated Providers for Federated ID.
I have also added Facebook in Identity Providers for User Pool and done attributes mapping (mapped Id and Email).

my FB provider class:
```
#import "AWSSocialIdentityProvider.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

@implementation AWSSocialIdentityProvider 

- (AWSTask<NSDictionary<NSString *, NSString *> *> *)logins {
    FBSDKAccessToken* fbToken = [FBSDKAccessToken currentAccessToken];
    if(fbToken){
        NSString *token = fbToken.tokenString;
        return [AWSTask taskWithResult: @{ AWSIdentityProviderFacebook : token }];
        NSLog(@"FB Token inside AWSSocialIdentityProvider class is: %@", token);
        
    } else {
        
        NSLog(@"FB Token is not found in AWSSocialIdentityProvider class");
        return [AWSTask taskWithError:[NSError errorWithDomain:@"facebook"
                                                          code:-1
                                                      userInfo:@{@"error":@"No current Facebook access token"}]];
    }
}
```
My fb credentials provider (I am implementing it inside _didCompleteWithResult_ method of FBSDKButtonDelegate: This method gets called only when user login with FB is succsessful):

```
- (void)loginButton:(FBSDKLoginButton *)loginButton didCompleteWithResult:(FBSDKLoginManagerLoginResult *)result error:(NSError *)error {
    if(!error){
        NSLog(@"FB Access token onFbSignIn is: %@", [FBSDKAccessToken currentAccessToken]);
        self.fbCredentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"us-east-1:b7353580-6b4c-4d15-8cbf-27b59bf4b6bf" identityProviderManager:self.socialProvider];
        NSLog(@"Cognito credentials provider value onFbSignIn is: %@", self.fbCredentialsProvider);
       AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:self.fbCredentialsProvider];
       [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;
 
        //wipe cached credentials
        [self.fbCredentialsProvider clearCredentials];
        
        //For calling fb logins
        [[self.fbCredentialsProvider credentials] continueWithSuccessBlock:^id(AWSTask *task) {
            
            NSLog(@"Result of credentials : %@", task.result);
            
            return nil;
            
        }];
    }
}
```

Can anyone help in resolving the error?

**Comment by sourabhzynq** [comment]
Hi,

I am facing similar issue, my code is in Objective C. I am using AWS Cognito Federated ID with my iOS app for social providers (Facebook, Google). After sign in with Facebook, user is getting error '_Token is not from a supported provider of this identity pool_'. If I allow unauthenticated ids in Fed IDs, then that user gets unauthenticated user id (linked logins = 0) in Identity browser and gets session key etc. 

I have added Facebook in Authenticated Providers for Federated ID.
I have also added Facebook in Identity Providers for User Pool and done attributes mapping (mapped Id and Email).

my FB provider class:
```
#import "AWSSocialIdentityProvider.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

@implementation AWSSocialIdentityProvider 

- (AWSTask<NSDictionary<NSString *, NSString *> *> *)logins {
    FBSDKAccessToken* fbToken = [FBSDKAccessToken currentAccessToken];
    if(fbToken){
        NSString *token = fbToken.tokenString;
        return [AWSTask taskWithResult: @{ AWSIdentityProviderFacebook : token }];
        NSLog(@"FB Token inside AWSSocialIdentityProvider class is: %@", token);
        
    } else {
        
        NSLog(@"FB Token is not found in AWSSocialIdentityProvider class");
        return [AWSTask taskWithError:[NSError errorWithDomain:@"facebook"
                                                          code:-1
                                                      userInfo:@{@"error":@"No current Facebook access token"}]];
    }
}
```
My fb credentials provider (I am implementing it inside _didCompleteWithResult_ method of FBSDKButtonDelegate: This method gets called only when user login with FB is succsessful):

```
- (void)loginButton:(FBSDKLoginButton *)loginButton didCompleteWithResult:(FBSDKLoginManagerLoginResult *)result error:(NSError *)error {
    if(!error){
        NSLog(@"FB Access token onFbSignIn is: %@", [FBSDKAccessToken currentAccessToken]);
        self.fbCredentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"us-east-1:XXXXXXXXXXX" identityProviderManager:self.socialProvider];
        NSLog(@"Cognito credentials provider value onFbSignIn is: %@", self.fbCredentialsProvider);
       AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:self.fbCredentialsProvider];
       [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;
 
        //wipe cached credentials
        [self.fbCredentialsProvider clearCredentials];
        
        //For calling fb logins
        [[self.fbCredentialsProvider credentials] continueWithSuccessBlock:^id(AWSTask *task) {
            
            NSLog(@"Result of credentials : %@", task.result);
            
            return nil;
            
        }];
    }
}
```

Can anyone help in resolving the error?

**Comment by vysotsky** [comment]
Any progress?

**Comment by constantineSafronov** [comment]
Have exactly the same issue. I spent a lot of time looking for the solution and i found that, there are two completely different pools, user pool and federal Identity pool, and they are not connected with each other.

**Comment by fr0hike** [comment]
Does anyone have a Swift4 complete example? Im having trouble with this

**Comment by moosabaloch** [comment]
Anybody with Swift4 example ?

**Comment by lpkim626** [comment]
I need help on Swift3 as well.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
