### ISSUE TITLE
Build break on MacOS with case-sensitive filesystem

### ISSUE THREAD

**Issue by mkistler** [awslabs/aws-sdk-ios-samples#18]
Line 19 in DeveloperAuthenticationClient.m:

    #import <UICKeychainStore/UICKeychainStore.h>

should be

    #import <UICKeyChainStore/UICKeyChainStore.h>

**Comment by yosuke-matsuda** [comment]
Thank you for the report. We'll update it with the next push.

**Comment by yosuke-matsuda** [comment]
We've updated the sample. Thanks.
