### ISSUE TITLE
Sign in AWSTaskCompletionSource is nill

### ISSUE THREAD

**Issue by ijknm** [awslabs/aws-sdk-ios-samples#180]
New to AWS framework but it work like anything I am not faced any issue until today from last 1 week
-Sign up Works fine get OTP (phone number verification)
-Confirm Sign Up Works Fine (Successfully confirm)
-Sign in getting an issue.
bellow code:
```
-(IBAction)didTapOnSignInButton:(id)sender{  self.passwordAuthenticationCompletion.result = [[AWSCognitoIdentityPasswordAuthenticationDetails alloc] initWithUsername:_usernameText password:self.ibPassword.text];
NSLog(@"%@",self.passwordAuthenticationCompletion);
}
-(id<AWSCognitoIdentityPasswordAuthentication>) startPasswordAuthentication {
    return self;
}
-(void) getPasswordAuthenticationDetails: (AWSCognitoIdentityPasswordAuthenticationInput *) authenticationInput  passwordAuthenticationCompletionSource: (AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> *) passwordAuthenticationCompletionSource {
    self.passwordAuthenticationCompletion = passwordAuthenticationCompletionSource;
    dispatch_async(dispatch_get_main_queue(), ^{
        if(!self.usernameText)
            self.usernameText = authenticationInput.lastKnownUsername;
    });   
}
-(void) didCompletePasswordAuthenticationStepWithError:(NSError*) error {
    dispatch_async(dispatch_get_main_queue(), ^{
        if(error){
              nslog(@"Error ");
        }else{
            self.usernameText = nil;
            [self dismissViewControllerAnimated:YES completion:nil];
        }
    });
}
self.passwordAuthenticationCompletion = nill
```
Printing description of self->_passwordAuthenticationCompletion:

and never called getPasswordAuthenticationDetails and didCompletePasswordAuthenticationStepWithError
what is wrong.......

Following this document
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample

**Comment by behrooziAWS** [comment]
Did you set the delegate on your AWSCognitoIdentityUserPool.delegate to this class?

**Comment by ijknm** [comment]
ya in viewDidload I added

**Comment by ijknm** [comment]
Still i am facing this issue please help me get it...

**Comment by manishkumar** [comment]
Try doing a `user.getSession()` in your viewDidLoad

**Comment by tikipatel** [comment]
I see this issue infrequently. Any other insight?

**Comment by muellerfr** [comment]
Hello @ijknm,

Sorry for the delay. Do you still require help with the issue?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
