### ISSUE TITLE
AWS Polly SUPER slow to answer (based on sample code) :: is it just me? / can I speed it up?

### ISSUE THREAD

**Issue by Daij-Djan** [awslabs/aws-sdk-ios-samples#181]
Hi
AWS Polly is SUPER slow to answer (based on sample code) :: is it just me? / can I speed it up?

BR
Dominik

**Comment by Daij-Djan** [comment]
p.s. reducing sample rate does not help noticeably :(

**Comment by rohandubal** [comment]
Hello @Daij-Djan 

Can you elaborate little more? Is the connection wifi / cellular? How is the bandwidth?

**Comment by Daij-Djan** [comment]
sure! sorry for me being so 'brief'

1. im on ios. doing swift
2. The connection im using is WiFi and the bandwith is ~300k

---

Now the time it takes for the 'intial polly' request is neglectable. I get a url for the mp3 quite fast.
BUT then the time between setting this NSURL for the AVPlayer and the phone actually playing sound takes a noticable big amount (Id say 2-4 seconds even)

**Comment by Daij-Djan** [comment]
to verify it isnt our wifi I retried with cellular (4g - normally fast enough)
=> same result

**Comment by rohandubal** [comment]
Are you fetching the entire stream before playing?

**Comment by Daij-Djan** [comment]
well, i am using your samplycode for ios - I must admit I dont know what AVPlayer does internally. I  hoped your sample code is already streaming the mp3 ok

**Comment by karthiksaligrama** [comment]
@Daij-Djan  what region are you connecting to?

**Comment by karthiksaligrama** [comment]
@Daij-Djan  ok so the culprit is the default player on ios. It does not support streaming content. Which is why you see a lag in the player.

**Comment by Suneel-Gunupudi** [comment]
How to notify, the received request of aws Polly audio received. Bcoz, the audio file URL is executed quickly, but the audio file for play is taking much time.
