### ISSUE TITLE
Push banner showing while app is in active state

### ISSUE THREAD

**Issue by danieldelouya** [awslabs/aws-sdk-ios-samples#182]
How do i disable that? I get normal push notification banner topdown when the app is running and it receives a push notification. 
Using default mobile hub code..

**Comment by wdane** [comment]
Hi Danieldelouya,

Unfortunately we do not offer generic iOS development support, only issues directly pertaining to AWS or our sample code. I would suggest checking out apples documentation on push notifications or search Stackoverflow.

Sorry,
Weston
