### ISSUE TITLE
Unable to upload images to subfolders

### ISSUE THREAD

**Issue by trillf0rd** [awslabs/aws-sdk-ios-samples#183]
I have been successfully able to upload images from an iphone to a bucket. I have in constants.swift: 
let S3BucketName: String = "bucket" 
However, I am not able to upload to subfolders in this bucket. In trying, I am setting in constants.swift:
let S3BucketName: String = "bucket/subbucket" 

I am able to upload to this subbucket with the same poolId and bucket name on android using the Android S3TransferUtilitySample. 

When I attempt to upload to the subbucket on iphone. The progress bar never begins uploading and the message is stuck at "Generating Upload File". I do not receive any errors in the console and the console says "AWSTask: 0x1740722c0; completed = YES;" but no file is uploaded to the bucket.

**Comment by behrooziAWS** [comment]
There is no such thing as a subbucket, there is just a bucket.  subbucket/ needs to be part of your key name.

**Comment by trillf0rd** [comment]
Awesome, thanks behrooziAWS for the quick response. I should have referenced uploading to a folder within a bucket in my question. For anyone encountering this problem, I was able to upload to a folder within a bucket by keeping:
let S3BucketName: String = "bucket"
and changing:
let S3UploadKeyName: String = "new1.jpg"
to:
let S3UploadKeyName: String = "subbucket/new1.jpg"
