### ISSUE TITLE
How to handle case when valid Cognito auth token already exists?

### ISSUE THREAD

**Issue by gc435** [awslabs/aws-sdk-ios-samples#186]
I want to modify _CognitoYourUserPools-Sample_ to work with my iOS/Swift app.

I have a ViewController with one UIButton outlet called `loginLogoutButton` and one UILabel outlet called `loggedInUserLabel`.  The label displays the user's name.

If a user has never logged in, the button's title is **Login**.  When clicked, it runs this code borrowed from _CognitoYourUserPools-Sample_:

        self.user?.getDetails().continueOnSuccessWith { (task) -> AnyObject? in
            DispatchQueue.main.async(execute: {
                self.response = task.result
                self.loginLogoutButton.setTitle("Logout", for: .normal)
            })
            return nil
        }

`response` has a property observer which sets the `loggedInUserLabel` text:

    var response: AWSCognitoIdentityUserGetDetailsResponse? {
        didSet {
            loggedInUserLabel.text = response?.userAttributes?[2].value
        }
    }

I believe the above code correctly handles the case when a user first logs in, or has logged out and then back in again.

However, **how should I handle the case when a user quits the app while still logged in?**  In this case, a valid authentication token already exists.  How can I detect this situation and adust my UI accordingly?  For example, the button should say **Logout** and the label should display the user's name.  Since the name might take a long time to be retrieved asynchronously, I'm not sure what to do.

**EDIT:** I now see `AWSCognitoIdentityUser.isSignedIn`.  I think [the relevant line in the SDK source](https://github.com/aws/aws-sdk-ios/blob/b79dbbc9b1547684092028792c0a17448265705a/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.h#L77) implies this property will be `true` as long as the refresh token has not expired.  My app's refresh token expiration is set to 30 days.  If this means `isSignedIn` will be `true` for 30 days, then I know what to do.

**Comment by minbi** [comment]
Feel free to re-open this issue if there are further questions
