### ISSUE TITLE
Do we have PubSubWebSocket sample similar to android sample?

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#187]
We have [AndroidPubSubWebSocket](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSubWebSocket) sample where we just need to configure

CUSTOMER_SPECIFIC_ENDPOINT = "<CHANGE_ME>";
COGNITO_POOL_ID = "<CHANGE_ME>";
MY_REGION = Regions.US_EAST_1;

Do we have similar sample in iOS? I'm unable to find!

**Comment by kvasukib** [comment]
Hi @SanyasiraoM,

Thanks for reporting to us.

We have IoTTemperatureControl Sample App here: 
https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoTTemperatureControl-Sample/Swift/IoTTemperatureControlSample/

You can look up the Constants.swift to specify the configuration information:
https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoTTemperatureControl-Sample/Swift/IoTTemperatureControlSample/Constants.swift

The App connects via WebSocket here:
https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoTTemperatureControl-Sample/Swift/IoTTemperatureControlSample/ViewController.swift#L310

Please let us know if you have any further questions.

**Comment by SanyasiraoM** [comment]
Thank you @kvasukib.
