### ISSUE TITLE
Unable to connect to server, where to configure Client end point or Host?

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#188]
Hi,
I configured cognito identity pool id and region in Constants.swift. But when I click on connect, it's saying Unable to create keys and/or certificate, check values in Constants.swift.

And I'm able to connect to server with same cognito identity pool id in [AndroidPubsubWebSocket](https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSubWebSocket) sample

And where to configure CLIEND_END_POINT (XXXXXXXXXX.iot.<region>.amazonaws.com) similar to https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSubWebSocket/src/com/amazonaws/demo/androidpubsubwebsocket/PubSubActivity.java#L47

Thank you.

**Comment by kvasukib** [comment]
Hi @SanyasiraoM,

Thanks for reporting to us.

"Unable to create keys and/or certificate, check values in Constants.swift."
In the file https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/Constants.swift
you need to fill in the certificates.

Issue-2:
"And where to configure CLIEND_END_POINT (XXXXXXXXXX.iot..amazonaws.com)"
In the file https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/Constants.swift
fill in the IOT_ENDPOINT

**Comment by SanyasiraoM** [comment]
Hi @kvasukib 

Thank you!

Sorry for the second issue, Some how that line got deleted from my side I guess.
