### ISSUE TITLE
Where can I replace certificate and private key instead of creating from cognito in iOS Sample?

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#189]
Hi,

In our use case we are generating certificate and private keys at backend service. And backend will send them to user in strings format when users login . So we uses certificates generated at our backend instead of generating them using cognito.

In android sample we replaced them at line https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java#L202,L203 and commented cognito part. You can check it in https://bitbucket.org/snippets/SunnyiB/jqGXB

I was bit confused in ios sample https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift as it's trying to create some p12 file and certificateId. So where can I replace my certificate and private key values as string and and commenting the cognito part?

Thank you!.

**Comment by bxpan** [comment]
Hi SanyasiraoM,

The certificates are stored in the keychain on iOS, the sample app reads from the keychain and use that to connect to IoT. As shown in the README file, you may generate the .p12 from you certificate file and private key, then import it into iOS keychain. Please refer to the bottom of https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/README.md

Thanks.

**Comment by SanyasiraoM** [comment]
@kvasukib My doubt is not cleared yet. I will the close issue my self once resolved

**Comment by SanyasiraoM** [comment]
I don't have physical certificate and private key files to generate .p12 from certificate. Our backend server will generate the certificates and sends them in string format when user login. And moreover I can't hard code them as they are unique for each user.

In android they gave option to keep certificate and private keys generated from our backend in https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java#L202,L203

@fengsongAWS replied https://github.com/aws/aws-iot-device-sdk-java/issues/28#issuecomment-309905231

I don't know how to do similarly in iOS as i'm new to iOS.
