### ISSUE TITLE
How to hide default chat/text screen as I need to show some button, Before shows

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [awslabs/aws-sdk-ios-samples#190]
Hi Amazon, 
Thanks for amazing framework. But, I am facing some issue, I want to show my customised button in chat/Text view screen. Once I pressed that button, then only I want to show chat screen, But I want those two in same screen. I tried, but default, its showing chat view.

Can anyone suggest me, how to do this.

**Comment by kvasukib** [comment]
Hi @AnilkumarRabhasa,

Thanks for reporting to us.

Can you give the name of the sample app in this repository that you are referring to?

**Comment by AnilkumarRabhasa** [comment]
https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoSync-Sample/Objective-C/

pls check.

thanks for quick response.

**Comment by kredden** [comment]
Are you sure that is the correct sample?  The one is for showing how to use Cognito Sync.  I assume from your question you were trying to do something with Lex?  Is it still an issue?

**Comment by AnilkumarRabhasa** [comment]
Yes, it was, any way, currently we are working on other project. But, if possible please provide the suggestions to fix this issue. Thanks!

**Comment by kredden** [comment]
It isn't very clear what you are trying to do.  Sounds like you might need to add some more controllers.
