### ISSUE TITLE
CognitoSync-Sample conversion to Swift 3.0?

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [awslabs/aws-sdk-ios-samples#194]
Hi,

Under the requirement you didn't mentioned it for swift 3.0 and later version so is it support swift 3.0 or not?

Thanks,

**Comment by behrooziAWS** [comment]
Which sample are you referring too?

**Comment by kvasukib** [comment]
Hi @Rahulgupta-cdnsol,

Thanks for reporting to us. Which SampleApp are you referring to?

**Comment by jasonb202020** [comment]
hey all .. CognitoSync-Sample .. has anyone converted to Swift 3?

Super keen to get a *working* version in Swift 3 illustrating the best practice approach for authenticating users via FB,Google,Twitter.

--

**Comment by jasonb202020** [comment]
*bump* . any word from the AWS team on a SWIFT3 update for this reference implementation?
anyone got a working project they'd be happy to share?

**Comment by seanh-spindance** [comment]
Agreed - this would be super helpful.

**Comment by kcsham** [comment]
And how about Swift4 with iOS11. I'm starting a new project and would very much like to us AWS and staying on the latest iOS and tools.

**Comment by adrianhall** [comment]
Does this not do it for you? http://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html

**Comment by johndpope** [comment]
ffs - this is a waste of time -CognitoSync-Sample - please update. 


![screen shot 2018-02-07 at 10 00 07 am](https://user-images.githubusercontent.com/289994/35923692-f38b0d62-0bee-11e8-925a-9abb329ed3b0.png)

I found this code which is compiling with swift 3. 
https://github.com/dkabyshev/AWS_APILess_SwiftApp/blob/master/AWSBased_SwiftAppDemo/SessionProviders/AmazonClientManager.swift

**Comment by muellerfr** [comment]
Hello @Rahulgupta-cdnsol,

Please use [AWS AppSync](https://aws.amazon.com/appsync/resources/) instead of Amazon Cognito Sync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.

It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

Please let us know if you have any questions about AppSync.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.

**Comment by johndpope** [comment]
@muellerfr  -   while all these tickets are being closed - it's important to check all the sample code - and make sure it's every one is working. this repo stinks of code rot the last time I checked it.

**Comment by muellerfr** [comment]
@johndpope Totally agree with you. We are in the process of refreshing the sample that we will maintain going forward. Other samples, like CognitoSync, will be deprecated/archived.
