### ISSUE TITLE
InvalidIdentityPoolConfigurationException

### ISSUE THREAD

**Issue by jonny009** [awslabs/aws-sdk-ios-samples#195]
I am trying to integrate Lex into my application and get the following error when I press the AWSLexVoiceButton:
InvalidIdentityPoolConfigurationException, message=Invalid identity pool configuration. Check assigned IAM roles for this pool.

My identity pool is configured to use the AWSServiceRoleForLexBots role for unauthenticated users.

**Comment by rohandubal** [comment]
Is you unauth role tied with the identity pool? Also can you try out Mobile Hub?  Mobile Hub will configure the IAM policies and roles for you and also provide a demo application.

**Comment by jonny009** [comment]
Mobile Hub seems to have done the trick.
