### ISSUE TITLE
DynamoDB and Cognito Gov account

### ISSUE THREAD

**Issue by danielet** [awslabs/aws-sdk-ios-samples#196]
Hi,
I was trying to use DynamoDB with my gov aws gov account. The first thing  I noticed that wasn't Cognito an option available on AWS gov dashboard.

Do you have any suggestion to use Dynamo db + iOS + gov account ?

Thanks

**Comment by kvasukib** [comment]
Hi @danielet, Cognito is not yet available in the AWS Gov. http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-services.html. You can, however, use DynamoDB.
