### ISSUE TITLE
How to remove cognito part if I have manually created certificate in IoT-Sample example?

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#197]
Hi,

In the [IoT-Sample](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift) , How to remove the cognito part if I already have hard coded certificate?. 

I'm able to do in [android sample](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub) . You can see the code after commenting cognito part in android sample [here](https://bitbucket.org/snippets/SunnyiB/jqGXB).

Need your help!

**Comment by SanyasiraoM** [comment]
@kvasukib Look into this please.

**Comment by SanyasiraoM** [comment]
@kvasukib look into this please

**Comment by bxpan** [comment]
Hi SanyasiraoM, 

Using Cognito to generate temporary certificates is the preferred way to authenticate with AWS IoT. It is not recommended to store permanent certificates on mobile device itself. 

If you do need to use your hard code certificate, the SDK currently supports taking a pkcs12 file from your app's bundle. You might need to look into creating a .p12 file from your certificate programmatically and put it into "Supporting Files" in you app bundle. See: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift item 8.  And examples of using  .p12 file : https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/ConnectionViewController.swift#L120 

Thanks.

**Comment by SanyasiraoM** [comment]
Hi @bxpan,
Thanks for reply

We will generate unique certificates and keys at our backend. And will be loaded dynamically when user login, so no issues with security.

So as I have certificates already. Do I still need to configure cognito pool id in app? as I'm able to remove cognito part in android sample mentioned above.

If cognito pool id is not needed. How can I remove cognito part as it's been giving for object of iotDataManger at https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/ConnectionViewController.swift#L252,L253,L254. Can I pass nil there?

**Comment by bxpan** [comment]
Hi SanyasiraoM,

Yes, you may pass in nil if you're not using cognito. Just make sure you have the right .p12 file with your certificate and private key under supporting files. 

Thanks.

**Comment by SanyasiraoM** [comment]
Thank you @bxpan. Everything is fine now
