### ISSUE TITLE
what is mean?

### ISSUE THREAD

**Issue by lwb22853628** [awslabs/aws-sdk-ios-samples#198]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `Info.plist` or set `defaultServiceConfiguration` before using this method.'

**Comment by kvasukib** [comment]
Hi @lwb22853628,

Thanks for reporting to us. Which sample app are you referring to?

Most of the sample apps in this repository have a README file which has the instructions to add configuration information to Info.plist. For example https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample#via-infoplist
