### ISSUE TITLE
Add asw3 to pod but can't find this type,can't be compiled

### ISSUE THREAD

**Issue by alexliubj** [awslabs/aws-sdk-ios-samples#20]
AWSS3TransferManagerUploadRequest
add this one to my bridge header already : `#import <AWSS3/AWSS3.h>`

**Comment by yosuke-matsuda** [comment]
Please share the detailed steps to reproduce the issue and the compiler error logs. Thanks.

**Comment by alexliubj** [comment]
1. edit podfile and awss3, 
2. pod update,
3. create bridge header
4 import  #import <AWSS3/AWSS3.h>
5.        compile, fine.
6. put this guy into one of swift file 
var uploadRequests = Array<AWSS3TransferManagerUploadRequest?>()
compile, failed due to can't find this AWSS3TransferManagerUploadRequest type 

/Users/alexliu/TorontoTB/toronto-tb-client/TorontoTB/TorontoTB/NewPostViewController.swift:27:32: error: use of undeclared type 'AWSS3TransferManagerUploadRequest'
    var uploadRequests = Array<AWSS3TransferManagerUploadRequest?>()
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alexliu/TorontoTB/toronto-tb-client/TorontoTB/TorontoTB/NewPostViewController.swift:27:31: note: while parsing this '<' as a type parameter bracket
    var uploadRequests = Array<AWSS3TransferManagerUploadRequest?>()

**Comment by alexliubj** [comment]
was following this step by step but still not working.

https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferManager-Sample/Swift

**Comment by alexliubj** [comment]
Added "${PODS_ROOT}/Headers/Public"
"${PODS_ROOT}/Headers/Public/AWSCore"
"${PODS_ROOT}/Headers/Public/AWSS3"

to Header search path also.

**Comment by alexliubj** [comment]
The example mislead me a lot.
I should be using bridge header if my project is swift project and using cocoas pod as well.
I should use this way instead.

edit podfile -> pod update/install -> in swift class import necessary directly in this way:

import ELCImagePickerController
import JTSImageViewController
import AWSS3
