### ISSUE TITLE
IoT-Sample/Swift

### ISSUE THREAD

**Issue by xiongwei0714** [awslabs/aws-sdk-ios-samples#201]
I have successfully run the IoT-Sample/Swift example on my iPhone.
When I publish the slider topic using iPhone, I can receive the message from the MQTT client on the web. When I publish the slider topic using MQTT client on the web, I can receive the message from iPhone.  
My question is : When I publish the slider topic using iPhone, why the iPhone itself cannot receive the message published by itself? From my opinion, the iPhone  subscribe the  slider topic and it will receive the message about the slider topic no matter who publish the message about slider topic.
Is my understanding about MQTT wrong? Or this example do something to avoid this?

**Comment by kvasukib** [comment]
Hello @xiongwei0714,

Did you run two instances of the application where one is publishing and the other is subscribing?

**Comment by xiongwei0714** [comment]
No. I mean why I cannot subscribe the message published by myself in one app instance.

**Comment by kredden** [comment]
The sample is not set up to do this. You can see it only subscribes to the topics in SubscribeViewController::viewWillAppear and then unsubscribes when the view goes away in SubscribeViewController::viewWillDisappear.  There is nothing in the SDK preventing you from subscribing to your own publishes.

Regards,
Kevin
