### ISSUE TITLE
AWS IOT reconnecting on getting internet

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#202]
How much time it will try to reconnect if user goes offline?

Will try to reconnect if user comes online?

**Comment by liuszeng** [comment]
Hi @SanyasiraoM ,

Thank you very much for your interests in AWS IoT iOS SDK.

The SDK provides automatic reconnect on network failures and progressive back off upon retries functionality. More details can be found in the following link:
https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/Internal/AWSIoTMQTTClient.m#L603
https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/Internal/AWSIoTMQTTClient.m#L370

Hope the above helps.

Thanks,
Liusu

**Comment by SanyasiraoM** [comment]
Okay, Thank you @liuszeng
