### ISSUE TITLE
Application tried to present modally an active controller

### ISSUE THREAD

**Issue by buwanekag** [awslabs/aws-sdk-ios-samples#203]
I'm running the user pool sample, swift version. The first build works fine allowing me to 
Sign up a new user -> Confirm verification -> Sign In as the newly registered user. 
However when I sign out and run the app again both on simulator and on an actual device the app crashes on launching the the "SignInViewController" with the error message 

"**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <UINavigationController: 0x15d014200>."**

I did extensively search for other similar cases online but have failed to find any, I was hoping I could get some guidance on this issue

**Comment by developer1996** [comment]
hey @buwanekag did you find a solution for this exception?

**Comment by sweeneyapps** [comment]
All you can make sure the app doesn't present navigationController again.

This is one of workaround below that I could think of.   So basically, the login setup for navigationController is a mess, we need an new design for it.    But you get the idea how it works and you can implement something to avoid reusing navigationController.

```
// MARK:- AWSCognitoIdentityInteractiveAuthenticationDelegate protocol delegate
extension AppDelegate: AWSCognitoIdentityInteractiveAuthenticationDelegate {
    
    func startPasswordAuthentication() -> AWSCognitoIdentityPasswordAuthentication {
        
        self.navigationController = nil
        self.signInViewController = nil
```

**Comment by angaaron** [comment]
Hey @sweeneyapps I placed `  self.navigationController = nil
        self.signInViewController = nil` in the code but it still didn't seem to work.

**Comment by sweeneyapps** [comment]
I can't produce the bug but this is the rest of the code.  Let me know if this is working.

```
    func startPasswordAuthentication() -> AWSCognitoIdentityPasswordAuthentication {
        print("startPasswordAuthentication")
        
        self.navigationController = nil
        self.signInViewController = nil
        
        if (self.navigationController == nil) {
            print("1")
            self.navigationController = self.storyboard?.instantiateViewController(withIdentifier: "signinController") as? UINavigationController
        }
        
        if (self.signInViewController == nil) {
            print("2")
            self.signInViewController = self.navigationController?.viewControllers[0] as? SignInViewController
        }
        
        DispatchQueue.main.async {
            print("3")
            
            print("\(self.navigationController!.isViewLoaded)")
    
               self.navigationController!.popToRootViewController(animated: false)
            
                if (!self.navigationController!.isViewLoaded
                    /* && self.navigationController!.view.window != nil */ ){
                    print("4")
                    self.window?.rootViewController?.present(self.navigationController!,
                                                             animated: true,
                                                             completion: nil)
                }
        }
        print("5")
        return self.signInViewController!
    }
```

**Comment by mixuechu** [comment]
@sweeneyapps duude you are really fast haha. I'm the facebook guy

**Comment by mixuechu** [comment]
@angaaron It works dude. Check it out

**Comment by qaisershehzad** [comment]
Facing same issue while trying to use CognitoYourUserPoolsSample

2018-08-26 13:15:35.489292+0500 CognitoYourUserPoolsSample[37587:708994] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <UINavigationController: 0x7fb687043600>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001053481e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000101c1a031 objc_exception_throw + 48
	2   UIKit                               0x000000010266da20 -[UIViewController _presentViewController:withAnimationController:completion:] + 5142
	3   UIKit                               0x00000001026702c6 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 99
	4   UIKit                               0x0000000103213a29 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 294
	5   UIKit                               0x000000010320f6d5 -[_UIViewControllerTransitionContext _runAlongsideCompletions] + 132
	6   UIKit                               0x000000010320f3c4 -[_UIViewControllerTransitionContext completeTransition:] + 118
	7   UIKit                               0x0000000102624a8e -[UITransitionView notifyDidCompleteTransition:] + 251
	8   UIKit                               0x0000000102624705 -[UITransitionView _didCompleteTransition:] + 1397
	9   UIKit                               0x0000000102626d3c -[UITransitionView _transitionDidStop:finished:] + 104
	10  UIKit                               0x000000010254aea9 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 343
	11  UIKit                               0x000000010254b4ec -[UIViewAnimationState animationDidStop:finished:] + 293
	12  UIKit                               0x000000010254b5a0 -[UIViewAnimationState animationDidStop:finished:] + 473
	13  QuartzCore                          0x00000001090605e5 _ZN2CA5Layer23run_animation_callbacksEPv + 323
	14  libdispatch.dylib                   0x0000000106b657ec _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000106b708cf _dispatch_main_queue_callback_4CF + 628
	16  CoreFoundation                      0x000000010530ac99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x00000001052ceea6 __CFRunLoopRun + 2342
	18  CoreFoundation                      0x00000001052ce30b CFRunLoopRunSpecific + 635
	19  GraphicsServices                    0x00000001081d9a73 GSEventRunModal + 62
	20  UIKit                               0x00000001024b6057 UIApplicationMain + 159
	21  CognitoYourUserPoolsSample          0x0000000100df40f7 main + 55
	22  libdyld.dylib                       0x0000000106be2955 start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kzahran** [comment]
There has to be a better way than this, but I just check if it has been already presented once. 

extension AppDelegate: AWSCognitoIdentityInteractiveAuthenticationDelegate {
    
    func startPasswordAuthentication() -> AWSCognitoIdentityPasswordAuthentication {

...

if (self.didItOnce == false) {
                    self.didItOnce = true
                    self.window?.rootViewController?.present(self.navigationController!,
                                                             animated: true,
                                                             completion: nil)
                }

**Comment by sweeneyapps** [comment]
yeah @kzahran 

the simplest way would be:

```
    func startPasswordAuthentication() -> AWSCognitoIdentityPasswordAuthentication {
        if self.navigationController == nil && self.signInViewController == nil {
            self.navigationController = self.storyboard?.instantiateViewController(withIdentifier: "signinController") as? UINavigationController
            self.signInViewController = self.navigationController?.viewControllers[0] as? SignInViewController
        }
        DispatchQueue.main.async {
            self.navigationController!.popToRootViewController(animated: true)
            if self.navigationController?.presentingViewController !== self.window?.rootViewController {
                self.window?.rootViewController?.present(self.navigationController!, animated: true, completion: nil)
            }
        }
        return self.signInViewController!
    }
```

**Comment by muellerfr** [comment]
Hello @qaisershehzad, 

Do you still need help? Looks like the original question was resolved.
