### ISSUE TITLE
Fetch files from S3 bucket and Download locally

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [awslabs/aws-sdk-ios-samples#204]
Hello Team,
I need a feature in my app which downloads files from S3 bucket and save it in document directory. Also i need to get the filename which gets downloaded from the S3 bucket.

I tried the S3TransferUtility-Sample to download file and save in document directory works, but **i need to get the filename which is getting downloaded**.

Then I used AWSS3ListObjectsRequest to get file names provided in your S3TransferManager-Sample.
But if i use it i don't find the files in the temp folder.  I also tried compiling the sample but the pods are missing also when i did pod install it gave me below error
[!] Unable to satisfy the following requirements:
- `AWSS3 (~> 2.5.5)` required by `Podfile`
None of your spec sources contain a spec satisfying the dependency: `AWSS3 (~> 2.5.5)`.

Could you please help me with what could have gone wrong with my implementation.

Waiting for your reply,
Thanks

**Comment by kvasukib** [comment]
Hi @AbhishekChourasia16690,

Thanks for reporting to us. 

http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html -> More Transfer Examples -> Downloading to a file section lays out an example of downloading S3 object to a file you specify.

**Comment by AbhishekChourasia16690** [comment]
Thanks for the reply. But how do I get the file name of the file downloaded from AWSS3TransferUtility.

Also I tried the S3TransferManager-Sample. I'm able to get file name but the file gets download in temp folder with filename+cache name( I suppose), which will make the file to retrieve by name difficult.

Could you please let me know how can we save the file in document directory with proper file name.

I used the below code as mentioned In your sample

- (void)listObjects:(id)sender {
    AWSS3 *s3 = [AWSS3 defaultS3];
    AWSS3ListObjectsRequest *listObjectsRequest = [AWSS3ListObjectsRequest new];
    listObjectsRequest.bucket = @"MyBucket";
    [[s3 listObjects:listObjectsRequest] continueWithBlock:^id(AWSTask *task) {
        if (task.error) {
            NSLog(@"listObjects failed: [%@]", task.error);
        } else {
            AWSS3ListObjectsOutput *listObjectsOutput = task.result;
            for (AWSS3Object *s3Object in listObjectsOutput.contents) {
                NSString *downloadingFilePath = [NSTemporaryDirectory() stringByAppendingPathComponent:s3Object.key];
                NSURL *downloadingFileURL = [NSURL fileURLWithPath:downloadingFilePath];
                
                if ([[NSFileManager defaultManager] fileExistsAtPath:downloadingFilePath]) {
                    [self.collection addObject:downloadingFileURL];
                } else {
                    AWSS3TransferManagerDownloadRequest *downloadRequest = [AWSS3TransferManagerDownloadRequest new];
                    downloadRequest.bucket = @"MyBucket";
                    downloadRequest.key = s3Object.key;
                    downloadRequest.downloadingFileURL = downloadingFileURL;
                    [self.collection addObject:downloadRequest];
                }
            }
            
            dispatch_async(dispatch_get_main_queue(), ^{
//                [self.collectionView reloadData];
            });
        }
        return nil;
    }];
}

**Comment by AbhishekChourasia16690** [comment]
Hello All,
Any updates if i could save the file in document directory?

Waiting for your reply.
Thanks.

**Comment by rohandubal** [comment]
Hello @AbhishekChourasia16690 
You can use the download to file by specifying the file URL in the Document directory. You should use S3TransferUtility feature for that. Please refer to following documentation on details:
http://docs.aws.amazon.com/mobile/sdkforios/developerguide/s3transferutility.html#downloading-to-a-file

Thanks
Rohan
