### ISSUE TITLE
Objective C Temperature Control and IoT Samples?

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#205]
Hi,

Are you guys planning to give objective c samples?

**Comment by liuszeng** [comment]
Hi @SanyasiraoM ,

Unfortunately, we only provide Swift samples along with the SDK in the latest version. We are actively collecting customer feedback/requests on SDK support and prioritize future tasks based on that input. Please stay tuned.

Thanks,
Liusu

**Comment by SanyasiraoM** [comment]
Okay, Thank you!
