### ISSUE TITLE
How to include cacert[Certificate Authority] in pkcs12 file while authenticating?

### ISSUE THREAD

**Issue by SanyasiraoM** [awslabs/aws-sdk-ios-samples#206]
Hi,

We have three certificates names private.pem.key,  certificate.pem.crt, cacert.pem

I tried generating pkcs12 file by using below command

openssl pkcs12 -export -in cert.pem -inkey key.pem -certfile cacert.pem -out awsiot.p12

But unable to include Certificate Authority[cacert.epm] in the key chain as https://github.com/aws/aws-sdk-ios/blob/master/AWSIoT/Internal/AWSIoTKeychain.m is considering only certificate and private key. So how to include certificate authority?

**Comment by muellerfr** [comment]
Hello @SanyasiraoM, sorry for the delay. Do you still require help with the issue?

**Comment by SanyasiraoM** [comment]
@muellerfr Yes.

**Comment by desokroshan** [comment]
Hi @SanyasiraoM,
You don't need to pass the CA Certificate to authenticate to AWS IoT using the sdk if you are using AWS IoT generated certificates. If you are using a device certificate signed and issued by a different Certificate Authority, you must register the CA certificate with AWS IoT. After the CA certificate is registered, any device certificate, signed by the CA can be registered with AWS IoT and be used for authentication. You can register your CA certificate using the steps in [this](https://docs.aws.amazon.com/iot/latest/developerguide/device-certs-your-own.html#register-CA-cert) link. If you were not able to connect and are running into an exception after registering your CA cert, can you please share the stacktrace?
Thanks, Roshan

**Comment by SanyasiraoM** [comment]
@desokroshan We are hosting our server with verneMQ, with custom certificates. In our authentication process, we need to send ca certificate from client, So we want to use aws-sdk for that purpose.

**Comment by SanyasiraoM** [comment]
@desokroshan Will do it and get back to you. Thank you!
