### ISSUE TITLE
S3TransferManagerSample-The request timed out

### ISSUE THREAD

**Issue by yangyu2010** [awslabs/aws-sdk-ios-samples#207]
###  when i use UploadViewController to upload picture, The following questions will arise.

nw_endpoint_flow_prepare_output_frames [2.1 54.231.177.32:443 ready socket-flow (satisfied)] Failed to use 1 frames, marking as failed
nw_endpoint_handler_add_write_request [2.1 54.231.177.32:443 failed socket-flow (satisfied)] cannot accept write requests
tcp_connection_write_eof_block_invoke Write close callback received error: [22] Invalid argument
nw_endpoint_flow_prepare_output_frames [3.1 52.218.192.8:443 ready socket-flow (satisfied)] Failed to use 1 frames, marking as failed
 nw_endpoint_handler_add_write_request [3.1 52.218.192.8:443 failed socket-flow (satisfied)] cannot accept write requests

 Upload failed: [Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x60000005e3f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://s3-us-west-2.//28210A0C-FBE5-4872-A483-F7442DA91FEB-16215-00001D3E02FCECA2.png, NSErrorFailingURLKey=https://28210A0C-FBE5-4872-A483-F7442DA91FEB-16215-00001D3E02FCECA2.png, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}]

What happened to this problem?

**Comment by rohandubal** [comment]
Hello, can you provide us with some code snippet so that we can assess the problem? It seems the URL and the key is incorrect.

Thanks,
Rohan

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If there's still an issue, please open it in the aws/aws-sdk-ios repo.
