### ISSUE TITLE
AWS Cognito

### ISSUE THREAD

**Issue by vunhatminh241191** [awslabs/aws-sdk-ios-samples#208]
Hi everyone,

I am new with AWS SDK, so can some one explain how to integrate AWS Cognito into my iOS app. I think I have to follow the work flow: User Pool Example --> Cognito Auth --> Cognito Sync, is it correct?

Moreover, when I tried to use Cognito Auth, can someone tell me how to set up SignIn Redirect URI? I am not sure how to do that. 

Thanks for you guys helping.

**Comment by kredden** [comment]
Have you tried using AWS Mobile Hub (https://aws.amazon.com/mobile/)?  It allows you to set up Cognito and then generates a sample app showing you how to use it.  It also has instructions on how to integrate it into your app.

**Comment by kvasukib** [comment]
Hi @vunhatminh241191,

Can you try the CognitoAuth demo sample app? (https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample). These instructions (https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoAuth-Sample/README.md) will help you set the sample app.

Thanks
AWS Mobile

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If there's still an issue, please open it in the aws/aws-sdk-ios repo.
