### ISSUE TITLE
com.amazonaws.AWSCognitoIdentityErrorDomain error 0

### ISSUE THREAD

**Issue by jonnokim17** [awslabs/aws-sdk-ios-samples#209]
I followed all the steps in the README for `S3TransferUtilitySampleSwift` but I am repeatedly getting the following error: `Error: The operation couldn’t be completed. (com.amazonaws.AWSCognitoIdentityErrorDomain error 0.)` for both `uploadData` function and `downloadData` functions.

**Comment by rohandubal** [comment]
Hello @jonnokim17 

Could you please provide the full stack trace? Have you set up the IAM permissions correctly and allowed unauthenticated access?

Thanks,
Rohan

**Comment by jonnokim17** [comment]
Below is the callstack I get when attempting todownload a file from my server's aws bucket. I am not using the upload image functionality within the app. What I want to achieve is to be able to download a file from my bucket securely, so that users of my app cannot have access the files. I understand that AWS encrypts/decrypts the files for free, but using a `GET` request in my app to retrieve the file would NOT prevent someone from downloading the files.. I was hoping using `AWSS3TransferUtility` would resolve the issue.

`["0   S3TransferUtilitySampleSwift        0x0000000103fbb82b _TFFC28S3TransferUtilitySampleSwift22DownloadViewController5startFCSo8UIButtonT_U1_FGCSo7AWSTaskCSo32AWSS3TransferUtilityDownloadTask_GSqPs9AnyObject__ + 1035", "1   S3TransferUtilitySampleSwift        0x0000000103fbbb9e _TTRXFo_oGCSo7AWSTaskCSo32AWSS3TransferUtilityDownloadTask__oGSqPs9AnyObject___XFo_oGS_S0___iGSqP___ + 30", "2   S3TransferUtilitySampleSwift        0x0000000103fbbd41 _TPA__TTRXFo_oGCSo7AWSTaskCSo32AWSS3TransferUtilityDownloadTask__oGSqPs9AnyObject___XFo_oGS_S0___iGSqP___ + 81", "3   S3TransferUtilitySampleSwift        0x0000000103fbbd90 _TTRXFo_oGCSo7AWSTaskCSo32AWSS3TransferUtilityDownloadTask__iGSqP___XFdCb_dGS_S0___aGSqPs9AnyObject___ + 64", "4   AWSCore                             0x0000000104120b28 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 104", "5   AWSCore                             0x00000001040c350e __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 190", "6   AWSCore                             0x00000001040c3ebe -[AWSExecutor execute:] + 94", "7   AWSCore                             0x00000001041210b2 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.126 + 50", "8   AWSCore                             0x000000010412044d -[AWSTask runContinuations] + 765", "9   AWSCore                             0x000000010411fe1a -[AWSTask trySetError:] + 282", "10  AWSCore                             0x00000001041222e9 -[AWSTaskCompletionSource setError:] + 89", "11  AWSCore                             0x0000000104120dff __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 271", "12  AWSCore                             0x0000000104120c31 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 369", "13  AWSCore                             0x00000001040c350e __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 190", "14  AWSCore                             0x00000001040c3ebe -[AWSExecutor execute:] + 94", "15  AWSCore                             0x00000001041210b2 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.126 + 50", "16  AWSCore                             0x000000010412044d -[AWSTask runContinuations] + 765", "17  AWSCore                             0x000000010411fe1a -[AWSTask trySetError:] + 282", "18  AWSCore                             0x00000001041222e9 -[AWSTaskCompletionSource setError:] + 89", "19  AWSCore                             0x0000000104120dff __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 271", "20  AWSCore                             0x0000000104120c31 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 369", "21  AWSCore                             0x00000001040c350e __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 190", "22  AWSCore                             0x00000001040c3ebe -[AWSExecutor execute:] + 94", "23  AWSCore                             0x00000001041210b2 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.126 + 50", "24  AWSCore                             0x000000010412044d -[AWSTask runContinuations] + 765", "25  AWSCore                             0x000000010411fe1a -[AWSTask trySetError:] + 282", "26  AWSCore                             0x00000001041222e9 -[AWSTaskCompletionSource setError:] + 89", "27  AWSCore                             0x0000000104120dff __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 271", "28  AWSCore                             0x0000000104120b28 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 104", "29  AWSCore                             0x00000001040c350e __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 190", "30  AWSCore                             0x00000001040c3ebe -[AWSExecutor execute:] + 94", "31  AWSCore                             0x00000001041210b2 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.126 + 50", "32  AWSCore                             0x000000010412044d -[AWSTask runContinuations] + 765", "33  AWSCore                             0x000000010411fe1a -[AWSTask trySetError:] + 282", "34  AWSCore                             0x00000001041222e9 -[AWSTaskCompletionSource setError:] + 89", "35  AWSCore                             0x0000000104120dff __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 271", "36  AWSCore                             0x0000000104120c31 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 369", "37  AWSCore                             0x00000001040c350e __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 190", "38  AWSCore                             0x00000001040c3ebe -[AWSExecutor execute:] + 94", "39  AWSCore                             0x00000001041210b2 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.126 + 50", "40  AWSCore                             0x000000010412044d -[AWSTask runContinuations] + 765", "41  AWSCore                             0x000000010411fe1a -[AWSTask trySetError:] + 282", "42  AWSCore                             0x00000001041222e9 -[AWSTaskCompletionSource setError:] + 89", "43  AWSCore                             0x0000000104120dff __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 271", "44  AWSCore                             0x0000000104120c31 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 369", "45  AWSCore                             0x00000001040c350e __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 190", "46  AWSCore                             0x00000001040c3ebe -[AWSExecutor execute:] + 94", "47  AWSCore                             0x00000001041210b2 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.126 + 50", "48  AWSCore                             0x000000010412044d -[AWSTask runContinuations] + 765", "49  AWSCore                             0x000000010411fe1a -[AWSTask trySetError:] + 282", "50  AWSCore                             0x00000001041222e9 -[AWSTaskCompletionSource setError:] + 89", "51  AWSCore                             0x0000000104120dff __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 271", "52  AWSCore                             0x0000000104120c31 __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 369", "53  Foundation                          0x00000001044f2237 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7", "54  Foundation                          0x00000001044f1f3b -[NSBlockOperation main] + 101", "55  Foundation                          0x00000001044f06f7 -[__NSOperationInternal _start:] + 627", "56  Foundation                          0x00000001044ec47c __NSOQSchedule_f + 198", "57  libdispatch.dylib                   0x000000010807e05c _dispatch_client_callout + 8", "58  libdispatch.dylib                   0x000000010805c94f _dispatch_queue_serial_drain + 221", "59  libdispatch.dylib                   0x000000010805d669 _dispatch_queue_invoke + 1084", "60  libdispatch.dylib                   0x000000010805fec4 _dispatch_root_queue_drain + 634", "61  libdispatch.dylib                   0x000000010805fbef _dispatch_worker_thread3 + 123", "62  libsystem_pthread.dylib             0x00000001084e35a2 _pthread_wqthread + 1299", "63  libsystem_pthread.dylib             0x00000001084e307d start_wqthread + 13"]`

I'm not sure what IAM Permissions is.. but I did set public access `Read object` to YES. Thanks in advance!

**Comment by rohandubal** [comment]
You need to give permissions for the Cognito Unauth role for the cognito pool id which you are using so that you can upload or download. Have you set the correct configuration in info.plist? 

Thanks,
Rohan

**Comment by jonnokim17** [comment]
Thanks for the reply Rohan.

Here's a screenshot on my info.plist. Am I missing something?

<img width="495" alt="screen shot 2017-08-23 at 12 35 03 pm" src="https://user-images.githubusercontent.com/7801383/29600369-988cd22e-87ff-11e7-8b0d-6ef757f56bdc.png">

**Comment by jonnokim17** [comment]
Here's a setup for Identity Pool via AWS console:

<img width="408" alt="screen shot 2017-08-23 at 12 37 17 pm" src="https://user-images.githubusercontent.com/7801383/29600411-e4ccc2d4-87ff-11e7-8936-52442c7122f6.png">

**Comment by jonnokim17** [comment]
hey @rohandubal - do you have any updates on this? Thank you.

**Comment by kvasukib** [comment]
Hi @jonnokim17,

Have you updated the bucket and keys in Constants.swift?

https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferUtility-Sample/Swift/S3BackgroundTransferSampleSwift/Constants.swift

This section covers the steps for setting up access.
http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-auth-aws-identity-for-ios.html

**Comment by daviskoh** [comment]
seeing this as well

**Comment by joshwolff1** [comment]
There are two different things here: identityPoolId and poolId. The poolId you have currently is actually your identityPoolId. Your poolId is shorter, something like this: us-east-1_*******. About that length. Find the poolId by going to the General Settings of your Users Pool in Cognito. It's at the top. Identity pool ID is given in the Federated Identities part of Cognito.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
