### ISSUE TITLE
Build error with Swift version of samples

### ISSUE THREAD

**Issue by tohsaki** [awslabs/aws-sdk-ios-samples#21]
I was able to compile and run Objective-C version of S3TransferManager-Sample.
 
However, I got compilation errors with the Swift version. 
Here are the steps I took:
1) Download and unzip aws-sdk-ios-samples-master.zip
2) Start terminal and go to .../S3TransferManager-Sample/Swift
3) type
pod install
4) Open the Swift project by double-clicking on S3TransferManagerSampleSwift.xcworkspace
5) Verify required AWS SDK components are installed from project navigator:
![image](https://cloud.githubusercontent.com/assets/10605604/8962041/66b19b3a-35cd-11e5-94c7-5dc6d99284dc.png)

6) Select Build Settings/TARGETS/S3TransferManagerSampleSwift
7) Verify Swift Compiler - Code Generation/Objective-C bridging Header section shows the correct path:
S3TransferManagerSampleSwift/ObjectiveC-Bridging-Header.h

![image](https://cloud.githubusercontent.com/assets/10605604/8961544/b4f10f9a-35ca-11e5-809d-27538862b4d0.png)

8) Build the project
Then I got build errors. Please see the attached screenshot shown below.
![image](https://cloud.githubusercontent.com/assets/10605604/8961739/d38367fe-35cb-11e5-9388-4b2c18ec1fe2.png)

I checked the bridging header file and verified AWSS3 is imported:
![image](https://cloud.githubusercontent.com/assets/10605604/8961814/4800871a-35cc-11e5-9598-620ec5cb8db2.png)

I appreciate you help in advance.

Tsuni Ohsaki

**Comment by yosuke-matsuda** [comment]
We couldn't reproduce the issue. Have you clean the Xcode cache? If it doesn't help, updating CocoaPods and Xcode to the latest (non-beta) versions may help.

**Comment by tohsaki** [comment]
Hi Matsuda-san,

Thanks for looking into this.

I cleaned cache by deleting all content of DerivedData but I still have the same issue :-(
I installed cocoapod quite recently. Here's the specs:
xCode: 6.4 
COCOAPODS: 0.38.1

Thanks!

Tsuni

**Comment by yosuke-matsuda** [comment]
0.38.2 is the latest version of CocoaPods, but probably it won't make a difference. Have you modified the source files in any way? It may be worthwhile to redownload the sample and set it up from the scratch.

**Comment by tohsaki** [comment]
Hi Matsuda-san,

I followed your instruction ("...redownload the sample and set it up from the scratch.") and used 0.38.2.
Now I compiled the project without errors!
You have been extremely helpful!!!

Tsuni Ohsaki
