### ISSUE TITLE
S3TransferManagerSampleSwift - too many errors

### ISSUE THREAD

**Issue by jtressle** [awslabs/aws-sdk-ios-samples#212]
Looks like projects still haven't been updated to Swift 3:

> Xcode 8 will not be able to build the target “S3TransferManagerSampleSwift”, and certain editing features will not function properly until the Swift source code in this target has been converted.
> 
> This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

Unfortunately, I get 1000 errors when the conversion is done.  

Will the samples get updated anytime soon?  Or should I look elsewhere for working samples / hosting?

**Comment by kvasukib** [comment]
Hi @jtressle, 

Thanks for reporting to us. Sorry for the inconvenience. We are working on a fix.

**Comment by gunteefe** [comment]
Hello has this fix been done?

**Comment by muellerfr** [comment]
Closing this issue, because we are retiring the S3TransferManager soon. Please use S3TransferUtility instead.
