### ISSUE TITLE
SNS-MobileAnalytics-Sample needs update

### ISSUE THREAD

**Issue by agao** [awslabs/aws-sdk-ios-samples#213]
`let deviceTokenString = "\(deviceToken)"
            .stringByTrimmingCharactersInSet(NSCharacterSet(charactersInString:"<>"))
            .stringByReplacingOccurrencesOfString(" ", withString: "")`

needs to be 
`let deviceTokenString = String(format: "%@", deviceToken as CVarArg)
            .trimmingCharacters(in: CharacterSet(charactersIn:"<>"))
            .replacingOccurrences(of: " ", with: "")`

New version of swift use Data instead of NSData therefore this changed is needed.

**Comment by kvasukib** [comment]
Hi @agao,

Thanks for reporting to us. We will take a look at it and fix in the future release.

**Comment by agao** [comment]
No problem. Thanks.

Best,
Alan Gao

**Comment by kredden** [comment]
Mobile Analytics was deprecated as a service and replace by equivalent functionality in AWS Pinpoint.
