### ISSUE TITLE
Bug ipad Mini 2 - 10.3.3  sample app of Cognito auth with Swift

### ISSUE THREAD

**Issue by gitton** [awslabs/aws-sdk-ios-samples#214]
Trying out the sample app of Cognito auth with Swift as language and find following error when I tap on Sign In 
2017-09-18 16:56:03.789252+0530 CognitoAuthSample[467:55748] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x101020240>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
*** First throw call stack:
(0x18ce0efe0 0x18b870538 0x19397ebe8 0x19328c0d4 0x193289e04 0x1931c6594 0x1931b8630 0x192f2c28c 0x18cdbc9a8 0x18cdba630 0x18cdbaa7c 0x18cceada4 0x18e755074 0x192f9ec9c 0x10001c254 0x18bcf959c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by gitton** [comment]
@IBAction func signInTapped(_ sender: Any) {
        self.auth.getSession  { (session:AWSCognitoAuthUserSession?, error:Error?) in
            if(error != nil) {
                self.session = nil
                self.alertWithTitle("Error", message: (error! as NSError).userInfo["error"] as? String)
            }else {
                self.session = session
            }
            self.refresh()
        }
    }

App crashes when executing above function from ipad

**Comment by behrooziAWS** [comment]
@gitton Thanks for reporting this.  I was able to repro locally, it is an issue with the Cognito Auth SDK and popover's requiring a sourceView and sourceRect on ipads.  I've made some progress on fixing it, but it doesn't display fullscreen like on iphones.  I'll continue working on it as time permits and will let you know if I have a patch.

**Comment by gitton** [comment]
Thank you @behrooziAWS for looking into the issue. Is there any fixes for the same

**Comment by behrooziAWS** [comment]
@gitton I believe you also reached out through AWS support,  I've provided support with a preliminary patch with a few issues that may get you unblocked.  If they haven't already they likely will reach out to you soon.

**Comment by gitton** [comment]
Thank you for the response @behrooziAWS . Waiting for the patch

**Comment by gitton** [comment]
Thank you @behrooziAWS got the patch and it works!
