### ISSUE TITLE
COMPILE ERROR : for the AWS DDOSLogger file 

### ISSUE THREAD

**Issue by vickydhas** [awslabs/aws-sdk-ios-samples#215]
Hello, 

Development Team

Could you please check the following error as it's received then I compile the app using XCode 9 official release from Appstore.

<img width="1440" alt="screen shot 2017-09-26 at 11 05 00 pm" src="https://user-images.githubusercontent.com/834663/30867804-81a3d104-a30f-11e7-9812-3e8f30d0483a.png">

I have updated the AWS Pods as well still the issue exists.

Using AFNetworking (3.1.0)
Installing AMPopTip 3.0.0 (was 2.1.7)
Installing AWSAutoScaling 2.6.1 (was 2.5.10)
Installing AWSCloudWatch 2.6.1 (was 2.5.10)
Installing AWSCognito 2.6.1 (was 2.5.10)
Installing AWSCognitoIdentityProvider 2.6.1 (was 2.5.10)
Installing AWSCore 2.6.1 (was 2.5.10)
Installing AWSDynamoDB 2.6.1 (was 2.5.10)
Installing AWSEC2 2.6.1 (was 2.5.10)
Installing AWSElasticLoadBalancing 2.6.1 (was 2.5.10)
Installing AWSIoT 2.6.1 (was 2.5.10)
Installing AWSKinesis 2.6.1 (was 2.5.10)
Installing AWSLambda 2.6.1 (was 2.5.10)
Installing AWSMachineLearning 2.6.1 (was 2.5.10)
Installing AWSMobileAnalytics 2.6.1 (was 2.5.10)
Installing AWSS3 2.6.1 (was 2.5.10)
Installing AWSSES 2.6.1 (was 2.5.10)
Installing AWSSNS 2.6.1 (was 2.5.10)
Installing AWSSQS 2.6.1 (was 2.5.10)
Installing AWSSimpleDB 2.6.1 (was 2.5.10)

I am using these frameworks as well as part of my XMPP Project requirement modules.
Using CocoaAsyncSocket (7.6.1)
Using CocoaLumberjack (3.2.1)
Pre-downloading: `XMPPFramework` from `https://github.com/robbiehanson/XMPPFramework.git`, branch `master`

**Comment by meacreatio** [comment]
+1 Same issue for me.

**Comment by kredden** [comment]
Hi,

This change was made due to XCode 9 beta flagging those same lines with the same error as you are seeing above.  I am unable to reproduce this with 2.6.1.  Have you tried doing a clean and rebuilding?

Thanks,
Kevin

**Comment by rohandubal** [comment]
What is the Xcode 9 build version which you are using? I tried reproducing with Xcode 9 (Version 9.0 (9A235)) and I am not able to reproduce. I also added dependencies which you have.

**Comment by vickydhas** [comment]
I deleted the Pods and did '#pod install and the issue was fixed. Closing this bug reported.
