### ISSUE TITLE
iOS Integration Issue

### ISSUE THREAD

**Issue by girishnair12345** [awslabs/aws-sdk-ios-samples#217]
I got this error while running this on swift

Domain=com.amazonaws.AWSLexErrorDomain Code=0 "null" UserInfo={NSLocalizedFailureReason=AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/, NSLocalizedDescription=null}

I went to modify the permission in AWSServiceRoleForLexBots policy but can't do it

This is the policy summary
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "polly:SynthesizeSpeech"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}

How can I modify it for this to work ??

**Comment by kvasukib** [comment]
Hi @girishnair12345,

What's the Sample app you are trying to run? Lex or Polly?

**Comment by girishnair12345** [comment]
Lex

**Comment by rohandubal** [comment]
You need to have a policy on your cognito role to allow post content operations on Lex. The policy would look something like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "lex:PostContent",
                "lex:PostText"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:lex:us-east-1:123456789011:bot:OrderFlowers:*",
                "arn:aws:lex:us-east-1:123456789011:bot:BookTrip:*"
            ]
        }
    ]
}
```

**Comment by girishnair12345** [comment]
Can you explain how to do that, and wouldn't it be great if you close the issue once the person raising it says its resolved ??

**Comment by girishnair12345** [comment]
I can't find this setting, How exactly can I enable this ??

Why does lex has to be clouded by so many permissions, it's so easy to use api.ai by google.

**Comment by sweeneyapps** [comment]
@girishnair12345  I'll help you out.  :)

I'm not sure how you setup your app.   But if you are using the sample.   Then I can assume that you are using Cognito Federated Identities.      You go to manage your Federated Identities, by Editing Identity Pool.    You will see Unauthenticated Role,  you can select one or create a new role.    Once you have a role for Unauthenticated Role.   You will have to go to IAM page.    On the IAM page, you'll select the role, you are using for Unauthenticated Role.   On the Summary page for the Role, you will:

Click on Add inline policy, and fill in this statement below:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "lex:PostContent",
                "lex:PostText"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "polly:SynthesizeSpeech"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by girishnair12345** [comment]
Thanks for your reply but I am using api.ai now
