### ISSUE TITLE
result.codeDeliveryDetails?.destination is Nil on SignUpViewController

### ISSUE THREAD

**Issue by begulsen** [awslabs/aws-sdk-ios-samples#222]
I have successfully register the user to my pooly with using CognitoYourUserPoolsSample example on simulator. Register is completed but didnt take any sms from amazon for verification of the phone number (phone_number_verified -> false ). 
ConfirmSignUpViewController didnt open because result.codeDeliveryDetails?.destination is Nil (line 96 on the SignUpViewController). I also try to give value to destination manually but didnt work once again.

Can you guys help me ? Is that a issue of AWSCognitoIdentityUser.m ?

**Comment by muellerfr** [comment]
Hello @begulsen,

sorry for the delay. Do you still require help with the issue?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
