### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by caltv** [awslabs/aws-sdk-ios-samples#223]
Can we get an example in Objective-C?

I've got this far but don't know how to create the AWSPollySynthesizeSpeechURLBuilderRequest

`AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]
                                                         initWithRegionType:AWSRegionUSWest2
                                                         identityPoolId:@"us-west-2:xxx"];`

`AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSWest2 credentialsProvider:credentialsProvider];`
   
  ` [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;`
   
  
 `  AWSPollySynthesizeSpeechURLBuilder *PollyURLBuilder = [AWSPollySynthesizeSpeechURLBuilder defaultPollySynthesizeSpeechURLBuilder];`

**Comment by kvasukib** [comment]
You can refer to one of the tests: https://github.com/aws/aws-sdk-ios/blob/master/AWSPollyTests/AWSPollyTests.m#L168

// Create the request:

AWSPollySynthesizeSpeechURLBuilderRequest *request = [[AWSPollySynthesizeSpeechURLBuilderRequest alloc]init];
    [request setText:@"Sample Text."];
    [request setOutputFormat:AWSPollyOutputFormatMp3];
    [request setVoiceId:AWSPollyVoiceIdSalli];
    [request setExpires:[NSDate dateWithTimeIntervalSinceNow:10*60]];
    
// Create the builder:

    AWSPollySynthesizeSpeechURLBuilder *builder = [AWSPollySynthesizeSpeechURLBuilder defaultPollySynthesizeSpeechURLBuilder];
    __block NSString *filePath;
    
// Connect request with the builder:

    [[[[builder getPreSignedURL:request] continueWithBlock:^id _Nullable(AWSTask<NSURL *> * _Nonnull task) {
        NSLog(@"Presigned URL: \n%@\n", task.result);
        return task;
    }] continueWithBlock:^id _Nullable(AWSTask * _Nonnull task) {
       //....
    }] waitUntilFinished];

**Comment by johndpope** [comment]
close this
