### ISSUE TITLE
AWSCognito.framework: unknown error -1=ffffffffffffffff

### ISSUE THREAD

**Issue by eironeia** [awslabs/aws-sdk-ios-samples#225]
Hello I am receiving this error from some days ago without change anything of the code or scripts. 

Code Signing /Users/ ____ /Library/Developer/Xcode/DerivedData/ ____ /Build/Products/Release-iphoneos/ ___ .app/Frameworks/AWSCognito.framework with Identity iPhone Developer: ____

/usr/bin/codesign --force --sign ___  --preserve-metadata=identifier,entitlements '/Users/_/Library/Developer/Xcode/DerivedData/ ____ /Build/Products/Debug-iphoneos/ ___ .app/Frameworks/AWSCognito.framework'

/Users/ ____ /Library/Developer/Xcode/DerivedData/ ____ /Build/Products/Debug-iphoneos/ ____ /Frameworks/AWSCognito.framework: unknown error -1=ffffffffffffffff

Command /bin/sh failed with exit code 1

I have tried to update the pod, clean the project, reinstall xcode, but nothing solves that. I am not running specifically any script of AWS so I don't understand why the project brokes when compiles.

Thank you.

**Comment by kvasukib** [comment]
What version of XCode, iOS, and AWSCognito are you using? Do you have AWSCore.framework in your app?

**Comment by dominic-healid** [comment]
Having this error too, it was working fine a few minutes ago and then now I'm getting this error. Have you fixed this @eironeia ?

**Comment by behrooziAWS** [comment]
Not enough info to troubleshoot, since it is related to code signing, please check your provisioning profile.  If you have more info or details that points at Cognito, please reopen with the iOS SDK version, xcode version and AWS SDK version.
