### ISSUE TITLE
CognitoAuth-Sample Crashes on iPad

### ISSUE THREAD

**Issue by coreyjv** [awslabs/aws-sdk-ios-samples#226]
AWS Mobile SDK Version: 2.6.5
Source code: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample
XCode version: Version 9.1 (9B55)
Simulator: iPad Pro (12.9 inch) - 2nd Generation iOS 11.1

When launching the sample on an iPad it crashes immediately:

```
2017-11-17 08:13:30.333193-0500 CognitoAuthSample[87483:86260671] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x7fed11524270>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010415b1ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000100bc1f41 objc_exception_throw + 48
	2   UIKit                               0x00000001021477f2 -[UIPopoverPresentationController presentationTransitionWillBegin] + 3290
	3   UIKit                               0x00000001015d819f __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 2458
	4   UIKit                               0x00000001015d591f __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 436
	5   UIKit                               0x000000010146a625 _runAfterCACommitDeferredBlocks + 318
	6   UIKit                               0x0000000101458bc5 _cleanUpAfterCAFlushAndRunDeferredBlocks + 280
	7   UIKit                               0x0000000101488c1c _afterCACommitHandler + 137
	8   CoreFoundation                      0x00000001040fdd37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	9   CoreFoundation                      0x00000001040fdc8e __CFRunLoopDoObservers + 430
	10  CoreFoundation                      0x00000001040e2254 __CFRunLoopRun + 1572
	11  CoreFoundation                      0x00000001040e19b9 CFRunLoopRunSpecific + 409
	12  GraphicsServices                    0x000000010a7309c6 GSEventRunModal + 62
	13  UIKit                               0x000000010145e5e8 UIApplicationMain + 159
	14  CognitoAuthSample                   0x0000000100272117 main + 55
	15  libdyld.dylib                       0x0000000105b68d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by behrooziAWS** [comment]
Hi, thanks for reporting this issue.  Modal views are handled differently on iPads.  I've attached some non-final patched code which is functional, but with the exception that if the user taps outside of the modal, it doesn't call the completion block.  If you remove the .txt extension and overlay on the files of the same name, it won't crash on iPads.

[AWSCognitoAuth.m.txt](https://github.com/awslabs/aws-sdk-ios-samples/files/1500031/AWSCognitoAuth.m.txt)
[AWSCognitoAuth.h.txt](https://github.com/awslabs/aws-sdk-ios-samples/files/1500032/AWSCognitoAuth.h.txt)

**Comment by coreyjv** [comment]
Thank you. I'll give this a test when I get a moment. Is it correct to assume that the changes you introduced will make it to the Cognito library?

**Comment by desokroshan** [comment]
@coreyjv Can you please confirm if the above files worked for you on iPads as expected?

**Comment by coreyjv** [comment]
Hi @desokroshan --

We recently tested on an iPad again and with the latest Cocoapod of the mobile SDK it does not crash any longer. I didn't test with these files specifically.

**Comment by muellerfr** [comment]
@coreyjv, thanks for the update. I will close the issue.
