### ISSUE TITLE
How to mapping attributes and create new user to userpool automatically when I login with external provider like Fb,Google...?

### ISSUE THREAD

**Issue by mvpscottjon** [awslabs/aws-sdk-ios-samples#228]
I study a lot of documents and try samples(aws sync, cognitoMyUserPool...)

But I can't succeed to (1.)map attributes to user pool and (2.)create new user automatically (it mean when I login with fb , it will create new user at user pool console  just like firebase, it means I don't need take the user profile to signup with programming)

question 1 and 2 , is that possible?

in my case,I use federated identity to get Fb login,but I don't know how to link userPool

look at my code below:

MyViewController:
```

import UIKit
import AWSCore
import AWSCognito
import AWSCognitoIdentityProvider


import FacebookLogin
import FacebookCore

import GoogleSignIn
class ViewController: UIViewController  {
    
  
    override func viewDidLoad() {
        super.viewDidLoad()
        //FB custom login
        // Add a custom login button to your app
        let myLoginButton = UIButton(type: .custom)
        myLoginButton.backgroundColor = UIColor.darkGray
        myLoginButton.frame = CGRect(x: 0, y: 0, width: 180, height: 40)
        myLoginButton.center = view.center
        myLoginButton.setTitle("MY login Btn", for: .normal)
        
        // Handle clicks on the button
        myLoginButton.addTarget(self, action: #selector(loginButtonClicked), for: .touchUpInside)

        // Add the button to the view
        view.addSubview(myLoginButton)
 
    }
    @objc func loginButtonClicked() {
        let loginManager = LoginManager()
        loginManager.logIn(readPermissions: [.publicProfile], viewController: nil) { loginResult in
            switch loginResult {
            case .failed(let error):
                print(error)
            case .cancelled:
                print("User cancelled login.")
            case .success( _, _, _):
                print("Logged in!")
       
                let fbProvider = FacebookProvider()
                let fbcredentialsProvider = AWSCognitoCredentialsProvider(regionType: .APNortheast1, identityPoolId: "ap-northeast-1:513a4d57-51c1-4cb9-a574-00197e2c3a21", identityProviderManager: fbProvider)
                let configuration = AWSServiceConfiguration(region: .APNortheast1, credentialsProvider:fbcredentialsProvider)
                AWSServiceManager.default().defaultServiceConfiguration = configuration
                
                // wipe cached creds
                fbcredentialsProvider.clearKeychain()
                fbcredentialsProvider.clearCredentials()
                
                //for call fb login method
                              fbcredentialsProvider.credentials()
                
            }
            }
    }
    
} // end of class


```
fbProvider class:
```
import UIKit
import AWSCognitoIdentityProvider
import FacebookCore
class FacebookProvider: NSObject, AWSIdentityProviderManager {
    func logins() -> AWSTask<NSDictionary> {
        if let token = AccessToken.current?.authenticationToken {
            return AWSTask(result: [AWSIdentityProviderFacebook:token])
        }
        return AWSTask(error:NSError(domain: "Facebook Login", code: -1 , userInfo: ["Facebook" : "No current Facebook access token"]))
    }
}
```

after I login with Fb, my federated identity can get fb login,but my userpool can't get the attributes or signup new user(is that need to signUp at code? Or just link federated identity and userPool?)

my federated identity get fb user:

<img width="483" alt="2017-11-23 10 35 46" src="https://user-images.githubusercontent.com/24777585/33157903-a77050b6-d040-11e7-96a3-333a22a36db0.png">

but my user pool didn't create new user:
<img width="914" alt="2017-11-23 10 36 04" src="https://user-images.githubusercontent.com/24777585/33157922-bd399e48-d040-11e7-86cd-388d4804fada.png">

here is my user pool setting:
<img width="1121" alt="2017-11-23 11 27 49" src="https://user-images.githubusercontent.com/24777585/33158029-73ced100-d041-11e7-801e-114e8dfd6850.png">
<img width="974" alt="2017-11-23 11 24 43" src="https://user-images.githubusercontent.com/24777585/33157969-0f55576c-d041-11e7-91e7-bdca0a9f11b4.png">
<img width="906" alt="2017-11-23 10 43 40" src="https://user-images.githubusercontent.com/24777585/33157978-1ec2f6aa-d041-11e7-863d-4dd3e996fdd6.png">

did I miss something?

**Comment by mvpscottjon** [comment]
I find somwhere I was wrong!!!!!

for example, When I use facebook login, follow the step below:

1. type your cognito
<img width="1204" alt="2017-11-28 5 41 08" src="https://user-images.githubusercontent.com/24777585/33312891-12e73d60-d464-11e7-9539-9405cda148e6.png">
2.follow official document:

[http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social.html
](url)
copy the domain prefix  and add `/oauth2/idpresponse`  at the last
<img width="1223" alt="2017-11-28 5 34 26" src="https://user-images.githubusercontent.com/24777585/33313293-32e8d730-d465-11e7-930d-96644902a4c2.png">

I also put app url,but it seems not to necessary.

<img width="1222" alt="2017-11-28 5 34 08" src="https://user-images.githubusercontent.com/24777585/33313518-daac406a-d465-11e7-9c5d-3b4874b3fbb8.png">

I'm a new one for using AWS, maybe this is stupid question.
But I hope no one just stuck at this problems for  two weeks ....

**Comment by johndpope** [comment]
Dear Amazon, 

Please create a cheat sheet to get this working. 

From reading docs - and click buttons for 3 hours last week ....

in IAM - create provider - Provider URL accounts.google.com


<img width="1228" alt="screen shot 2018-02-22 at 10 20 54 am" src="https://user-images.githubusercontent.com/289994/36547244-612b56d8-17bb-11e8-9c71-ed725637de08.png">


for audience specify the id from 
Manage User Pools > User Pool > App Integration > App Client Settings > grab this id 
and add as **audience**


<img width="1215" alt="screen shot 2018-02-22 at 10 26 07 am" src="https://user-images.githubusercontent.com/289994/36547036-d531bb90-17ba-11e8-8339-757a5990198d.png">

**Comment by johndpope** [comment]
From this group - the users should show up - (but actually not working for me.)
<img width="1223" alt="screen shot 2018-02-22 at 10 34 56 am" src="https://user-images.githubusercontent.com/289994/36547513-0c877458-17bc-11e8-8029-9b6b18e1494c.png">

**Comment by johndpope** [comment]
skimming through this thread - 
https://github.com/aws/amazon-cognito-identity-js/issues/508

digging further in to this - I think the oauth 2 needs to be wired up to hit the appropriate redirect....

For Google, add your Amazon Cognito user pool domain URL (**https://<your-user-pool-domain>/oauth2/idpresponse**) in the Google app's Authorized redirect URIs (in the Credentials section).

For Facebook, add your Amazon Cognito user pool domain URL (**https://<your-user-pool-domain>/**) in the Facebook app's Settings (Basic), Website URL.

For Login with Amazon, add your Amazon Cognito user pool domain URL (**https://<your-user-pool-domain>/oauth2/idpresponse**) to the Login with Amazon app's Allowed Return URLs.



https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started.html
<img width="854" alt="screen shot 2018-02-22 at 11 08 27 am" src="https://user-images.githubusercontent.com/289994/36549418-c12a37f2-17c0-11e8-9482-30021cc15d3e.png">

**Comment by johndpope** [comment]
create a domain url 
<img width="1197" alt="screen shot 2018-02-22 at 11 11 12 am" src="https://user-images.githubusercontent.com/289994/36550372-1fd88888-17c3-11e8-9aea-4057a1fe02cf.png">

put that into facebook app. 
<img width="1215" alt="screen shot 2018-02-22 at 11 25 06 am" src="https://user-images.githubusercontent.com/289994/36550381-27d1b78a-17c3-11e8-9420-833c4f5f4d7b.png">

**Comment by johndpope** [comment]
related - https://github.com/awslabs/aws-sdk-ios-samples/issues/236
- I'm still stuck getting the facebook users to show up
I believe I've followed all these steps. 
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social.html

**Comment by johndpope** [comment]
I found the official cheat sheet

https://aws.amazon.com/blogs/aws/launch-amazon-cognito-user-pools-general-availability-app-integration-and-federation/



to get users to automatically be created in cognito - 


"This would only work if they use the Hosted UI: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-ux.html

If they have their own UI, then logging in with FB/Google still requires that they create a hook to add that user to Cognito (which is a hack, btw, since the user won’t be able to login without a password).

So yes, this is possible but only with Hosted UI.

They should review this video to get more details about the hosted UI: https://www.youtube.com/watch?v=VZqG7HjT2AQ

There’s a link to the app in the comments, which should get them started faster."

**Comment by dlippy** [comment]
@johndpope We have been struggling with this as well.  Thanks for the information.  So it looks like it's just not possible in iOS without using a hack?

**Comment by johndpope** [comment]
I guess what's not said here - is that to do this natively - you would need to craft a lambda function to trigger when user signs up via facebook  - then create a pseudo cognito user (with a default password that would never be used). That is happening with the hosted ui flow. hypothetically - you could include api secret keys with create permissions to call this yourself. 
this repo / not official from aws - can do administrative functionality in swift - the idea of embedding this into a public app is kind of a nightmare security waiting to happen but possibily you could lock down a security profile to only allow creation of accounts.
 
I only saw this code the other day - haven't used / or dived into it beyond face value. 

https://github.com/noppoMan/aws-sdk-swift

here an s3 bucket is created programatically 

```swift

import AWSSDKSwift

do {
    let bucket = "my-bucket"

    let s3 = S3(
        accessKeyId: "Your-Access-Key",
        secretAccessKey: "Your-Secret-Key",
        region: .apnortheast1
    )

    // Create Bucket
    let createBucketRequest = S3.CreateBucketRequest(bucket: bucket)
    _ try s3.createBucket(createBucketRequest)

    // Upload text file to the s3
    let bodyData = "hello world".data(using: .utf8)!
    let putObjectRequest = S3.PutObjectRequest(bucket: bucket, contentLength: Int64(bodyData.count), key: "hello.txt", body: bodyData, acl: .publicRead)
    _ = try s3.putObject(putObjectRequest)

    // Get text file from s3
    let getObjectRequest = S3.GetObjectRequest(bucket: bucket, key: "hello.txt")
    let getObjectOutput = try s3.getObject(getObjectRequest)
    if let body = getObjectOutput.body {
      print(String(data: body, encoding: .utf8))
    }
} catch {
    print(error)
}
```

**Comment by dlippy** [comment]
We were able to use their hosted flow in a mock web app and see the user get created in the pool and shown as EXTERNAL_PROVIDER for status.  I suppose like you say we can emulate this with a lambda but I think if that's the only option we will probably just get rid of the federated identity providers for now.  We are in the process of implementing the android version as well and interestingly it looks like it does create the user in the pool...

**Comment by desokroshan** [comment]
@mvpscottjon As mentioned by @johndpope, current behavior is that a user authenticated via fb is created on the user pools console if you use the [Hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-ux.html) for authentication. If you have your own UI, logging via an external provider you would need additional hook to add the user to user pools console. Please let us know if you need any further clarification.

**Comment by Birowsky** [comment]
@desokroshan I would love some clarification around using the native UI instead of the hosted one.

The native ui [resolves with an auth code](https://github.com/EddyVerbruggen/cordova-plugin-googleplus#8-exchanging-the-serverauthcode) that is sufficient to auth the user inside cognito user pool, I just wonder which api/endpoint to use to finish up the deal.
