### ISSUE TITLE
POLLY SWIFT SAMPLE COULD NOT RUN SUCCESSFULLY,HELP

### ISSUE THREAD

**Issue by randyhere** [awslabs/aws-sdk-ios-samples#229]
libc++abi.dylib: terminating with uncaught exception of type NSException
what is wrong?help me.

**Comment by kredden** [comment]
Hi, can you give us some more information?  What version of the SDK are you using?  Can you post the stack trace?

**Comment by kredden** [comment]
I just verified that the sample does work correctly with the latest version of the SDK.  The README.md for the sample is currently being updated to make the instructions clearer.  They will look something like this:

In the Amazon Cognito Console, press the **Manage Federated Identities** button and on the resulting page press the **Create new identity pool** button.

Give your identity pool a name and ensure that **Enable access to unauthenticated identities** under the **Unauthenticated identities** section is checked. This allows the sample application to assume the unauthenticated role associated with this identity pool. Press the **Create Pool** button to create your identity pool.

Important: see note below on unauthenticated user access.

As part of creating the identity pool, Cognito will setup two roles in Identity and Access Management (IAM). These will be named something similar to: _Cognito_PoolNameAuth_Role and_ _Cognito_PoolNameUnauth_Role_. You can view them by pressing the **View Details** button. Now press the **Allow** button to create the roles.

Save the _Identity pool ID_ value that shows up in red in the "Getting started with Amazon Cognito" page, it should look similar to: `us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" and note the region that is being used. These will be used in the application code later.

Now we will attach a policy to the unauthenticated role which has permissions to access the required Amazon Polly API. This is done by attaching an IAM Policy to the unauthenticated role in the IAM Console. First, search for the unauth role that you created in step 3 above (named something similar to _Cognito_PoolNameUnauth_Role_) and select its hyperlink. In the resulting **Summary** page press the Attach Policy button in the **Permissions** tab.

Search for "polly" and check the box next to the policy named _AmazonPollyFullAccess_ and then press the **Attach Policy** button. This policy allows the application to perform all operations on the Amazon Polly service.

Note: to keep this example simple it makes use of unauthenticated users in the identity pool. This can be used for getting started and prototypes but unauthenticated users should typically only be given read-only permissions in production applications.

Open PollySample.xcworkspace.

Open Constants.swift and update the following lines with the appropriate constants:

let AwsRegion = AWSRegionType.Unknown
let CognitoIdentityPoolId = "YourCognitoIdentityPoolId"
Build and run the sample app.

I am closing this issue as the code seems to work fine.  If you are still having issues please reopen the issue.
