### ISSUE TITLE
Importing <AWSCore/AWSCore.h> causes parse errors in AWSCategory.h

### ISSUE THREAD

**Issue by gadphly** [awslabs/aws-sdk-ios-samples#23]
Hello,
I am using portions of the CognitoSync sample in my own code with Google Login.
However when i import <AWSCore/AWSCore.h>, I get Parse Issue errors in AWSCategory.h as seen below for
@interface NSDate (AWS)
@interface NSDictionary (AWS)
.. and other NS objects.

Any idea??

thank you.

![screen shot 2015-08-21 at 2 55 02 pm](https://cloud.githubusercontent.com/assets/12171600/9417800/ea2db918-4814-11e5-9945-7b166d36da00.png)

**Comment by yosuke-matsuda** [comment]
Do you get the same issue with a fresh copy of the CognitoSync sample? Have you cleaned the Xcode cache?
