### ISSUE TITLE
 Wrong number of slashes

### ISSUE THREAD

**Issue by Gelacio** [awslabs/aws-sdk-ios-samples#230]
func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        
       ...
let deviceTokenString = deviceToken.reduce(""){$0 + String(format: "%02X", $1) }
        
        print("deviceTokenString: \(deviceTokenString)")
        UserDefaults.standard.set(deviceTokenString, forKey: "deviceToken")
        mainViewController()?.displayDeviceInfo()
    
        let sns = AWSSNS.default()
        let request = AWSSNSCreatePlatformEndpointInput()
        request?.token = deviceTokenString
        request?.platformApplicationArn = SNSPlatformApplicationArn
        
        
        sns.createPlatformEndpoint(request!).continue(with: AWSExecutor.mainThread(), with: { (task: AWSTask!) -> AnyObject! in
            if task.error != nil {
                print("Error: \(String(describing: task.error))")
            } else {
                let createEndpointResponse = task.result
                print("endpointArn: \(String(describing: createEndpointResponse?.endpointArn))")
                UserDefaults.standard.set(createEndpointResponse?.endpointArn, forKey: "endpointArn")
                self.mainViewController()?.displayDeviceInfo()
            }
            
            return nil
        })
    }

Any idea why I'm getting this error:
<Error>
    <Type>Sender</Type>
    <Code>InvalidParameter</Code>
    <Message>Invalid parameter: PlatformApplicationArn Reason: Wrong number of slashes in relative portion of the ARN.</Message>
  </Error>

Using ARN and topic ARN in this format

let SNSPlatformApplicationArn = "arn:aws:sns:us-west-2:xxxxxxxxxxxx:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

**Comment by kvasukib** [comment]
Hi @Gelacio, 

Thanks for reporting to us. Sorry for the inconvenience caused.
Can you tell us how did you fetch the SNSPlatformApplicationArn?

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If there's still an issue, please open it in the aws/aws-sdk-ios repo.
