### ISSUE TITLE
 Certificate and Private Key from server not in bundle for AWS IOT connection in swift

### ISSUE THREAD

**Issue by johnikarthi** [awslabs/aws-sdk-ios-samples#231]
I am receiving certificate and private key from server to connect with AWS iot. Is there any method that takes certificate and private key as parameters and returns as .p12 file in aws SDK?

Or is there any other way to create .p12 file with received certificate and private key in swift 2.3?

Or please suggest if it is any other way?

**Comment by kelvin996** [comment]
ex.
openssl pkcs12 -export -in certificate.pem.crt -inkey private.pem.key -out awsiot-identity.p12

use command to create .p12 file

**Comment by johnikarthi** [comment]
Thanks, for all your replies. I requested my server team to create .p12 file and send through an api call.
