### ISSUE TITLE
unable to activate voice along the Prompt programmatically via iOS

### ISSUE THREAD

**Issue by Baalakrishnan** [awslabs/aws-sdk-ios-samples#233]
I started working on the Lex voice service, based on the input I need to activate prompt for further filter, but Lex SDK and AWSLexVoiceButton delegate not have the option to enable the lex voice programmatically and not able to prompt text to voice / speech from Lex itself

**Comment by kredden** [comment]
Do you want to just enable Lex programmatically or do you want to do that as well as using the button?  If you just want to enable it programmatically the just look at the code to see how the AWSLexVoiceButton does so and you can do the same thing.

Regards,
Kevin

**Comment by kredden** [comment]
If this does not answer your question then please reopen this issue.

Regards,
Kevin

**Comment by Baalakrishnan** [comment]
AWSLexVoiceButton has this as the private method "startMonitoring" / " startListening" and no delegate to access this methods from AWSLexVoiceButton and also for changing the mic-Icon and voice view customisation also not possible because all are private methods, not able to access directly using AWSLexVoiceButton instance

Regards,
Balakrishnan

**Comment by kredden** [comment]
Balakrishnan,

If you want to change the way the button works you can always create your own version of it and use that instead.

Regards,
Kevin
