### ISSUE TITLE
IoTSampleSwift throw NSInternalInconsistencyException

### ISSUE THREAD

**Issue by kelvin996** [awslabs/aws-sdk-ios-samples#238]
2018-01-09 15:05:37.429272+0800 IoTSampleSwift[1508:499351] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid region type.'
*** First throw call stack:
(0x1c2f3b3d 0x1b57b067 0x414a81 0x3a862d 0x3e57bf 0x3add7f 0x109140 0x106c4c 0x1064d0 0x106f84 0x21525eb7 0x21525ad9 0x21657b23 0x216578db 0x21657745 0x2165a305 0x215335c3 0x2165bf85 0x2165acd1 0x2153d0ad 0x2153ceff 0x2159f0df 0x2152d9d5 0x2152cdad 0x2152cc03 0x2152c211 0x215295bb 0x21599159 0x21796b13 0x2179bc1d 0x217ae7c5 0x2179935b 0x1dbd4c13 0x1dbd4acd 0x1dbd4db7 0x1c2affdd 0x1c2afb05 0x1c2adf51 0x1c2011af 0x1c200fd1 0x2158ee2d 0x21589a53 0xf15d0 0x1b9ee4eb)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kvasukib** [comment]
Hi @kelvin996, 

Thanks for reporting to us. 

Have you modified the region in [Constants.swift](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/Constants.swift)? 

For example, if your AWS region is `us-east-1`, you need to add `AWSRegionType.USEast1` in this file. The `README.md` file explains all the steps required to configure this app.
