### ISSUE TITLE
How to upload or download multiple images at a time using TransferUtility or TransferManager (Swift)?

### ISSUE THREAD

**Issue by Vincent-St** [awslabs/aws-sdk-ios-samples#239]
How to upload or download multiple images at a time using TransferUtility or TransferManager (Swift)?

**Comment by rohandubal** [comment]
Hello,

You would have to call the upload/ download method multiple times for concurrent uploads/ downloads. Currently there is no method which provides batch upload/ download from a list of files.

Thanks,
Rohan

**Comment by Vincent-St** [comment]
Thanks for the reply, Rohan. I just found the resolution half an hour ago from [the example of AWSS3 TransferManager. ](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample/Swift)

But it took me more than 3 days. Can't believe this.  I'm not sure if you are from AWS Mobile Team. But the [documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-ios-s3-transfermanager.html) is so confusing. There are so many different versions of documentation, such as AWS Mobile SDK iOS Developer Guide, AWS Mobile Hub Developer Guide Version 1.0, AWS Mobile Developer Guide, etc. Jesus. Please put all the details to one documentation if possible.

I don't think people would like to be stuck on finding an correct official documentation, when they get started with Amazon Mobile Hub.

Best Regards,
Vincent

**Comment by kvasukib** [comment]
Hi @Vincent-St, Sorry for the inconvenience caused in finding the documentation. We are continuously working on to improve out documentation. You can see our [How-to-transfer-files-with-TransferUtility](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html) for more information.
