### ISSUE TITLE
continueOnSuccessWith doesn't call

### ISSUE THREAD

**Issue by sebasx** [awslabs/aws-sdk-ios-samples#240]
Hello,

Constants looks fine:

```
let AwsRegion = AWSRegionType.EUWest2 // e.g. AWSRegionType.usEast1
let CognitoIdentityPoolId = "eu-west-2_(...)"
```

but after run app I see that continueOnSuccessWith closure is not called

```
		task.continueOnSuccessWith { (awsTask: AWSTask<AWSPollyDescribeVoicesOutput>) -> Any? in
            print("i am here")
```

pickerValues is empty array

`pickerValues []`

and app crush on selectedVoice = pickerValues[row]

when I click on Synthesize button, I don't see aby action. Console is clear

```
2018-01-14 22:42:31.311769+0100 PollySample[18917:239258] [MC] Lazy loading NSBundle MobileCoreServices.framework
2018-01-14 22:42:31.313268+0100 PollySample[18917:239258] [MC] Loaded MobileCoreServices.framework
```

**Comment by rohandubal** [comment]
Hello,

Have you attached the IAM permissions to access the `DescribeVoices` api from the unauthenticated role of Cognito Identity Pool?

Also, `continueOnSuccessWith ` is called only if the request successfully goes through. To debug the error, could you use `continueWith` and use the error message to print the error debug log?

Thanks,
Rohan

**Comment by kredden** [comment]
Yes, you need to follow all the instructions in the ReadMe file: https://github.com/awslabs/aws-sdk-ios-samples/blob/master/Polly-Sample/Swift/README.md.  If you don't set up the policy correctly then the list of voices will not show up.

Regards,
Kevin
