### ISSUE TITLE
How to upload photos or videos to AWS S3 Bucket (only the uploader could list these objects) with Swift 4?

### ISSUE THREAD

**Issue by Vincent-St** [awslabs/aws-sdk-ios-samples#242]
I'm able to upload or download photos or videos to AWS S3 Bucket. But it seems the two users in my User Pool both could view or list those photos or videos. (I have two users in my User Pool, which were created automatically when sign up my sample app. )

<img width="2133" alt="screen shot 2018-01-24 at 22 33 28" src="https://user-images.githubusercontent.com/12606544/35337946-8976ce26-0157-11e8-9b97-e001606c164b.png">

<img width="2499" alt="screen shot 2018-01-24 at 22 40 57" src="https://user-images.githubusercontent.com/12606544/35337992-ac8a15bc-0157-11e8-9a19-8a70b44c5a6e.png">

But what I want to archive is: Only the uploader could list those photos that he uploaded before, not any other users. Just like the MySampleApp does, the current login user could only list what he uploaded before.

<img width="565" alt="screen shot 2018-01-24 at 22 44 21" src="https://user-images.githubusercontent.com/12606544/35338169-229192c6-0158-11e8-92ac-ed97f434dd47.png">

I did read the codes from the MySampleApp project, but it seems too complicated. Is there any other way to make it easy? Thanks.

**Comment by kvasukib** [comment]
Hi @Vincent-St,

Thanks for reporting to us. Sorry for the inconvenience caused.

I did the following experiment:

Download the Mobile hub sample app.
Sign up user1, sign-in as user1, upload a picture: image1.png
View the picture uploaded, downloaded it.
I am able to see just **image1** under private

Sign out the user user1

Sign up user2, sign-in as user2, upload a picture: image2.png
View the picture uploaded, downloaded it.
I am able to see just **image2** under private

Did you modify the app or back-end settings manually after creating the mobile hub project?

Thanks

**Comment by Vincent-St** [comment]
Hi @kvasukib ,

Thanks for your reply. Yes, you are definitely correct. And my sample app works well like yours. 

But when I create a new bucket in AWS S3, I have no idea how to set up the permission so that it will works like the sample app downloaded from AWS Mobile Hub resources center. I mean when I create a new bucket in AWS S3, all users could view any other user's uploaded pictures.

Any ideas you can share with me? Thanks. The codes from the sample looks a little bit different for me.

Thanks.

**Comment by rohandubal** [comment]
Hello @Vincent-St,

To achieve the use-case which you described above, you will have to manually set up the IAM policies. You could use the Mobile Hub resources setup as a reference point to set up your own policies. 

Thanks,
Rohan
