### ISSUE TITLE
enhancement - refactor global constants to unify variables across classes

### ISSUE THREAD

**Issue by johndpope** [awslabs/aws-sdk-ios-samples#245]
problem is - 
sample code has variables flying everywhere

FOUNDATION_EXPORT AWSRegionType const CognitoRegionType;
FOUNDATION_EXPORT NSString *const CognitoIdentityPoolId;
FOUNDATION_EXPORT NSString *const DeviceTokenKey;
FOUNDATION_EXPORT NSString *const CognitoDeviceTokenKey;
FOUNDATION_EXPORT NSString *const CognitoPushNotification;
FOUNDATION_EXPORT NSString *const DeveloperAuthAppName;
FOUNDATION_EXPORT NSString *const DeveloperAuthEndpoint;
FOUNDATION_EXPORT NSString *const DeveloperAuthProviderName;

it would be best to wrap into a struct of some sort - then when the code references these variables - they will be unified. 

Cognito.clientId
Cognito.regionType

struct Cognito {
    
    static let clientId:String = "test" // AWS -> ctest4 -> App Integration / App client settings
    static let CognitoIdentityUserPoolAppClientSecret:String =  "" // not configured nor used - nor known - should be nil
    static let AWSCognitoUserPoolsSignInProviderKey:String = "UserPool"
    
    static let regionType: AWSRegionType = AWSRegionType.APSoutheast2
    static let poolId = "ap-southeast-2"  // general settings / Pool Id
    static let identityPoolId = "ap-southeast-2:1234"
    static let identityPoolRegion: AWSRegionType = Cognito.regionType
    
    
}

**Comment by johndpope** [comment]
probably better to read from the plist 

<img width="627" alt="screen shot 2018-02-21 at 2 57 16 pm" src="https://user-images.githubusercontent.com/289994/36502316-8e5fca20-1717-11e8-8fb3-09656d929415.png">

**Comment by cbommas** [comment]
@johndpope 

Thank you for your feedback. I've added this request to our backlog and will wiyh work our team to get it prioritized.
