### ISSUE TITLE
feedback -  aws-my-sample-app-ios-swift generated sample crashes on successful google login

### ISSUE THREAD

**Issue by johndpope** [awslabs/aws-sdk-ios-samples#246]
sample file
https://drive.google.com/file/d/1yVFNaLgfxu5S44zysgejjIdquSuvMVvB/view?usp=sharing

Cannot find executable for CFBundle 0x7fa8e5e42ea0 </Users/johndpope/Library/Developer/CoreSimulator/Devices/8ECCD6EE-9AB3-4559-810E-C00739F786BA/data/Containers/Bundle/Application/0522829F-326A-4059-B105-D39FC02E46AE/MySampleApp.app/Frameworks/AWSAuthUI.framework/AWSAuthUI.bundle> (not loaded)

upon logging in with google - I get a 
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

<img width="962" alt="screen shot 2018-02-21 at 2 23 50 pm" src="https://user-images.githubusercontent.com/289994/36500663-ddb9a410-1712-11e8-8fd4-740ad7623fbf.png">

I have run
pod install --repo-update

**Comment by johndpope** [comment]
tried on device / simulator no joy
after signing into google page - it's coming up with google search page.

**Comment by johndpope** [comment]
import GoogleSignIn




    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {

        
        return GIDSignIn.sharedInstance().handle(url,
                                                 sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String,
                                                 annotation: options[UIApplicationOpenURLOptionsKey.annotation])
    }

**Comment by cbommas** [comment]
@johndpope 

Just checking in to see if you are good to go or need help on this thread?

**Comment by johndpope** [comment]
so the sample code that's spat out by aws mobile hub is missing above code. This is a critical bug. 

thus - will crash when you successfully sign in to google.
I got it working for myself - but needs to be fixed upstream. 

also - would make a lot of sense to have this sample dummy app in it's own repo (perhaps with all sign in / additional capabilities enabled.) the wizard style coding is great - but when you need to add stuff - I think it would beneficial to community to be able to chime in on features. 
eg. how to read email from facebook / google - this is not supported in sample. 

I'd also suggest using a protocol approach to adding code.
eg. Extend LoginViewController to support facebook - this would keep code separated / and not a massive hodge podge. Users can then cherry pick code into their own apps. 

<img width="1269" alt="screen shot 2018-02-22 at 9 52 19 am" src="https://user-images.githubusercontent.com/289994/36545088-19ecd6d4-17b6-11e8-90e9-99496e94ba24.png">

**Comment by johndpope** [comment]
AppDelegate+Google.swift
```swift

extension AppDelegate{
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {

        
        return GIDSignIn.sharedInstance().handle(url,
                                                 sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String,
                                                 annotation: options[UIApplicationOpenURLOptionsKey.annotation])
    }
}
```

**Comment by johndpope** [comment]
to be clear - the permissions are set to read public profile / and potentially email - but there's no actual call to invoke this from sample code. this needs it's own ticket - and preferrably where the repo for sample app is. 

```swift
extension LoginViewController : FBSDKLoginButtonDelegate {
    
    func configureFacebook(){
        // log out the user if previously logged in.
        let facebookLoginManager = FBSDKLoginManager()
        facebookLoginManager.logOut()
        
        // set up the information you want to read from the user's Facebook account.
        facebookButton.readPermissions = ["public_profile", "email"];
    }
    
    func loginButton(_ loginButton: FBSDKLoginButton!,
                     didCompleteWith result: FBSDKLoginManagerLoginResult!,
                     error: Error!) {
        
        if error != nil {
            displayLoginError(error: error as NSError)
            return
        }
        
        if result.isCancelled {
                return
        }
        
        guard let idToken = FBSDKAccessToken.current() else {
            let error = NSError(domain: "com.asmtechnology.awschat",
                                code: 100,
                                userInfo: ["__type":"Unknown Error", "message":"Facebook JWT token error."])
            self.displayLoginError(error: error)
            return
        }
        
        
        let graphRequest : FBSDKGraphRequest = FBSDKGraphRequest(graphPath: "me",
                                                                 parameters: ["fields":"email,name"])
        
        graphRequest.start(completionHandler: { (connection, result, error) -> Void in
            
            if let error = error {
                self.displayLoginError(error: error as NSError)
                return
            }
            
            if let result = result as? [String : AnyObject],
                let name = result["name"] as? String {
                
                let email = result["email"] as? String
                

                CognitoIdentityPoolController.shared.getFederatedIdentityForFacebook(idToken: idToken.tokenString,
                    username: name, emailAddress: email,
                    completion: { (error: Error?) in
                        
                        if let error = error {
                            self.displayLoginError(error:error as NSError)
                            return
                        }
                        
                        self.displaySuccessMessage()
                        return
                })
                
            }
            
        })
        
    }
    
    func loginButtonDidLogOut(_ loginButton: FBSDKLoginButton!) {
        // do nothing.
    }
    
}
```

**Comment by rohandubal** [comment]
Hello @johndpope 

We have instructions where we mention to add interceptors in delegate which are handled by AWSMobileClient and call underlying provider's methods (Google in this case)

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html#set-up-google -> Step 4 in this link

That should prevent the crash.

I also understand your point where if we want to separately add Google handler, we need to call Google Sign In SDK directly.

Thanks,
Rohan
