### ISSUE TITLE
Rename apps in repo that are out of date to deprecated.

### ISSUE THREAD

**Issue by johndpope** [awslabs/aws-sdk-ios-samples#248]
There’s a lot of time being wasted by people using out of date code. Should focus on mobile hub code and improve this code generation instead of supporting the code rot in these repos.

**Comment by minbi** [comment]
Hi @johndpope ,

We will take this into consideration and work to keep the samples marked or updated.

Do you prefer to use these samples or the mobile hub code?

**Comment by johndpope** [comment]
if the mobile hub code could be polished over time - then I think it's best to focus efforts there in my opinion. There's a divergence in code styles and code is frankly rotting in this repo / old pull requests that are conflicted and  there's a degree of too many cooks spoiling the broth in my opinion (see cognito sync in swift 2).  

only problem with mobile hub code - there's no repo - there's currently no way to submit PRs. 
I could imagine that there's some meta programming to dynamically turn / turn off things - getting the sample app to a world class level would be best for everyone. Why have 100 developers spending 3-6 hours fixing rotting code base - when if you focus those hours / time into perfecting sample generated app - then it would save lots of time / effort. 

If the use cases of aws swift are fleshed out and covered by mobile hub 
eg. (sign in via amazon login natively - join existing accounts / get facebook email etc) - and the mobile hub code is updated and tuned - then maintaining these repos is superseded in my opinion. 

I lost a week or two sourcing code from github - most of which is outdated. 
https://github.com/BruceBuckland/SignIn-awsmhh/issues/7
 
Also in my opinion - cheat sheets should have a more prominent place for people getting started. 
Pictures speak a thousand words - this needs more visibility in my opinion. 
https://aws.amazon.com/blogs/aws/launch-amazon-cognito-user-pools-general-availability-app-integration-and-federation/

Also - because you're listening I recommend using protocol extensions to decouple the view controllers from logic. I do everything programatically - so want to drop in functionality in my own app without code being tangled to IBOUTLETS. 
eg. LoginViewController+Facebook.swift

**Comment by muellerfr** [comment]
Hello @johndpope,

We updated the name of directories and the readme files to indicate which samples have been deprecated. We will delete the deprecated samples in two weeks. We're going through the remaining samples to refresh them.

**Comment by johndpope** [comment]
this is done. thanks
