### ISSUE TITLE
getSession login does not authenticate user until app is restarted

### ISSUE THREAD

**Issue by HTCDeveloper** [awslabs/aws-sdk-ios-samples#249]
As the title suggests the AWSCognitioIdentityUser when attempting to create a session using the SDK doesn't actually authenticate the user immediately after the continueBlock even though it came back as a success.

After the continueBlock comes back with a success i move the user to the next viewController and attempt to call a lambda function using the new assigned identity ID, but unfortunately the ID is rejected by my lambda function because the identity ID isn't the ID of the user that just logged in and thus the identity has a value of unauthenticated. 

To be more specific i am using the explicit log in [[getSession username: password: ] continueWithBlock].

If i was to restart the app, the users session is found immediately and when i attempt to make the same call to the lambda function the correct identityID seems to be sent.

So what is happening in the time that I log in, than restart the app. What exactly am i missing?

Here is an example of my code which logs in the user but doesnt give me the correct authentication

` [[user getSession:finalAccountName password:_passwordField.text validationData:@[type]] continueWithExecutor:[AWSExecutor mainThreadExecutor] withBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserSession *> * _Nonnull initialTask) {
        
        AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSWest2 identityPoolId:@"your_identity_id_here" identityProviderManager:sharedDelegate.mainUserPool];
        
        [[credentialsProvider getIdentityId] continueWithExecutor:[AWSExecutor mainThreadExecutor] withBlock:^id _Nullable(AWSTask<NSString *> * _Nonnull t) {
            
            
            [(UIButton*)sender setUserInteractionEnabled:TRUE];
            [loader removeFromSuperview];
            
            if(initialTask.error){
                UIAlertController *controller = [UIAlertController alertControllerWithTitle:@"Login Failed" message:[initialTask.error.userInfo objectForKey:@"message"] preferredStyle:UIAlertControllerStyleAlert];
                [controller addAction:[UIAlertAction actionWithTitle:@"OK!" style:UIAlertActionStyleCancel handler:nil]];
                [self presentViewController:controller animated:YES completion:nil];
            } else {
                LoginStuffViewController *stuff = [[LoginStuffViewController alloc] init];
                [self.navigationController pushViewController:stuff animated:NO];
            }
            return nil;
        }];
        
        
        return nil;
    }];`

**Comment by behrooziAWS** [comment]
Couple suggestions here:

1.  Before changing the logged in user, you should also call [clearCredentials](https://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoCredentialsProvider.html#//api/name/clearCredentials) on your credentials provider.  Credentials are good for an hour, and the credentials provider will continue to use the ones it has unless you tell it to drop them.
2. You don't need to call getIdentityId prior to calling your lambda, if you've associated your lambda client with your credentials provider, it will lazily call getIdentityId/getCredentials as necessary.
3. It is unclear what credentials provider you have associated with your lambda client.  Normally you have a single credentials provider that your configure in your AppDelegate and is the credentials provider for all clients.  Creating multiple credentials providers can have unpredictable results if you are expecting them to play nicely with each other.  I would recommend setting up your user pool and credentials provider in the app delegate as the defaults

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If there's still an issue, please open it in the aws/aws-sdk-ios repo.
