### ISSUE TITLE
AWS File transfer failure + New SDK migration issues

### ISSUE THREAD

**Issue by vickyrappier** [awslabs/aws-sdk-ios-samples#25]
Hello Team,

I have below mentioned issues that I am facing while integrating new SDK.

1) New SDK imported but still gives me compile error for AWSTask not found, have to forcibly go ahead with BFTask only after migration. 

2) When multiple files are send in loop and calling the S3Backgroundtransfer sample code given few files are missed while other get successfully uploaded. How to make it synchronous and check if connection is successfully established.

I have always observed that first time the connection is stuck with warning 'A Long running operation is done over main thread' this problem is happened'

Can anyone please help on this.

Thanks, 
Regards,
Vicky

**Comment by yyzhu** [comment]
@vickyrappier 

1) The most possible reason is the project has not been cleaned up thus Xcode is still looking for old SDK while import.

If you were installed via Cocoapods, please remove `Podfile.lock` and `Pods/` folder, and run `pod install` to reinstall the SDK. Please also make sure the cocoapods has been updated to latest version (0.38.2).

If you were installed via static framework, make sure the `Framework Search Paths` and `Header Search Paths` in Build Settings doesn't contains directory of the old framework.


2) Could you give me a sample project that could reproduce this issue? It is kinda hard to debug without actually see the code.

Thanks!

**Comment by vickyrappier** [comment]
Hello Yi Zhu,

Thanks for the instant reply I shall try the process informed by you for the
upgrade and come back if face any issue.

For the missed filed upload on S3 here is my implementation that I am using
in chat application

Attached document  have  the code base for the flow I am working on.

Thanks,
Regards,
Vicky S Dhas | Project Manager
Email:vickydhas@rappier.com

Please consider the impact to the environment before printing this email

This e-mail is confidential and may also be privileged. If you are not the
intended recipient, please notify us immediately by replying to this message
and then delete it from your system. You should not copy or use it for any
purpose, nor disclose its contents to any other person. Thank you.


From:  Yi Zhu <notifications@github.com>
Reply-To:  awslabs/aws-sdk-ios-samples
<reply+00a9e1ab90d3ae1bc8793df2311b9d56c09fde2eee8e1b3492cf000000011206fe5d9
2a169ce06448693@reply.github.com>
Date:  Wednesday, 9 September 2015 3:51 am
To:  awslabs/aws-sdk-ios-samples <aws-sdk-ios-samples@noreply.github.com>
Cc:  Vicky Dhas <vickydhas@rappier.com>
Subject:  Re: [aws-sdk-ios-samples] AWS File transfer failure + New SDK
migration issues (#25)


@vickyrappier <https://github.com/vickyrappier>

1) The most possible reason is the project has not been cleaned up thus
Xcode is still looking for old SDK while import.

If you were installed via Cocoapods, please remove Podfile.lock and Pods/
folder, and run pod install to reinstall the SDK. Please also make sure the
cocoapods has been updated to latest version (0.38.2).

If you were installed via static framework, make sure the Framework Search
Paths and Header Search Paths in Build Settings doesn't contains directory
of the old framework.

2) Could you give me a sample project that could reproduce this issue? It is
kinda hard to debug without actually see the code.

Thanks!


Reply to this email directly or view it on GitHub
<https://github.com/awslabs/aws-sdk-ios-samples/issues/25#issuecomment-13868
1726> .

**Comment by yyzhu** [comment]
Hi @vickyrappier 

I don't think github allows attachment, you may paste the code snippets in this conversation.

**Comment by vickyrappier** [comment]
Hello Yi Zu,

Can you check the link as the code snippet is huge.
https://drive.google.com/open?id=0B-I5s-hddS-PWWNWQTJlRUE3bWM



On Thursday, September 10, 2015, Yi Zhu <notifications@github.com> wrote:

> Hi @vickyrappier <https://github.com/vickyrappier>
>
> I don't think github allows attachment, you may paste the code snippets in
> this conversation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-ios-samples/issues/25#issuecomment-138999222>
> .
>


-- 
Sent from my iPhone

**Comment by yosuke-matsuda** [comment]
Please reduce your project to a minimum reproducible code snippet so that we can assist you in finding a cause, and other people with similar issues can benefit from this.

Also, [AWS Support](https://aws.amazon.com/premiumsupport/) offers one-on-one support if you prefer more one-on-one support. Thanks.

**Comment by yyzhu** [comment]
Hi @vickyrappier,

Please reduce your project to a minimum reproducible code snippet and paste it in this thread so that we can take a look, if you prefer a one-one-one support,  you can use [AWS Support](https://aws.amazon.com/premiumsupport)

**Comment by vickyrappier** [comment]
Okay I'll past the code again with with minimal understanding.

On Thursday, September 17, 2015, Yi Zhu <notifications@github.com> wrote:

> Hi @vickyrappier <https://github.com/vickyrappier>,
>
> Please reduce your project to a minimum reproducible code snippet and
> paste it in this thread so that we can take a look, if you prefer a
> one-one-one support, you can use AWS Support
> <https://aws.amazon.com/premiumsupport>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-ios-samples/issues/25#issuecomment-140828137>
> .
>


-- 
Sent from my iPhone

**Comment by vickyrappier** [comment]
Hello Team,

Below is the shortened code snippet to send multiple files and its failing to send few, below are my queries summarised.

1) How to make it sequential file transfer so the callbacks are received in order I Put in chat screen. Refer WhatsApp the way images are selected and uploading its gone in same order and seen on the other end.
2) There is some operation error that gives error in your example code and mine too for the "Warning: Longer running operation is using the main thread ......' 
3) First media when the session is established is stuck for a long time
4) How to manage the sequencing for the task to give all files once to request and make them work in sequential order of upload. I have seen some example where you can set max task to the upload and set the concurrent count to 1 so all task are queued and start one after the other.
5) Migration of new SDK gives build errors , this I am trying to solve as advised by few developers but BFTask have to be used as AWS task gives error so i have to write the code like below line.
    [[[AWSS3PreSignedURLBuilder defaultS3PreSignedURLBuilder] getPreSignedURL:getPreSignedURLRequest] continueWithBlock:^id(BFTask *task) {
        
        if (task.error)
        {
            NSLog(@"Error startFileUploadForFileWithAbsolutePath: %@",task.error);
            
                    //UI alert thrown

Giving the code snippet that I actually used to make our scenarios handled.

//CODE Snippet START

//Looping for the selected images as given in S3TRansfermanager example as well.
{
        // UIImagePickerControllerMediaType
        if(mediaVO.mediatype == MediaTypeImage)
        {
            UIImage *originaImage = nil;
            // call the result handler block on the main queue (i.e. main thread)
            dispatch_async(dispatch_get_main_queue(), ^{
                
                [[FileManager sharedManager] storeImage:originaImage underFolder:foldername withCompression:YES completion:^(NSString *filePath) {

                    //Add object to DB

                    Chat *chatObject = [....Store all media information in DB here ];

                    //ADD To UI

                    NSString *filePath1 = //File path from which the file is asked to upload
                    
                    //Initiate file transfer
                    //Set state to uploading in DB
                    [[CLBizManager sharedManager] //update the media state as uploding];
                    
                    //The session I tried to keep out of loop so no need to create multiple times and

                    NSURLSession *s3Session = //as below code function


                    static NSURLSession *session = nil;
                    
                    static dispatch_once_t onceToken;
                    dispatch_once(&onceToken, ^{
                        
                        NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:BackgroundSessionUploadIdentifier];
                        session = [NSURLSession sessionWithConfiguration:configuration delegate:(id)self delegateQueue:nil];
                        
                        session.sessionDescription = @"upload";

                    //This is actual function I call to send the file to transfer on S3 , i referred S3BackgroundTransfer example to proceed.

                    [[Uploadmanager sharedManager] startFileUploadForFileWithAbsolutePath:filePath1 session:s3Session];
                
                //Hide loading on UI

                } failed:^(NSError *error) {
                    
                //Hide loading on UI

                    NSLog(@"ERROR: Could not copy file for upload :%@",[error localizedDescription]);
                }];
            });
            
        }
        else if(mediaVO.mediatype == MediaTypeVideo)
        {
            //Same as Image
        }
    }

}


//Upload delegates handled below as the example
-(void)startFileUploadForFileWithAbsolutePath //code here for this function
    {
    NSString *fileName = [[filePath componentsSeparatedByString:@"/"] lastObject];
    
    NSURL *uploadFileURL = [NSURL fileURLWithPath:filePath];
    
    AWSS3GetPreSignedURLRequest *getPreSignedURLRequest = [AWSS3GetPreSignedURLRequest new];
    getPreSignedURLRequest.bucket = S3BucketName;
    getPreSignedURLRequest.key = //File name Key;
    getPreSignedURLRequest.HTTPMethod = AWSHTTPMethodPUT;
    getPreSignedURLRequest.expires = [NSDate dateWithTimeIntervalSinceNow:3600];
    
    //Important: must set contentType for PUT request
    
    NSString *fileContentTypeStr = [NSString stringWithFormat:@"image/%@",[fileName pathExtension]];
    
    getPreSignedURLRequest.contentType = fileContentTypeStr;
    
    [[[AWSS3PreSignedURLBuilder defaultS3PreSignedURLBuilder] getPreSignedURL:getPreSignedURLRequest] continueWithBlock:^id(BFTask *task) {
        
        if (task.error)
        {
            NSLog(@"Error startFileUploadForFileWithAbsolutePath: %@",task.error);
            
                    //UI alert thrown
        }
        else
        {
            NSURL *presignedURL = task.result;
            
            NSLog(@"upload presignedURL is: \n%@", presignedURL);
            
            NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:presignedURL];
            request.cachePolicy = NSURLRequestReloadIgnoringLocalCacheData;
            [request setHTTPMethod:@"PUT"];
            [request setValue:fileContentTypeStr forHTTPHeaderField:@"Content-Type"];
            
            NSURLSessionUploadTask *uploadTask = [session uploadTaskWithRequest:request fromFile:uploadFileURL];
            [uploadTask setTaskDescription:@"upload"];
            [uploadTask resume];
        }
        
        return nil;
    }];
}

//Function used to show progress in NSLog and UI(optional not used yet)
- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend {
    
    double progress = (double)totalBytesSent / (double)totalBytesExpectedToSend;
    NSString *fileName = [[[task currentRequest] URL] lastPathComponent];
    
    NSLog(@"UploadTask progress: %lf", progress);
    
    dispatch_async(dispatch_get_main_queue(), ^{
        
        NSDictionary *dictionary = [NSDictionary dictionaryWithObjects:@[fileName,[NSNumber numberWithDouble:totalBytesSent],[NSNumber numberWithDouble:totalBytesExpectedToSend],[NSNumber numberWithBool:NO]] forKeys:@[kFileName,kFileTotalBytesSent,kFileTotalBytesExpectedToSend,kISFileTaskComplete]];
        
        [[NSNotificationCenter defaultCenter] postNotificationName:kS3TransferUploadNotificationKey object:nil userInfo:dictionary];
    });
}


- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error {
    
    NSString *fileName = [[[task currentRequest] URL] lastPathComponent];
    
    
    if (!error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            
            
            if([task.taskDescription isEqualToString:@"upload"])
            {
                NSDictionary *dictionary = [NSDictionary dictionaryWithObjects:@[fileName,[NSNumber numberWithDouble:(double)task.countOfBytesSent],[NSNumber numberWithDouble:(double)task.countOfBytesExpectedToSend],[NSNumber numberWithBool:YES]] forKeys:@[kFileName,kFileTotalBytesSent,kFileTotalBytesExpectedToSend,kISFileTaskComplete]];
                
                [[NSNotificationCenter defaultCenter] postNotificationName:kS3TransferUploadNotificationKey object:nil userInfo:dictionary];
                
                NSLog(@"S3 UploadTask: %@ completed successfully", task);
            }
            else
            {
                NSDictionary *dictionary = [NSDictionary dictionaryWithObjects:@[fileName,[NSNumber numberWithDouble:(double)task.countOfBytesReceived],[NSNumber numberWithDouble:(double)task.countOfBytesExpectedToReceive],[NSNumber numberWithBool:YES]] forKeys:@[kFileName,kFileTotalBytesWritten,kFileTotalBytesExpectedToWrite,kISFileTaskComplete]];
                
                [[NSNotificationCenter defaultCenter] postNotificationName:kS3TransferDownloadNotificationKey object:nil userInfo:dictionary];
                
                NSLog(@"S3 DownloadTask: %@ completed successfully", task);
            }
            
            
            
        });
        
        
    }else {
        dispatch_async(dispatch_get_main_queue(), ^{
            
            if([task.taskDescription isEqualToString:@"upload"])
            {
                NSDictionary *dictionary = [NSDictionary dictionaryWithObjects:@[fileName,[NSNumber numberWithDouble:(double)task.countOfBytesSent],[NSNumber numberWithDouble:(double)task.countOfBytesExpectedToSend],[NSNumber numberWithBool:NO]] forKeys:@[kFileName,kFileTotalBytesSent,kFileTotalBytesExpectedToSend,kISFileTaskComplete]];
                
                [[NSNotificationCenter defaultCenter] postNotificationName:kS3TransferUploadNotificationKey object:error userInfo:dictionary];
                
                NSLog(@"S3 Upload Task: %@ completed with error: %@", task, [error localizedDescription]);
            }
            else
            {
                NSDictionary *dictionary = [NSDictionary dictionaryWithObjects:@[fileName,[NSNumber numberWithDouble:(double)task.countOfBytesReceived],[NSNumber numberWithDouble:(double)task.countOfBytesExpectedToReceive],[NSNumber numberWithBool:NO]] forKeys:@[kFileName,kFileTotalBytesWritten,kFileTotalBytesExpectedToWrite,kISFileTaskComplete]];
                
                [[NSNotificationCenter defaultCenter] postNotificationName:kS3TransferDownloadNotificationKey object:error userInfo:dictionary];
                
                NSLog(@"S3 Download Task: %@ completed with error: %@", task, [error localizedDescription]);
            }
            
            
        });
    }
    
    task = nil;
}

- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession *)session {
    
    CLBizManager *bizManager = [CLBizManager sharedManager];
    
    if ([session.sessionDescription isEqualToString:@"upload"]) {
        
        if (bizManager.backgroundUploadSessionCompletionHandler)
        {
            void (^completionHandler)() = bizManager.backgroundUploadSessionCompletionHandler;
            
            bizManager.backgroundUploadSessionCompletionHandler = nil;
            
            completionHandler();
        }
        
        NSLog(@"Completion Handler has been invoked, background upload task has finished.");
        
    }
    else
    {
        
        if (bizManager.backgroundDownloadSessionCompletionHandler)
        {
            void (^completionHandler)() = bizManager.backgroundDownloadSessionCompletionHandler;
            
            bizManager.backgroundDownloadSessionCompletionHandler = nil;
            
            completionHandler();
        }
        
        NSLog(@"Completion Handler has been invoked, background download task has finished.");
        
    }
    
}

//CODE Snippet END

**Comment by vickyrappier** [comment]
Hi Team,

Any help on this.

**Comment by yosuke-matsuda** [comment]
You seem to be able to generate the Amazon S3 pre-signed URL correctly, but having issues with Apple's APIs. You should refer to Apple's documentation for more details. Here is a couple of them that may help you:

- [Networking Overview](https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/Introduction/Introduction.html)
- [Networking with NSURLSession](https://developer.apple.com/videos/play/wwdc2015-711/)

**Comment by vickyrappier** [comment]
Thanks for the help. We sorted this by setting transport security in plist.

On Wednesday, 11 November 2015, Yosuke Matsuda <notifications@github.com>
wrote:

> You seem to be able to generate the Amazon S3 pre-signed URL correctly,
> but having issues with Apple's APIs. You should refer to Apple's
> documentation for more details. Here is a couple of them that may help you:
>
>    - Networking Overview
>    <https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/Introduction/Introduction.html>
>    - Networking with NSURLSession
>    <https://developer.apple.com/videos/play/wwdc2015-711/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-ios-samples/issues/25#issuecomment-155622631>
> .
>


-- 
Sent from my iPhone
