### ISSUE TITLE
How to retrieve an item from a table, then pass it to be the numberOfItemsInSection (AWS DynamoDB Swift 4)?

### ISSUE THREAD

**Issue by Vincent-St** [awslabs/aws-sdk-ios-samples#250]
I'm trying to retrieve an item from a table (TheUserIds2018) of Amazon DynamoDB, and I would like to pass the item to be the numberOfItemsInSection of the UICollectionViewCell, here is the table TheUserIds2018 looks like:

<img width="325" alt="screen shot 2018-03-14 at 00 48 57" src="https://user-images.githubusercontent.com/12606544/37358153-50d9bbde-2725-11e8-8200-27f199f067e6.png">

Here are the codes:

```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)

    let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        dynamoDbObjectMapper.load(TheUserIds2018.self, hashKey: "TheUserIds2018", rangeKey: nil, completionHandler: { (objectModel: AWSDynamoDBObjectModel?, error: Error?) -> Void in
            if let error = error {
                print("Amazon DynamoDB Read Error: \(error)")
                return
            }

            DispatchQueue.main.async {
                if let count = objectModel?.dictionaryValue["_articleCounters"] {
                    self.counters = count as! Int
                }
            }
        })

}


 override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
            return self.counters
}
```

But there is no collectionViewCell displaying in the screen when I build and run the app, it's blank:

<img width="577" alt="screen shot 2018-03-14 at 00 58 32" src="https://user-images.githubusercontent.com/12606544/37358248-91f920a0-2725-11e8-8997-43c9b47a1737.png">

I know the reason is that the collectionViewCell launches before than viewWillAppear. So I tried the following way, but sometimes it will crash (with the error: `Thread 1: Fatal error: Index out of range`):

```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)

    let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        dynamoDbObjectMapper.load(TheUserIds2018.self, hashKey: "TheUserIds2018", rangeKey: nil, completionHandler: { (objectModel: AWSDynamoDBObjectModel?, error: Error?) -> Void in
            if let error = error {
                print("Amazon DynamoDB Read Error: \(error)")
                return
            }

            DispatchQueue.main.async {
                if let count = objectModel?.dictionaryValue["_articleCounters"] {
                    self.counters = count as! Int
                }
            }
        })

}

func getItems() {
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        var tasksList = Array<AWSTask<AnyObject>>()
        for i in 1...10 {
            tasksList.append(dynamoDbObjectMapper.load(RecommendArticles.self, hashKey: "userId" + String(11 - i), rangeKey: nil))
        }

        AWSTask<AnyObject>.init(forCompletionOfAllTasksWithResults: tasksList).continueWith { (task) -> Any? in
            if let cards = task.result as? [RecommendArticles] {
                    self.card = cards
                    print("cards counter: \(cards.count)")

            } else if let error = task.error {
                print(error.localizedDescription)
            }

            return nil

        }


    }

    func updateItems() {
        let dynamoDbObjectMapper = AWSDynamoDBObjectMapper.default()
        var tasksList = Array<AWSTask<AnyObject>>()
            for i in 1...self.counters {
                tasksList.append(dynamoDbObjectMapper.load(RecommendArticles.self, hashKey: "userId" + String(self.counters + 1 - i), rangeKey: nil))
            }
            AWSTask<AnyObject>.init(forCompletionOfAllTasksWithResults: tasksList).continueWith { (task) -> Any? in
                if let cards = task.result as? [RecommendArticles] {
                        self.card = cards
                        print("Real cards counter: \(cards.count)")

                } else if let error = task.error {
                    print(error.localizedDescription)
                }

                return nil

            }

    }



 override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {

        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: verticalCellId, for: indexPath) as! VerticalCellId

        if let link = self.card?[indexPath.item]._imageURL {
            let url = URL(string: link)
            cell.photoImageView.kf.setImage(with: url)

        }

    }
```

PS: There are two different tables in my AWS DynamoDB: TheUserIds2018 and RecommendArticles. Here is what the RecommendArticles looks like:

<img width="855" alt="screen shot 2018-03-14 at 01 10 22" src="https://user-images.githubusercontent.com/12606544/37358311-b9cbae40-2725-11e8-86c4-d267083fd047.png">

Any other way to retrieve the item from the table (TheUserIds2018), and then pass it to be the numberOfItemsInSection? Thanks.

**Comment by rohandubal** [comment]
Hello,

You would have to call the `reloadData` method of the `UITableViewController` to refresh the data in the table and view controller. You can find the documentation on `reloadData` [here.](https://developer.apple.com/documentation/uikit/uitableview/1614862-reloaddata)

Some general best practices would be:
- Have a var array on view controller level to store all the items retrieved from dynamoDB(initialize to an empty list)
- Use list.size for the items in section
- Once you load the items from dynamodb, put them in the above list and call `reloadData`

Thanks,
Rohan

**Comment by Vincent-St** [comment]
@rohandubal Thanks, man. After adding `self.collectionView?.reloadDate()` to main thread, it works well in most cases, but it sometimes crashes if try to scroll down immediately after the app launches, especially when in a bad internet connection. Same error: `Thread 1: Fatal error: Index out of range`. Here is the card I set up in the UICollectionViewController:

```
class RecentsViewController: UICollectionViewController, UICollectionViewDelegateFlowLayout, SFSafariViewControllerDelegate {

var card: [RecommendArticles]?
var counters: Int = 0

}

```

Any ideas you can share with me? Thanks.

**Comment by Vincent-St** [comment]
Never mind, I just figured it out with the help of StackOverflow. Please take a look at [this thread,](https://stackoverflow.com/questions/49262048/retrieve-an-item-from-a-table-of-amazon-dynamodb-then-pass-it-to-be-the-numbero) if anyone else has the same issue.
