### ISSUE TITLE
Cannot find executable for CFBundle ... AWSAuthUI.bundle

### ISSUE THREAD

**Issue by nomad3k** [awslabs/aws-sdk-ios-samples#251]
Following the examples laid out (below) I'm getting an error when attempting to login to AWS Cognito.  This issue seems similar to #246 but I'm using Cognito, not Google.  For info, I'm using eu-west-1.  I've found in the past some of the samples seem to be fixed to us-east-1.

Example:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/getting-started.html
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html

Error:
```
2018-03-14 17:48:43:873 PropertyLife[32953:354651] didFinishLaunching:withOptions:resumeSessionWithCompletionHandler:
2018-03-14 17:48:43:882 PropertyLife[32953:354651] Resuming any previously signed-in session
2018-03-14 17:48:43.959737+0000 PropertyLife[32953:354651] Cannot find executable for CFBundle 0x7fa3489194e0 </Users/chris/Library/Developer/CoreSimulator/Devices/34C23101-6A34-464D-8361-7923659EE079/data/Containers/Bundle/Application/2D2F4AF1-5D29-4327-A3EF-5BA4F56A5764/PropertyLife.app/Frameworks/AWSAuthUI.framework/AWSAuthUI.bundle> (not loaded)
```

**Comment by kvasukib** [comment]
Thank you @nomad3k for reporting to us. Sorry for the inconvenience caused. Can you click **iOS Simulator > Reset Content and Settings** and restart the simulator to see if it solves the problem?

**Comment by alpriest** [comment]
I followed the instructions in those steps and have the same problem. I've created a brand new Xcode project and integrated AWSMobileClient with cocoapods (1.4.0). The following is the output from a pod install

```
Using AWSAuthCore (2.6.13)
Using AWSAuthUI (2.6.13)
Using AWSCognitoIdentityProvider (2.6.13)
Using AWSCognitoIdentityProviderASF (1.0.1)
Using AWSCore (2.6.13)
Using AWSMobileClient (2.6.13)
Using AWSUserPoolsSignIn (2.6.13)

```
When I run the app I see

```
2018-03-21 12:10:13:014 AWS_Test[375:61385] didFinishLaunching:withOptions:resumeSessionWithCompletionHandler:
2018-03-21 12:10:13:021 AWS_Test[375:61385] Resuming any previously signed-in session
2018-03-21 12:10:13.055940+0000 AWS_Test[375:61385] Cannot find executable for CFBundle 0x106006c60 </var/containers/Bundle/Application/088FAF9C-9E82-4919-A2FC-FAAC2C6B2791/AWS_Test.app/Frameworks/AWSAuthUI.framework/AWSAuthUI.bundle> (not loaded)
2018-03-21 12:10:13:318 AWS_Test[375:61385] Welcome to AWS! You are connected successfully.
2018-03-21 12:10:13:319 AWS_Test[375:61385] result = {
AWSCredentials
AccessKey: <DATA>
SecretKey: <DATA>
SessionKey: <DATA>
```

I then present the `AWSAuthUIViewController` and I see a view with "Sign In", the AWS orange blocks, but no login options. This happens on simulator and device, tested with iOS 10.x and 11.x.

**Comment by alpriest** [comment]
I've managed to resolve my problem detailed above. I'd not enabled any login methods on my Mobile Hub configuration. Whilst I still see the warning message about the bundle, I do now see the login email/password fields.

It'd be great to see a warning message in the debug log if you attempt to present the Auth without having first enabled any auth providers.

**Comment by kvasukib** [comment]
Thank you @alpriest for the analysis. As you correctly pointed out, the AWSMobileClient reads in `awsconfiguration.json` and automatically registers the auth providers with the AWSSignInManager (AWSAuthCore). When you use `AWSAuthUIViewController`, it adds the respective UI components for the auth providers based on the existence of the auth providers in the `awsconfiguration.json` file. Thank you for your suggestion. We will add the appropriate debug/log messages when you present the Auth UI without any providers. Regarding the warning for not loading `AuthUI.bundle`, we are still looking into it.

**Comment by ykbryan** [comment]
+1 to this issue. I’m facing the same issue too.

**Comment by xiafangmo** [comment]
save issue.

**Comment by obird-rive** [comment]
I also encountered the same phenomenon.
After that I solved it myself. The reason is that the project name specified in Info.plist was incorrect. I think that it may be checked as one of the possibilities.

**Comment by clsource** [comment]
The solution for me was to add a Navigation Controller in the Storyboard to the View Controller that calls the AuthUI

`[AWSAuthUIViewController presentViewControllerWithNavigationController:self.navigationController`

**Comment by nomad3k** [comment]
Sorry, I don’t know.  I don’t use this any more.

**Comment by PaulHorenberger** [comment]
This is still an issue. The problem appears to stem from the method` [AWSSignInViewController getImageFromBundle]` unnecessarily appending "AWSAuthUI.bundle" to the path of the framework in order to find the SignIn storyboard. I've rebuilt the AWSAuthUI framework without the call to ` [[currentBundle resourceURL] URLByAppendingPathComponent:RESOURCES_BUNDLE];` and it does not throw an exception.

**Comment by rohandubal** [comment]
Thanks for pointing out the fix @PaulHorenberger 

Would you be OK to publish a PR on the aws-sdk-ios repository? We can roll it out in one of the future release if the changes the look good.

Thanks,
Rohan

**Comment by umair-ali-confiz** [comment]
Unable to load AWSAuthUI component from  bundle, following error showing on console:

2018-09-11 16:25:14.519931+0500 AwsLogin[12745:259621] Cannot find executable for CFBundle 0x7fbbe8403370 </Users/umairali/Library/Developer/CoreSimulator/Devices/7A529309-BCF4-482B-ADFD-AB95AC4B2169/data/Containers/Bundle/Application/AEB4BC97-4951-4EE4-AE2F-084FBBD79399/AwsLogin.app/Frameworks/AWSAuthUI.framework/AWSAuthUI.bundle> (not loaded)

**Comment by umair-ali-confiz** [comment]
@rohandubal Issue still exist in AWSAuthUI. Please help me in this regard.

**Comment by adimona** [comment]
I had the same issue and here is how I solved my problem.
I went to Mobile Hub, clicked on my project, clicked integrate then downloaded Config json file and replaced it with the current one in my Xcode project (the one I previously made using amplify init).

**Comment by desokroshan** [comment]
This issue is being tracked as [SDK Issue#1107](https://github.com/aws-amplify/aws-sdk-ios/issues/1107)
