### ISSUE TITLE
com.amazonaws.AWSCognitoIdentityErrorDomain error 10

### ISSUE THREAD

**Issue by amit2908** [awslabs/aws-sdk-ios-samples#259]
While creating identity in AWS Identity Pool I am getting the error described in the title. Can anybody help and let me know what is the meaning of this error code 10 and why is it supposed to come?

`credentialsProvider?.credentials().continueWith(block: { (task) -> Any? in
            if task.isFaulted {
                print("Credential task failed with error: ",task.error?.localizedDescription ?? "")
            }else if task.isCompleted {
                print("Credentials retrivel success")
             }
             return nil
        })`

**Comment by kvasukib** [comment]
Thank you @amit2908 for reporting to us. Can you provide the error message and the stack trace for further debugging?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
