### ISSUE TITLE
Major problems with SDK code samples for Swift 2.0 / Xcode 7

### ISSUE THREAD

**Issue by petegrif** [awslabs/aws-sdk-ios-samples#26]
I am not going to list all the problems I've had and continue to have with the Swift code samples, but basically I would have thought that given that Swift 2 is now Swift and that XCode 7 is now XCode that code samples in Swift should compile under Xcode 7 and run successfully.  Right now - they don't, even when converted to Swift 2.0.

I have been watching the Issues people have been having and your responses and there are all sorts of crazy 'fixes' like compiling with bitcode off etc, hack plist etc, but this shouldn't be necessary. Call me old fashioned but surely code samples for a major OS in a language the vendor is clearly committed to and that is growing like crazy should just work.  Right now is just a painful time suck.

Maybe I have missed something, maybe there are working code samples out there and I've not found them, and if so I apologize, but if not can you please let me know when we can expect updated SDK and associated code samples that work reliably for todays iOS environment/Swift?  Thanks.  :)

**Comment by yosuke-matsuda** [comment]
The code sample is currently not compatible with Xcode 7/Swift 2. When we update the samples, we'll update the thread. Thanks.

**Comment by petegrif** [comment]
Thanks for getting back to me.  So the question remains - when is that
likely to be?

**Comment by opswhisperer** [comment]
+1

**Comment by andypease** [comment]
+1

**Comment by yosuke-matsuda** [comment]
We've updated the samples. Thanks.

**Comment by petegrif** [comment]
Thats great. Thanks. Will check them out right away. :)

**Comment by petegrif** [comment]
Good job guys. Much appreciated.
