### ISSUE TITLE
Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=1 "(null)"

### ISSUE THREAD

**Issue by hemantkadamata** [awslabs/aws-sdk-ios-samples#260]
I'm using iOS 10, Swift 4, Xcode 9.3 to run the S3TransferUtilitySampleSwift app. I have registered the AWSCognitoCredentialsProvider in Appdelegate

However, when I try to download a zip file given the bucket and key, I get the following error:

Error Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=1 "(null)" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Content-Type=application/xml, Date=Thu, 05 Apr 2018 02:36:02 GMT, x-amz-request-id=3E09D6D2C0CFCDC2, x-amz-id-2=irhstApYymSQ6aPyPDcRblYGd1NPD+vUUjADnOyy/BGbvAnnd7+9DQb1Zc6vUF1ucBRX/8HkM7A=, x-amz-bucket-region=ap-southeast-1}

Any ideas on why this is happening? Thanks in advance!

**Comment by minbi** [comment]
Hi @hemantkadamata ,

Can you share a code snippet that can reproduce this problem?
Does this only occur when using Swift 4? The sample is written in Swift 3.

**Comment by cbommas** [comment]
hello @hemantkadamata 

Error code 1 in the AWSS3TransferUtilityErrorDomain indicates that the server sent back a redirect response (either a 301 or a 307) to the download request. A common scenario where I have encountered this error is if you have setup transfer acceleration on your bucket and haven't set the isAcceleratedModeEnabled to true in the TransferUtilityConfiguration. 

As requested by @minbi, can you share your code snippet and details about how your bucket is setup to help in debugging this further?

**Comment by hemantkadamata** [comment]
This is my function 

in app delegate i have written the following 

 let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .APSoutheast1, identityPoolId: Constants.AWSConstants.AWS_IDENTITY_POOL_ID)
        let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        

in my view controller 
func downloadData() {
        
        let expression = AWSS3TransferUtilityDownloadExpression()
        expression.progressBlock = {(task, progress) in DispatchQueue.main.async(execute: {
            self.progressView.progress = Float(progress.fractionCompleted)
        })
        }
        
        var completionHandler: AWSS3TransferUtilityDownloadCompletionHandlerBlock?
        completionHandler = { (task, location, data, error) -> Void in
            DispatchQueue.main.async(execute: {
                if let error = error {
                    NSLog("Failed with error: \(error.infoMessage)  -- \n \(error.localizedDescription) --- \n \(error)")
                }
                else if(self.progressView.progress != 1.0) {
                    NSLog("Error: Failed.")
                } else {
                    NSLog("Success.")
                    var fileName: String = ""
                    do {
                        try fileName = (data?.write(to: self.getDocumentsDirectory(), options: .atomic) as! String?)!
                    } catch {
                        print(error)
                    }
                    FileOperations.sharedInstance.unZipFile(fileName: fileName ,fileType: ".zip", unZipFileLocation: self.getDocumentsDirectory().path)
                    
                    self.render()
                }
            })
        }
        
        let transferUtility = AWSS3TransferUtility.default()
        
        
        
        transferUtility.downloadData(
            fromBucket: Constants.AWSConstants.S3_BUCKET_NAME,
            key: "256b2b62-3266-11e8-b467-0ed5f89f718b/UnifiedAvataar/Test-MB127/256b2b62-3266-11e8-b467-0ed5f89f718b.zip", //Constants.AWSConstants.S3_DOWNLOAD_KEY_NAME,
            expression: expression,
            completionHandler: completionHandler
            ).continueWith {
                (task) -> AnyObject! in if let error = task.error {
                    print("Error: \(error.localizedDescription)")
                }
                
                if let _ = task.result {
                    // Do something with downloadTask.
                    
                }
                return nil;
        }
    }

**Comment by cbommas** [comment]
hello @hemantkadamata 

Thank you for sharing the code snippet. We will need you to make one more change to help debug this further. The latest version of the SDK, 2.6.18, contains logic to propagate additional diagnostic information (thanks to PR #666 submitted by @k4ety ). Can you upgrade to the latest and send me the details of the error?

See below for a code snippet on how to get the error information

    let errorInfo = err.userInfo["Error"] as? [String: Any]
    if errorInfo != nil {
        print("Found error in response. Details are:")
        for element in errorInfo! {
            print(">> \(element.key): \(element.value)")
        }
   }

**Comment by cbommas** [comment]
@hemantkadamata 

Closing this issue as I haven't heard back. Please feel free to reopen if you are still having issues.
