### ISSUE TITLE
How to display images and texts (which retrieved from AWS Dynamodb) dynamically using logics with Swift?

### ISSUE THREAD

**Issue by Vincent-St** [awslabs/aws-sdk-ios-samples#262]
I'm trying to build a sample app (using Swift 4), now I would like to add a function: To display images and labels dynamically.

For example: **sometimes, I would like to display an image in the top of a ViewController**, just like the following picture shows:

<img width="419" alt="screen shot 2018-04-09 at 00 47 52" src="https://user-images.githubusercontent.com/12606544/38470156-5cdc688e-3b91-11e8-8cf0-247e4555991e.png">

**But sometimes, I would like the display the image in the bottom of the Summary label, or some other positions**.

Is there any way to make it happen? And the most important is: There is no way to modify the codes, once the app submitted to App Store. So, the logic may be implemented from internet (AWS Dynamodb, or AWS Lamba)? I'm not sure about this. Thanks.

**Comment by froggomad** [comment]
This is fairly easy to do by instantiating a UIImageview in a different location based on whatever variable there may be

**Comment by Vincent-St** [comment]
Thanks, @froggomad . But how to instantiate an UIImageview in a different location, when the app submitted to App Store? Where are the logics? Local or remote server?

**Comment by froggomad** [comment]
@Vincent-St I misunderstood - you would need to update your app to do what I'm saying. I know you can run Swift server-side, but I wouldn't think it possible to modify your frontend code with a backend script.

**Comment by Vincent-St** [comment]
OK, thanks anyway, @froggomad. I was not sure about this before, that's why I opened the issue to see if it's possible.

**Comment by minbi** [comment]
There are no SDK fixes for this issue. Closing.
