### ISSUE TITLE
transfer Utility problem with slash in Bucket Name

### ISSUE THREAD

**Issue by FahdSaif** [awslabs/aws-sdk-ios-samples#263]
Hi when I use the TransferManager and upload a .png file through IOS Swift4 in the following bucket e.g australiatest/testbucket works, however when i use the  Transfer Utility and send it to the same path, australiatest/testbucket, it dosent work, why?.

Interestingly I tried to upload to this path, australiatest, using Transfer Utility and to my surprise it worked. I think when I add a slash to the path,using Transfer Utility, it dosen't work, but this is not making sense to me. Can you please assist if there are any limitations to using a path like this australiatest/testbucket in Transfer Utility?

Kindly assist

**Comment by rohandubal** [comment]
Hello,

Could you please clarify couple things for me:

- What is the name of your bucket? 
    - australiatest or
    - australiatest/testbucket
- For the case in which `TransferUtility` works, does the data show up in the same bucket as transfer manager in a different folder?

Thanks,
Rohan

**Comment by FahdSaif** [comment]
Hi Rohan, Thanks for your response. I had a sub folder inside my bucket. The images were going inside the bucket but not in the subfolder, until i figured out that i can put the subfolder name with the filename and that did the trick. So it worked for me.

**Comment by rohandubal** [comment]
Great! Closing this issue. Please feel free to open a new issue if you encounter any other issue.
