### ISSUE TITLE
Cognito example - AmazonClientManager - problems with resumeSessionWithCompletionHandler

### ISSUE THREAD

**Issue by WhiteHexagon** [awslabs/aws-sdk-ios-samples#27]
I've tried two different providers, google and facebook. Both authenticate fine for a single use of the app, but neither wants to run a second time.

In the resumeSessionWithCompletionHandler method it calls the following methods, but each has it's own problem.
1. reloadFBSession

[FBSDKAccessToken currentAccessToken] always returns nil.  At first I thought the token was being lost, but I found if I add the following in my AppDelegate then the token is visible to that call.  I'm not sure if this is correct, or just a hack that might fail again later...
[[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
1. reloadGSession

For this one the trySilentAuthentication always returns NO.  Which again sounds like the token has been lost after initial authentication.  I'm also reading that this is not certain even to call the 'finishedWithAuth' method, which might be the next issue here.  But If I click the Login button again for google, then the token magically appears again, ie. without the round trip to Safari for the signin process.  Can anyone confirm this behavior is correct?  I dont really want to ask the user to press the login each time the app starts, and I cant really call it programmatically since I dont know if they even had a token previously (and since this returns NO that would indicate they dont).

My target is iOS 7.1 and using XCode 7

pod 'AWSCore', '2.2.0'
pod 'AWSCognito', '2.2.0'
pod 'AWSS3', '2.2.0'
pod 'AWSLambda',  '2.2.0'
pod 'UICKeyChainStore', '2.0.0'
pod 'googleplus-ios-sdk', '1.7.1'
pod 'Facebook-iOS-SDK', '4.0.1'

**Comment by behrooziAWS** [comment]
Do you see this behavior on a device or only in the simulator?

**Comment by behrooziAWS** [comment]
According to this document, adding that to the didFinishLaunchingWithOptions in the appdelegate is the correct thing to do for facebook, we will fix: https://developers.facebook.com/docs/ios/getting-started#delegate

For Google sign-in, I'm not sure I am seeing the same thing as you.  If I login with Google, kill the simulator, then launch it again with this modified reloadGSession:

- (void)reloadGSession
{
    GPPSignIn *signIn = [self getGPlusLogin];
    BOOL result = [signIn trySilentAuthentication];
    NSLog(@"GPPSignIn trySilentAuthentication: %@",result?@"YES":@"NO");
}

I see:

2015-10-12 22:21:47.449 CognitoSyncDemo[22650:5919358] GPPSignIn trySilentAuthentication: YES

Can you give me steps to repro the trySilentAuthentication returning NO?

**Comment by WhiteHexagon** [comment]
Thank you for the quick response and confirmation on the facebook change. 
 
On the google side of things I thought it might be a token based issue.  The auth I get back on initial login has an expiry that is the same as the current date time! or even 1 hour earlier.  As I tried switching timezones but I think maybe that timestamp is bogus, although I found some issues on the google plus side (958 & 981) that might be related. 
 
I had a name clash with GooglePlus which I fixed, and I had a GPPSignInButton which I removed.  Since I have been testing exclusively on device.  I tried in simulator and saw the same issue, but I tried a 'reset content and settings' and it now returns YES!

So on the device testing I tried a delete of the app without success (maybe it doesnt clear the keychains?).  But I also realised that the logout was not completing properly, since the 'Google' was in the keychain, but there was no auth.  ie 'isLoggedInWithGoogle' returns NO in this case.  

I went back to my original code, and tried a logout from there, which does a bit more such as unlinks with an anon provider and calls [signIn signOut] on the google side.  And after all of the above it finally seems to be working.  I suspect it was some kind of mismatched tokens, since my own code was previously requesting scope 'profile' and ACM requests slightly different scopes.

In my search though I did find a blog that implies this still might not be that reliable.

"If the user has already signed-in, the SDK stores a keychain entry for that, and (most of the time) calling trySilentAuthentication will fire the finishedWithAuth:error: call on the sign-in delegate in short-order."
http://www.riskcompletefailure.com/2013/06/common-issues-with-google-sign-in-on-ios.html

This can be closed.  Thanks for your help.

**Comment by WhiteHexagon** [comment]
PS I forgot to mention that I noticed the 'resumeSessionWithCompletionHandler' can call the 'completionHandler' more than once.  eg.  If I resume with google, and since the notification is asynchronous, first I see the completionHandler called (not logged in) and then a short while later it calls back from the CompleteGLogin with loggedIn true.  Probably this is intended behavior,  but maybe it needs a mention in the code base.

**Comment by chetanme** [comment]
Hi, thanks for pointing these problem out.

We will look into the resumeSessionWithCompletionHandler flow with Google and update sample app or docs if necessary.

**Comment by MadhavanPaulrajan** [comment]
Hi, am also facing the same problem with resumeSessionWithCompletionHandler in GPlus login. But the same resume session works fine for Facebook Login. Can u please help me on this. This is the code am using,

[[AmazonClientManager sharedInstance] googleLoginFromView:self withCompletionHandler:^id(AWSTask *task) {
    dispatch_async(dispatch_get_main_queue(), ^{
        [[AmazonClientManager sharedInstance] resumeSessionWithCompletionHandler:^id(AWSTask *task) {
            dispatch_async(dispatch_get_main_queue(), ^{
                // Dataset successfully refreshed
            });
            return nil;
        }];
        
    });
    return nil;
}];

It would be helpful for me if you have solution on this. Thanks..

**Comment by desokroshan** [comment]
Original issue has been resolved. Behavior pointed out by @WhiteHexagon is being tracked in [SDK Issue#1108](https://github.com/aws-amplify/aws-sdk-ios/issues/1108). 
@MadhavanPaulrajan Please open an issue in aws-amplify/aws-sdk-ios if you still need help.
