### ISSUE TITLE
CognitoAuth-Sample Conversion to latest Version

### ISSUE THREAD

**Issue by gunteefe** [awslabs/aws-sdk-ios-samples#270]
Hi there, I've used the code to get this to run however, it cant be used with the latest verson of xcode and swift.

Does anyone know how to upgrade the code, as it not converting to the latest version with out errors.

Apologies as Im fairly new to this.

Just need to get the sample working.

Thanks

**Comment by behrooziAWS** [comment]
@gunteefe Just confirming you are using 9.3.1 or some other version of Xcode?

**Comment by gunteefe** [comment]
Hi there, yes I've checked it is version 9.3.1

**Comment by desokroshan** [comment]
@gunteefe I was able to run the CognitoAuth-Sample successfully on Xcode version 9.3.1 as is without any changes. Are you getting build errors or runtime errors? Can you please share the errors that you are running into with Xcode version 9.3.1? Thanks.
