### ISSUE TITLE
Not work sign out function in AWSCognitoAuth.default()

### ISSUE THREAD

**Issue by Bhadresh4488** [awslabs/aws-sdk-ios-samples#272]
auth.signOut { (error:Error?) in
          if(error != nil){
               alertWithTitle("Error", message: (error! as NSError).userInfo["error"] as? String)
          }else {
            
            session = nil
            alertWithTitle("Info", message: "Session completed successfully")
        }
        self.refresh()
     }

I am use this method but can't successfully sign out
Click sing in button then open safari page & can't ask user name & password why?

**Comment by minbi** [comment]
Closing to track in aws/aws-sdk-ios#947
