### ISSUE TITLE
Invalid identity pool configuration

### ISSUE THREAD

**Issue by quanguyen** [awslabs/aws-sdk-ios-samples#274]
Hi,

Thanks for this great Amazon IoT Sample, which saves me a lot of time to dig through the API to find the process of connecting an AWS MQTT service.

In my project, I changed constants in `Constants.swift` in order to access MQTT service of my client, as following:

```
let AWSRegion = AWSRegionType.USWest2 // e.g. AWSRegionType.USEast1
let CognitoIdentityPoolId = "us-west-2:e95087f0-48a7-4732-b482-4614c7c63db6"
let CertificateSigningRequestCommonName = "MyApp"
let CertificateSigningRequestCountryName = "MyCountry"
let CertificateSigningRequestOrganizationName = "MyOrganization"
let CertificateSigningRequestOrganizationalUnitName = "MyUnit"
let PolicyName = "pubsub_policy"

// This is the endpoint in your AWS IoT console. eg: https://xxxxxxxxxx.iot.<region>.amazonaws.com

let IOT_ENDPOINT = "https://<endpoint>.amazonaws.com" // endpoint is entered correctly!
let ASWIoTDataManager = "MyIotDataManager"
```

But when I press `Connect`, the app throws this error:

> 2018-06-04 17:12:59:992 IoTSampleSwift[4999:2464150] Response body:
> {"__type":"InvalidIdentityPoolConfigurationException","message":"Invalid identity pool configuration. Check assigned IAM roles for this pool."}
> 2018-06-04 17:12:59:994 IoTSampleSwift[4999:2464150] GetCredentialsForIdentity failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=5 "(null)" UserInfo={__type=InvalidIdentityPoolConfigurationException, message=Invalid identity pool configuration. Check assigned IAM roles for this pool.}]
> 2018-06-04 17:12:59:995 IoTSampleSwift[4999:2464150] Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=5 "(null)" UserInfo={__type=InvalidIdentityPoolConfigurationException, message=Invalid identity pool configuration. Check assigned IAM roles for this pool.}]
> 2018-06-04 17:13:00:017 IoTSampleSwift[4999:2464150] error: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=5 "(null)" UserInfo={__type=InvalidIdentityPoolConfigurationException, message=Invalid identity pool configuration. Check assigned IAM roles for this pool.}

- Is there something wrong with my parameters in `Constants.swift`? 
- Is there something to enable at my client's service so I can access?
- According to 10): p12 file: if available, then I don't have to create keys and certificates dynamically every time I need to access this MQTT service? But my client has to create it on his [Amazon AWS IoT Console][2] and gives me the certificate/key so I can generate this p12 file on my MAC?

Sorry, I have to ask these simple questions since I'm new to AWS IoT API.

Regards,

**Comment by rohandubal** [comment]
Hi, This is likely due to missing roles for your un-auth role in Cognito Federated Indentity console. You will have to assign a valid role for the un-auth role.

**Comment by quanguyen** [comment]
@rohandubal 

Thanks for the reply. I also thought of some roles missing in Cognito Federated Identity console. But I also have an Android version which successfully connects using the parameters above:

```
private static final String CUSTOMER_SPECIFIC_ENDPOINT = "a22i2y89l436o4.iot.us-west-2.amazonaws.com";
// Cognito pool ID. For this app, pool needs to be unauthenticated pool with
// AWS IoT permissions.
//private static final String COGNITO_POOL_ID = "us-west-2:3e78bed9-9fea-4ab8-aeee-4cd931afd6ae";
private static final String COGNITO_POOL_ID = "us-west-2:3e78bed9-9fea-4ab8-aeee-4cd931afd6ae";
// Name of the AWS IoT policy to attach to a newly created certificate
private static final String AWS_IOT_POLICY_NAME = "pubsub_policy";
```

Is there any more settings I could ask my clients to check?

Regards
