### ISSUE TITLE
Why is there no example to send SMS message in docs?

### ISSUE THREAD

**Issue by mayankntreepies** [awslabs/aws-sdk-ios-samples#277]
https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html
This page only has example to send message if you are using java sdk. Can someone please translate this to swift

**Comment by rohandubal** [comment]
Are you trying to use this from iOS SDK? You can refer the API reference for publish here: http://aws.github.io/aws-sdk-ios/docs/reference//Classes/AWSSNS.html#//api/name/publish:

**Comment by mayankntreepies** [comment]
Thank you for pointing me out docs but I couldn't find the same.
how do we initialise SNS client using access key and secret key using swift in iOS?
what is the equivalent of 
`        AmazonSNSClient snsClient = new AmazonSNSClient(new BasicAWSCredentials("ACCESS KEY", "SECRET KEY"));
`
in swift iOS?
