### ISSUE TITLE
How to remove stored keychain details from amazon iOS cognito SDK

### ISSUE THREAD

**Issue by khetiSubrat** [awslabs/aws-sdk-ios-samples#279]
I am using https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample to implement sign-in and sign-out using AWS iOS SDK. I have signout button inside my app, on clicking sign out I need to clear the keychain details instead of calling signout block and showing safariviewcontroller. Is there any way to do so? I could see the only way to that using signout block but I don't want same.
The only solution I can see i.e 

```
[cognitoAuth signOut:self completion:^(NSError * _Nullable error) {
        if(error){
            NSLog(@"Error: %@", error.userInfo[@"error"]);
        }else {
            //User successfully signed out
            NSLog(@"User signed out");        
        }
    }];
```

But, don't want to call the signout block and showing a SafariViewController.

**Comment by kvasukib** [comment]
Thank you @khetiSubrat for reporting to us. Sorry for the inconvenience caused. Have you tried the signOut method without the view controller? https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoAuth/AWSCognitoAuth.m#L341

There is a method signOutLocally which is not public, but you could take a look at the implementation here: https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoAuth/AWSCognitoAuth.m#L379

```
if([self currentUsername]){
        NSArray *keys = self.keychain.allKeys;
        NSString *keyChainPrefix = [[self keyChainNamespaceClientId:[self currentUsername]] stringByAppendingString:@"."];
        for (NSString *key in keys) {
            //clear tokens associated with this user
            if([key hasPrefix:keyChainPrefix]){
                [self.keychain removeItemForKey:key];
            }
        }
}
```

It clears the user session from the keychain. Is there a use-case where you want to only clear session from keychain?

**Comment by dwsolberg** [comment]
@kvasukib On a shared device, when a user deletes the app and then later a different user installs the app again, the tokens stored in the iOS keychain persist, which means that the new user automatically is signed in as the prior user. I think users expect that deleting the app will also remove their user information. 

Would it be possible to expose the `signOutLocally` method in the public API so that we could check for a fresh app install?

**Comment by khetiSubrat** [comment]
Hi @kvasukib, @rohandubal , Signout method can do the things, but it will show a signout safari view controller which we don't want and do the things silently. It would be good if we have an public API to do the same.

Thanks

**Comment by dwsolberg** [comment]
@rohandubal Thanks for responding! We normally use the `signout` method you specified. However, there are two issues we've encountered:

1. Sometimes the user does not have network access, but we still need to delete the tokens from their device.
2. There are times when showing a view controller to sign out is a bad user experience.

My original comment details a scenario where both the above issues apply. For example, on a shared device (used in medical settings), if a previous user deleted the app, and a new user installed the app, they might be surprised to find out that the app opens to a logout screen on first launch. If they have no network access, they would also be surprised to learn that logging out failed.

**Comment by kvasukib** [comment]
@dwsolberg  Thank you for the reply. Does exposing `signOutLocallyAndClearLastKnownUser` and `signOutLocally` solve your use-cases?

**Comment by dwsolberg** [comment]
For our purposes, just exposing `signOutLocallyAndClearLastKnownUser` would be perfect because we'd always want to clear the last user when signing out.

**Comment by kvasukib** [comment]
Thank you @dwsolberg for the quick reply. I will get back to you on this shortly.
