### ISSUE TITLE
LEX's voice button does not have AWSLexInteractionKit available for controlling the voice button delegates

### ISSUE THREAD

**Issue by ymisal** [awslabs/aws-sdk-ios-samples#280]
LEX's voice button does not have AWSLexInteractionKit available for controlling the voice button and setting the default session attribute like PIN etc.

We are integrating AWS LEX in our app which have the feature to set the PIN before invoking the voice skill (to authenticate with our bot) but currently there is no provision to set the PIN or manage session attribute or even we can not access the AWSLexInteractionKit object in our (voice view implemented) custom class for voice view. If we tried to create and assign the AWSLexInteractionKit delegates to voice button then the animation does not working.

Can anyone implemented like this or have solution for this? 
I really appreciate for your kind help.

Thank you

**Comment by rohandubal** [comment]
Hi @ymisal 

Currently we do not support customization like this in the button, you can copy the code in your application and make the necessary changes to fit your exact use case. I will take this as feature request to the team. 

Thanks,
Rohan
