### ISSUE TITLE
IoT sample swift  couldn't locate the awsconfiguration.json

### ISSUE THREAD

**Issue by morrislwt** [awslabs/aws-sdk-ios-samples#282]
Hello,

When I press the Connect button, debug area show this message,
how can I find the awsconfiguration.json file? 
thank you.

`2018-07-06 18:05:03:124 IoTSampleSwift[66776:5418689] Couldn't locate the awsconfiguration.json file. Skipping load of awsconfiguration.json.`

**Comment by minbi** [comment]
Hi @morrislwt ,

If you are setting your IoT endpoint and region; Cognito Identity pool and region; or Cognito Userpool client id, client secret, region in code (i.e. Swift code), then the json file is not necessary. The awsconfiguration.json file is a way to configure settings like the above mentioned.

**Comment by cbommas** [comment]
@morrislwt 

Closing this issue. Please feel free to reopen if you run into issues or have further questions.
