### ISSUE TITLE
Creating AWSLexVoiceButton Programmatically

### ISSUE THREAD

**Issue by aborem** [awslabs/aws-sdk-ios-samples#283]
I tried creating an AWSLexVoiceButton programmatically in Swift like
`let button = AWSLexVoiceButton()`
and tried positioning it in the center of the view but nothing is showing up (I know if is being positioned in the correct location since I set the background color to something easily identifiable).
Also please add customization for the button!

**Comment by kvasukib** [comment]
@aborem Sorry for the inconvenience caused. Can you post a code snippet for further debugging? Regarding the customization, currently, AWSLexVoiceButton supports changing the color: https://github.com/aws/aws-sdk-ios/blob/master/AWSLex/AWSLexVoiceButton.h#L114. Can you give a list of items you would like to see in customization?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
