### ISSUE TITLE
Cognito Auth Login without web view for getting token

### ISSUE THREAD

**Issue by evgzor** [awslabs/aws-sdk-ios-samples#284]
Is it possible to get cognito token by some request instead of oath2 Webview?

**Comment by minbi** [comment]
Hi @evgzor ,

You may check the Cognito Userpools [sample](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoYourUserPools-Sample) to sign-in users through native UI.

**Comment by evgzor** [comment]
@minbi it does not return token. Could u please point me how I can retrieve token by using Cognito User Pools?
