### ISSUE TITLE
Secrets Manager Service

### ISSUE THREAD

**Issue by fs-bonlook** [awslabs/aws-sdk-ios-samples#289]
I am trying to integrate Amazon Secrets Manager Service (without Cognito), in Swift.
My amazon account is set with all requirements. I am able to see my secrets keys in my amazon console.
But I am not able to find any doc about integration of this service in a Swift project. And I can't find any pod about secrets manager.
Do you have some tutorial or sample source code somewhere?
Could you give me some track to resolve my problem ?

thank you so much

**Comment by rohandubal** [comment]
Hello @fs-bonlook 

We currently do not support an SDK for Secrets Manager Service. I have added this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK.

Thanks,
Rohan

**Comment by fs-bonlook** [comment]
Hi rohandubal ,

thank you for your answer. 
Maybe I will try to use APIGateway to connect ASM service...

:)

**Comment by rohandubal** [comment]
Yes, that can be one of the approach you take.
