### ISSUE TITLE
Handle continue upload/download while in background & Low speed transfer than android SDK

### ISSUE THREAD

**Issue by vickyrappier** [awslabs/aws-sdk-ios-samples#29]
Hello Team,

I am developing app that needs to send/receive the media in chat while user press home. 

I have tried using the S3 background transfer but could not see the download continuing in the background when home button pressed.

Hence continued with the AWSTRansfermanager example as its more reliable way to handle the request.

Can anyone tell me as to how we can let the S3 continue the transfer while app being in background and not PAUSE as its currently doing.

PS: I've tried using the example code with my AWS settings and still face the same issue in the example provided for both mechanisms.

Also the upload and download are very slow in 3G and comparatively to WIFI. This is not that slow in android as its rapid fast comparing our app in android using Android AWS SDK.

Note that looking for earlier blogs for AWS the AWSS3Client was used that was able to do some tweaking in the network detection and bandwidth throttling but in this latest example this is not shown or possible.

Any immediate help & guidance is truly appreciated.

Thanks,
Vicky

**Comment by yosuke-matsuda** [comment]
I have confirmed the S3 Background Transfer sample (both Swift and Objective-C versions) kept downloading a file after the home button is pressed. Also, the iOS handles the background transfer, and the AWS Mobile SDK does not directly performs the download.

**Comment by vickyrappier** [comment]
Hello team,

Please check the logs below explaining that scenerio it paused, Ive
highlighted the areas and also you can check the timestamp of left side to
see when the app went into background and came in foreground the resumption
is happening.

Do I need to do any additional settings to make the transfer enabled. Just
to recall I am using a AWSTransfer manager and not S3 Background transfer as
it had issues.



2015-10-23 12:16:06.989 Closrr_DV3[1225:204029] TASK Progress
:<AWSS3TransferManagerUploadRequest: 0x12768afa0> {
    ACL = 0;
    body = 
"file:///var/mobile---Application/80----80F0FC9BFC/Documents/Closrr/Media/+6
598595499/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov";
    bucket = "closrr-media-dev";
    cacheIdentifier =
"56B6A88D-CBB9-4417-ADB6-0D522BE85E18-1225-00000149334313C7";
    completedPartsArray =     (
    );
    contentType = "video/quicktime";
    currentUploadingPartNumber = 0;
    expires = "2015-10-23 05:16:06 +0000";
    key = "1444293870a3----57acd6d6dd/VID-EF005D3E-BE1----62378840A1A4.mov";
    serverSideEncryption = 0;
    state = 1;
    storageClass = 0;
    totalSuccessfullySentPartsDataLength = 0;
}

//Transfer actually startes at '2015-10-23 12:16:10.342¹


2015-10-23 12:16:10.342 Closrr_DV3[1225:204175] Progress status : 0.001449
2015-10-23 12:16:10.448 Closrr_DV3[1225:204175] Progress status : 0.010137
2015-10-23 12:16:10.460 Closrr_DV3[1225:204327] Progress status : 0.011586
2015-10-23 12:16:10.462 Closrr_DV3[1225:204327] Progress status : 0.013038
2015-10-23 12:16:10.467 Closrr_DV3[1225:204175] Progress status : 0.014487
---trimmed logs

5-10-23 12:16:12.464 Closrr_DV3[1225:204175] Progress status : 0.218757
2015-10-23 12:16:12.474 Closrr_DV3[1225:204175] Progress status : 0.220205
2015-10-23 12:16:12.490 Closrr_DV3[1225:204175] Progress status : 0.221654
2015-10-23 12:16:12.505 Closrr_DV3[1225:204175] Progress status : 0.223103
2015-10-23 12:16:12.524 Closrr_DV3[1225:204175] Progress status : 0.224552
2015-10-23 12:16:12.536 Closrr_DV3[1225:204133] Progress status : 0.226000
2015-10-23 12:16:12.546 Closrr_DV3[1225:204133] Progress status : 0.227449
2015-10-23 12:16:12.553 Closrr_DV3[1225:204327] Progress status : 0.228898
2015-10-23 12:16:12.567 Closrr_DV3[1225:204175] Progress status : 0.230347
2015-10-23 12:16:12.587 Closrr_DV3[1225:204133] Progress status : 0.231795
2015-10-23 12:16:12.611 Closrr_DV3[1225:204133] Progress status : 0.232441
2015-10-23 12:16:12.614 Closrr_DV3[1225:204327] Progress status : 0.232441

2015-10-23 12:16:12.714 Closrr_DV3[1225:204029] INFO:App entered
background:-[CLAppDelegate applicationWillResignActive:]
//Here for few milliseconds the transfer continues

2015-10-23 12:16:12.953 Closrr_DV3[1225:204133] Progress status : 0.233889
2015-10-23 12:16:12.960 Closrr_DV3[1225:204327] Progress status : 0.235338
2015-10-23 12:16:12.964 Closrr_DV3[1225:204417] Progress status : 0.236787
2015-10-23 12:16:12.966 Closrr_DV3[1225:204133] Progress status : 0.238236
2015-10-23 12:16:12.968 Closrr_DV3[1225:204327] Progress status : 0.239684
2015-10-23 12:16:12.985 Closrr_DV3[1225:204133] Progress status : 0.241133
2015-10-23 12:16:12.998 Closrr_DV3[1225:204417] Progress status : 0.242582
2015-10-23 12:16:13.006 Closrr_DV3[1225:204417] Progress status : 0.244031
2015-10-23 12:16:13.037 Closrr_DV3[1225:204417] Progress status : 0.245479
2015-10-23 12:16:13.058 Closrr_DV3[1225:204327] Progress status : 0.246924
2015-10-23 12:16:13.059 Closrr_DV3[1225:204327] Progress status : 0.248377
2015-10-23 12:16:13.068 Closrr_DV3[1225:204327] Progress status : 0.249825
--trimmed logs

15-10-23 12:16:15.146 Closrr_DV3[1225:204416] Progress status : 0.383108
2015-10-23 12:16:15.157 Closrr_DV3[1225:204327] Progress status : 0.384556
2015-10-23 12:16:15.169 Closrr_DV3[1225:204327] Progress status : 0.386005
2015-10-23 12:16:15.193 Closrr_DV3[1225:204169] Progress status : 0.387454
2015-10-23 12:24:52.533 Closrr_DV3[1225:204175] Progress status : 0.388903

2015-10-23 12:24:52.557 Closrr_DV3[1225:205474] AWSiOSSDKv2 [Error]
AWSURLSessionManager.m line:260 | -[AWSURLSessionManager
URLSession:task:didCompleteWithError:] | Session task failed with error:
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."
UserInfo=0x1702e2f80 {NSUnderlyingError=0x1746525d0 "The operation couldn¹t
be completed. (kCFErrorDomainCFNetwork error -1001.)",
NSErrorFailingURLStringKey=https://s3-ap-southeast-1.amazonaws.com/-------29
3870a37013c8182d17dcf9d21657acd6d6dd/VID-EF005D3E-BE12-44B6-BA30-62378840A1A
4.mov?partNumber=2&uploadId=plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDw
QZWAJnu8sPBLCMBzlU.DhyqWZEs0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUp
uGVHZo68Vi5T0EYcsJNiKPuOLPV4JT8sSk4IlBmTQxSw0js-,
NSErrorFailingURLKey=https://s3-ap-southeast-1.amazonaws.com/closrr-media-de
v/1444293870a370----acd6d6dd/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov?pa
rtNumber=2&uploadId=plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8
sPBLCMBzlU.DhyqWZEs0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68
Vi5T0EYcsJNiKPuOLPV4JT8sSk4IlBmTQxSw0js-, NSLocalizedDescription=The request
timed out.}

-
2015-10-23 12:24:52.816 Closrr_DV3[1225:205474] Progress status : 0.390355
2015-10-23 12:24:52.819 Closrr_DV3[1225:204175] Progress status : 0.391804
2015-10-23 12:24:52.824 Closrr_DV3[1225:205474] Progress status : 0.393253
2015-10-23 12:24:52.829 Closrr_DV3[1225:205459] Progress status : 0.394701
2015-10-23 12:24:52.832 Closrr_DV3[1225:205474] Progress status : 0.396150
2015-10-23 12:24:52.850 Closrr_DV3[1225:205459] Progress status : 0.397599
2015-10-23 12:24:52.861 Closrr_DV3[1225:204175] Progress status : 0.399048
2015-10-23 12:24:52.867 Closrr_DV3[1225:204175] Progress status : 0.400496
2015-10-23 12:24:52.874 Closrr_DV3[1225:204175] Progress status : 0.401945
2015-10-23 12:24:52.884 Closrr_DV3[1225:204175] Progress status : 0.403394
2015-10-23 12:24:52.887 Closrr_DV3[1225:205474] Progress status : 0.404843
2015-10-23 12:24:52.903 Closrr_DV3[1225:204175] Progress status : 0.406291
2015-10-23 12:24:52.909 Closrr_DV3[1225:205474] Progress status : 0.407740
2015-10-23 12:24:52.922 Closrr_DV3[1225:205474] Progress status : 0.409189

--trimmed logs

-10-23 12:24:53.006 Closrr_DV3[1225:205474] Progress status : 0.428022
2015-10-23 12:24:53.012 Closrr_DV3[1225:205459] Progress status : 0.429471
2015-10-23 12:24:53.053 Closrr_DV3[1225:205474] Progress status : 0.439612


2015-10-23 12:24:53.063 Closrr_DV3[1225:204029] INFO:App entered
foreground:-[CLAppDelegate applicationDidBecomeActive:]

//App became active and transfer resumed than already should have
transferred  resume time 2015-10-23 12:24:53.066

2015-10-23 12:24:53.066 Closrr_DV3[1225:205474] Progress status : 0.441056
2015-10-23 12:24:53.066 Closrr_DV3[1225:204169] Progress status : 0.442509
2015-10-23 12:24:53.195 Closrr_DV3[1225:204175] Progress status : 0.456996

---trimmed logs


2015-10-23 12:25:01.058 Closrr_DV3[1225:205474] Progress status : 0.989968
2015-10-23 12:25:01.066 Closrr_DV3[1225:205474] Progress status : 0.991417
2015-10-23 12:25:01.094 Closrr_DV3[1225:205474] Progress status : 0.992865
2015-10-23 12:25:01.132 Closrr_DV3[1225:205528] Progress status : 0.994314

trimmed logs

2015-10-23 12:25:03.944 Closrr_DV3[1225:205528] Progress status : 1.152870
2015-10-23 12:25:03.953 Closrr_DV3[1225:205474] Progress status : 1.154319
2015-10-23 12:25:03.961 Closrr_DV3[1225:205528] Progress status : 1.155767
2015-10-23 12:25:03.968 Closrr_DV3[1225:205474] Progress status : 1.156466
2015-10-23 12:25:03.975 Closrr_DV3[1225:205475] Progress status : 1.156466
2015-10-23 12:25:04.187 Closrr_DV3[1225:205528] TASK Finished
:<AWSS3TransferManagerUploadRequest: 0x12768afa0> {
    ACL = 0;
    body = 
"file:///var/mobile/Containers/Data/Application/80F4F172-8C7C-4620-8710-9480
F0FC9BFC/Documents/Closrr/Media/+6598595499/VID-EF005D3E-BE12-44B6-BA30-6237
8840A1A4.mov";
    bucket = "closrr-media-dev";
    cacheIdentifier =
"56B6A88D-CBB9-4417-ADB6-0D522BE85E18-1225-00000149334313C7";
    completedPartsArray =     (
        "<AWSS3CompletedPart: 0x17483a8a0> {\n    ETag =
\"\\\"671ce9e5dac5ddbfe7fce16f8a31e8f0\\\"\";\n    partNumber = 1;\n}",
        "<AWSS3CompletedPart: 0x17062d1a0> {\n    ETag =
\"\\\"522f1a2d770529db96c166196bf7d3da\\\"\";\n    partNumber = 2;\n}",
        "<AWSS3CompletedPart: 0x174628ba0> {\n    ETag =
\"\\\"e1969011e1fdd555c6c7d4218ef10568\\\"\";\n    partNumber = 3;\n}",
        "<AWSS3CompletedPart: 0x17482b100> {\n    ETag =
\"\\\"e5c0a76232ea896af6ad1af9ef49e9bd\\\"\";\n    partNumber = 4;\n}",
        "<AWSS3CompletedPart: 0x174626720> {\n    ETag =
\"\\\"b8ba12eacf4a47025b56db197315199c\\\"\";\n    partNumber = 5;\n}"
    );
    contentType = "video/quicktime";
    currentUploadingPart = "<AWSS3UploadPartRequest: 0x1700f3c80> {\n
body = 
\"file:///private/var/mobile/Containers/Data/Application---99-6350B290968C\"
;\n    bucket = \"closrr-media-dev\";\n    contentLength = 1584248;\n    key
= \²1444293870a37013c8182d1----44B6-BA30-62378840A1A4.mov\";\n    partNumber
= 5;\n    uploadId =
\"plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8sPBLCMBzlU.DhyqWZE
s0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68Vi5T0EYcsJNiKPuOLP
V4JT8sSk4IlBmTQxSw0js-\";\n}";
    currentUploadingPartNumber = 6;
    expires = "2015-10-23 05:16:06 +0000";
    key = 
"1444293870a37013c8182d17dcf9d21657acd6d6dd/VID-EF005D3E-BE12-44B6-BA30-6237
8840A1A4.mov";
    serverSideEncryption = 0;
    state = 4;
    storageClass = 0;
    totalSuccessfullySentPartsDataLength = 22555768;
    uploadId = 
"plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8sPBLCMBzlU.DhyqWZEs
0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68Vi5T0EYcsJNiKPuOLPV
4JT8sSk4IlBmTQxSw0js-";
}

Summarising  12:16 transfer started and I went in background and transfer
resumes at 12:24 where as per your response it should have finished.

Thanks,
Regards,
Vicky S Dhas
From:  Yosuke Matsuda <notifications@github.com>
Reply-To:  awslabs/aws-sdk-ios-samples
<reply+00a9e1abb46b6406aacc901702988803f5b3aac621c0e06892cf000000011240f4179
2a169ce06b8144d@reply.github.com>
Date:  Friday, 23 October 2015 2:59 am
To:  awslabs/aws-sdk-ios-samples <aws-sdk-ios-samples@noreply.github.com>
Cc:  Vicky Dhas <vickydhas@rappier.com>
Subject:  Re: [aws-sdk-ios-samples] Handle continue upload/download while in
background & Low speed transfer than android SDK (#29)


I have confirmed the S3 Background Transfer sample (both Swift and
Objective-C versions) kept downloading a file after the home button is
pressed. Also, the iOS handles the background transfer, and the AWS Mobile
SDK does not directly performs the download.


Reply to this email directly or view it on GitHub
<https://github.com/awslabs/aws-sdk-ios-samples/issues/29#issuecomment-15032
3119> .

**Comment by vickyrappier** [comment]
Hi Team, 

Appreciate if I can get any reply to this. As logs mentioned above its having a paused state when the application move in background. The download/upload progresses for a few % when going in background and then pauses. Please try with big size file to get this issue replicated.

**Comment by vickyrappier** [comment]
Hello AWS team,

I checked and it's working in background transfer code however can you
please let me know how to enable this in transfer manager example.

Thanks,Vicky

On Friday, 23 October 2015, Vicky Dhas <vickydhas@rappier.com> wrote:

> Hello team,
>
> Please check the logs below explaining that scenerio it paused, Ive
> highlighted the areas and also you can check the timestamp of left side to
> see when the app went into background and came in foreground the resumption
> is happening.
>
> Do I need to do any additional settings to make the transfer enabled. Just
> to recall I am using a AWSTransfer manager and not S3 Background transfer
> as it had issues.
>
>
>
> *2015-10-23 12:16:06.989 *Closrr_DV3[1225:204029] TASK Progress
> :<AWSS3TransferManagerUploadRequest: 0x12768afa0> {
>     ACL = 0;
>     body =
> "file:///var/mobile---Application/80----80F0FC9BFC/Documents/Closrr/Media/+6598595499/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov";
>     bucket = "closrr-media-dev";
>     cacheIdentifier =
> "56B6A88D-CBB9-4417-ADB6-0D522BE85E18-1225-00000149334313C7";
>     completedPartsArray =     (
>     );
>     contentType = "video/quicktime";
>     currentUploadingPartNumber = 0;
>     expires = "2015-10-23 05:16:06 +0000";
>     key =
> "1444293870a3----57acd6d6dd/VID-EF005D3E-BE1----62378840A1A4.mov";
>     serverSideEncryption = 0;
>     state = 1;
>     storageClass = 0;
>     totalSuccessfullySentPartsDataLength = 0;
> }
>
> //Transfer actually startes at '*2015-10-23 12:16:10.342**’*
>
>
> *2015-10-23 12:16:10.342 Closrr_DV3[1225:204175] Progress status :
> 0.001449*
> *2015-10-23 12:16:10.448 *Closrr_DV3[1225:204175] Progress status :
> 0.010137
> 2015-10-23 12:16:10.460 Closrr_DV3[1225:204327] Progress status : 0.011586
> 2015-10-23 12:16:10.462 Closrr_DV3[1225:204327] Progress status : 0.013038
> 2015-10-23 12:16:10.467 Closrr_DV3[1225:204175] Progress status : 0.014487
> ---trimmed logs
>
> 5-10-23 12:16:12.464 Closrr_DV3[1225:204175] Progress status : 0.218757
> 2015-10-23 12:16:12.474 Closrr_DV3[1225:204175] Progress status : 0.220205
> 2015-10-23 12:16:12.490 Closrr_DV3[1225:204175] Progress status : 0.221654
> 2015-10-23 12:16:12.505 Closrr_DV3[1225:204175] Progress status : 0.223103
> 2015-10-23 12:16:12.524 Closrr_DV3[1225:204175] Progress status : 0.224552
> 2015-10-23 12:16:12.536 Closrr_DV3[1225:204133] Progress status : 0.226000
> 2015-10-23 12:16:12.546 Closrr_DV3[1225:204133] Progress status : 0.227449
> 2015-10-23 12:16:12.553 Closrr_DV3[1225:204327] Progress status : 0.228898
> 2015-10-23 12:16:12.567 Closrr_DV3[1225:204175] Progress status : 0.230347
> 2015-10-23 12:16:12.587 Closrr_DV3[1225:204133] Progress status : 0.231795
> 2015-10-23 12:16:12.611 Closrr_DV3[1225:204133] Progress status : 0.232441
> 2015-10-23 12:16:12.614 Closrr_DV3[1225:204327] Progress status : 0.232441
>
> *2015-10-23 12:16:12.714 Closrr_DV3[1225:204029] INFO:App entered
> background:-[CLAppDelegate applicationWillResignActive:]*
> //Here for few milliseconds the transfer continues
>
> 2015-10-23 12:16:12.953 Closrr_DV3[1225:204133] Progress status : 0.233889
> 2015-10-23 12:16:12.960 Closrr_DV3[1225:204327] Progress status : 0.235338
> 2015-10-23 12:16:12.964 Closrr_DV3[1225:204417] Progress status : 0.236787
> 2015-10-23 12:16:12.966 Closrr_DV3[1225:204133] Progress status : 0.238236
> 2015-10-23 12:16:12.968 Closrr_DV3[1225:204327] Progress status : 0.239684
> 2015-10-23 12:16:12.985 Closrr_DV3[1225:204133] Progress status : 0.241133
> 2015-10-23 12:16:12.998 Closrr_DV3[1225:204417] Progress status : 0.242582
> 2015-10-23 12:16:13.006 Closrr_DV3[1225:204417] Progress status : 0.244031
> 2015-10-23 12:16:13.037 Closrr_DV3[1225:204417] Progress status : 0.245479
> 2015-10-23 12:16:13.058 Closrr_DV3[1225:204327] Progress status : 0.246924
> 2015-10-23 12:16:13.059 Closrr_DV3[1225:204327] Progress status : 0.248377
> 2015-10-23 12:16:13.068 Closrr_DV3[1225:204327] Progress status : 0.249825
> --trimmed logs
>
> 15-10-23 12:16:15.146 Closrr_DV3[1225:204416] Progress status : 0.383108
> 2015-10-23 12:16:15.157 Closrr_DV3[1225:204327] Progress status : 0.384556
> 2015-10-23 12:16:15.169 Closrr_DV3[1225:204327] Progress status : 0.386005
> 2015-10-23 12:16:15.193 Closrr_DV3[1225:204169] Progress status : 0.387454
> 2015-10-23 12:24:52.533 Closrr_DV3[1225:204175] Progress status : 0.388903
>
> 2015-10-23 12:24:52.557 Closrr_DV3[1225:205474] AWSiOSSDKv2 [Error]
> AWSURLSessionManager.m line:260 | -[AWSURLSessionManager
> URLSession:task:didCompleteWithError:] | Session task failed with error:
> Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."
> UserInfo=0x1702e2f80 {NSUnderlyingError=0x1746525d0 "The operation couldn’t
> be completed. (kCFErrorDomainCFNetwork error -1001.)",
> NSErrorFailingURLStringKey=
> https://s3-ap-southeast-1.amazonaws.com/-------293870a37013c8182d17dcf9d21657acd6d6dd/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov?partNumber=2&uploadId=plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8sPBLCMBzlU.DhyqWZEs0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68Vi5T0EYcsJNiKPuOLPV4JT8sSk4IlBmTQxSw0js-,
> NSErrorFailingURLKey=
> https://s3-ap-southeast-1.amazonaws.com/closrr-media-dev/1444293870a370----acd6d6dd/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov?partNumber=2&uploadId=plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8sPBLCMBzlU.DhyqWZEs0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68Vi5T0EYcsJNiKPuOLPV4JT8sSk4IlBmTQxSw0js-,
> NSLocalizedDescription=The request timed out.}
>
> -
> 2015-10-23 12:24:52.816 Closrr_DV3[1225:205474] Progress status : 0.390355
> 2015-10-23 12:24:52.819 Closrr_DV3[1225:204175] Progress status : 0.391804
> 2015-10-23 12:24:52.824 Closrr_DV3[1225:205474] Progress status : 0.393253
> 2015-10-23 12:24:52.829 Closrr_DV3[1225:205459] Progress status : 0.394701
> 2015-10-23 12:24:52.832 Closrr_DV3[1225:205474] Progress status : 0.396150
> 2015-10-23 12:24:52.850 Closrr_DV3[1225:205459] Progress status : 0.397599
> 2015-10-23 12:24:52.861 Closrr_DV3[1225:204175] Progress status : 0.399048
> 2015-10-23 12:24:52.867 Closrr_DV3[1225:204175] Progress status : 0.400496
> 2015-10-23 12:24:52.874 Closrr_DV3[1225:204175] Progress status : 0.401945
> 2015-10-23 12:24:52.884 Closrr_DV3[1225:204175] Progress status : 0.403394
> 2015-10-23 12:24:52.887 Closrr_DV3[1225:205474] Progress status : 0.404843
> 2015-10-23 12:24:52.903 Closrr_DV3[1225:204175] Progress status : 0.406291
> 2015-10-23 12:24:52.909 Closrr_DV3[1225:205474] Progress status : 0.407740
> 2015-10-23 12:24:52.922 Closrr_DV3[1225:205474] Progress status : 0.409189
>
> --trimmed logs
>
> -10-23 12:24:53.006 Closrr_DV3[1225:205474] Progress status : 0.428022
> 2015-10-23 12:24:53.012 Closrr_DV3[1225:205459] Progress status : 0.429471
> 2015-10-23 12:24:53.053 Closrr_DV3[1225:205474] Progress status : 0.439612
>
>
> *2015-10-23 12:24:53.063 Closrr_DV3*[1225:204029] INFO:App entered
> foreground:-[CLAppDelegate applicationDidBecomeActive:]
>
> //App became active and transfer resumed than already should have
> transferred — *resume time 2015-10-23 12:24:53.066 *
>
> 2015-10-23 12:24:53.066 Closrr_DV3[1225:205474] Progress status : 0.441056
> 2015-10-23 12:24:53.066 Closrr_DV3[1225:204169] Progress status : 0.442509
> 2015-10-23 12:24:53.195 Closrr_DV3[1225:204175] Progress status : 0.456996
>
> ---trimmed logs
>
>
> 2015-10-23 12:25:01.058 Closrr_DV3[1225:205474] Progress status : 0.989968
> 2015-10-23 12:25:01.066 Closrr_DV3[1225:205474] Progress status : 0.991417
> 2015-10-23 12:25:01.094 Closrr_DV3[1225:205474] Progress status : 0.992865
> 2015-10-23 12:25:01.132 Closrr_DV3[1225:205528] Progress status : 0.994314
>
> —trimmed logs
>
> 2015-10-23 12:25:03.944 Closrr_DV3[1225:205528] Progress status : 1.152870
> 2015-10-23 12:25:03.953 Closrr_DV3[1225:205474] Progress status : 1.154319
> 2015-10-23 12:25:03.961 Closrr_DV3[1225:205528] Progress status : 1.155767
> 2015-10-23 12:25:03.968 Closrr_DV3[1225:205474] Progress status : 1.156466
> 2015-10-23 12:25:03.975 Closrr_DV3[1225:205475] Progress status : 1.156466
> 2015-10-23 12:25:04.187 Closrr_DV3[1225:205528] TASK Finished
> :<AWSS3TransferManagerUploadRequest: 0x12768afa0> {
>     ACL = 0;
>     body =
> "file:///var/mobile/Containers/Data/Application/80F4F172-8C7C-4620-8710-9480F0FC9BFC/Documents/Closrr/Media/+6598595499/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov";
>     bucket = "closrr-media-dev";
>     cacheIdentifier =
> "56B6A88D-CBB9-4417-ADB6-0D522BE85E18-1225-00000149334313C7";
>     completedPartsArray =     (
>         "<AWSS3CompletedPart: 0x17483a8a0> {\n    ETag =
> \"\\\"671ce9e5dac5ddbfe7fce16f8a31e8f0\\\"\";\n    partNumber = 1;\n}",
>         "<AWSS3CompletedPart: 0x17062d1a0> {\n    ETag =
> \"\\\"522f1a2d770529db96c166196bf7d3da\\\"\";\n    partNumber = 2;\n}",
>         "<AWSS3CompletedPart: 0x174628ba0> {\n    ETag =
> \"\\\"e1969011e1fdd555c6c7d4218ef10568\\\"\";\n    partNumber = 3;\n}",
>         "<AWSS3CompletedPart: 0x17482b100> {\n    ETag =
> \"\\\"e5c0a76232ea896af6ad1af9ef49e9bd\\\"\";\n    partNumber = 4;\n}",
>         "<AWSS3CompletedPart: 0x174626720> {\n    ETag =
> \"\\\"b8ba12eacf4a47025b56db197315199c\\\"\";\n    partNumber = 5;\n}"
>     );
>     contentType = "video/quicktime";
>     currentUploadingPart = "<AWSS3UploadPartRequest: 0x1700f3c80> {\n
>  body =
> \"file:///private/var/mobile/Containers/Data/Application---99-6350B290968C\";\n
>    bucket = \"closrr-media-dev\";\n    contentLength = 1584248;\n    key =
> \”1444293870a37013c8182d1----44B6-BA30-62378840A1A4.mov\";\n    partNumber
> = 5;\n    uploadId =
> \"plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8sPBLCMBzlU.DhyqWZEs0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68Vi5T0EYcsJNiKPuOLPV4JT8sSk4IlBmTQxSw0js-\";\n}";
>     currentUploadingPartNumber = 6;
>     expires = "2015-10-23 05:16:06 +0000";
>     key =
> "1444293870a37013c8182d17dcf9d21657acd6d6dd/VID-EF005D3E-BE12-44B6-BA30-62378840A1A4.mov";
>     serverSideEncryption = 0;
>     state = 4;
>     storageClass = 0;
>     totalSuccessfullySentPartsDataLength = 22555768;
>     uploadId =
> "plb0xoQqik5Xl6i6u7TeZaTqw3j4gUMpR8zA37DZbAoFIcDwQZWAJnu8sPBLCMBzlU.DhyqWZEs0ye1ssWX0PNkxubKgxOD52g9wVAbMumpdxBB._ETHy7yaixUpuGVHZo68Vi5T0EYcsJNiKPuOLPV4JT8sSk4IlBmTQxSw0js-";
> }
>
> Summarising — *12:16* transfer started and I went in background and
> transfer resumes at *12:24 *where as per your response it should have
> finished.
>
> Thanks,
> Regards,
> Vicky S Dhas
> From: Yosuke Matsuda <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> Reply-To: awslabs/aws-sdk-ios-samples <
> reply@reply.github.com
> <javascript:_e(%7B%7D,'cvml','reply%2B00a9e1abb46b6406aacc901702988803f5b3aac621c0e06892cf000000011240f41792a169ce06b8144d@reply.github.com');>
> >
> Date: Friday, 23 October 2015 2:59 am
> To: awslabs/aws-sdk-ios-samples <aws-sdk-ios-samples@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','aws-sdk-ios-samples@noreply.github.com');>>
> Cc: Vicky Dhas <vickydhas@rappier.com
> <javascript:_e(%7B%7D,'cvml','vickydhas@rappier.com');>>
> Subject: Re: [aws-sdk-ios-samples] Handle continue upload/download while
> in background & Low speed transfer than android SDK (#29)
>
> I have confirmed the S3 Background Transfer sample (both Swift and
> Objective-C versions) kept downloading a file after the home button is
> pressed. Also, the iOS handles the background transfer, and the AWS Mobile
> SDK does not directly performs the download.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-ios-samples/issues/29#issuecomment-150323119>
> .
>


-- 
Sent from my iPhone

**Comment by yosuke-matsuda** [comment]
`AWSS3TransferManager` does not support background transfers. If you want to keep uploading/downloading data in the background, you need to use `AWSS3TransferUtility` instead.

**Comment by vickyrappier** [comment]
Noted with thanks I'll try changing my source code with this implementation.

Also why does the transfer becomes very slow when switched to 3G and then
even after coming back to wifi it's still slow.

It seems not identifying the network change and accordingly managing
bandwidth. Although the AWS SDK in android is rapid fast in 3G.

Can you guide please.

Thanks Vicky

On Wednesday, 28 October 2015, Yosuke Matsuda <notifications@github.com>
wrote:

> AWSS3TransferManager does not support background transfers. If you want
> to keep uploading/downloading data in the background, you need to use
> AWSS3TransferUtility instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-ios-samples/issues/29#issuecomment-151605798>
> .
>


-- 
Sent from my iPhone

**Comment by yosuke-matsuda** [comment]
The background transfer is handled by the iOS, not by the AWS Mobile SDK. You should refer to Apple's documentation for details.

**Comment by vickyrappier** [comment]
Sure thanks I shall migrate to code to handle transfer using background
transfer example as it may solve our purpose.

I checked your latest AWS background transfer is supporting transfers in
background.


On Wednesday, 11 November 2015, Yosuke Matsuda <notifications@github.com>
wrote:

> The background transfer is handled by the iOS, not by the AWS Mobile SDK.
> You should refer to Apple's documentation for details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-ios-samples/issues/29#issuecomment-155623058>
> .
>


-- 
Sent from my iPhone
