### ISSUE TITLE
How can I mutate an attribute in Cognito user pool?

### ISSUE THREAD

**Issue by returnzer0** [awslabs/aws-sdk-ios-samples#291]
I am trying to change the 'family_name' attribute in my user pool for a specific user, so for example when the person wants to change their last name to something else. How do I go about doing this? I am unable to find anything specific for the iOS Cognito SDK.

Thanks

**Comment by returnzer0** [comment]
Yes! That works perfectly. Thanks!

**Comment by kvasukib** [comment]
Thank you for confirming!
