### ISSUE TITLE
S3TransferManager > Default

### ISSUE THREAD

**Issue by semerda** [awslabs/aws-sdk-ios-samples#292]
`<key>S3TransferManager</key>
<dict>
    <key>Default</key>
    <dict>
        <key>Region</key>
        <string>us-east-1</string>
    </dict>
</dict>`

Is it possible to have n+ (others) regions as failovers?

**Comment by cbommas** [comment]
@semerda 

Please review the documentation of S3 Storage Classes (https://aws.amazon.com/s3/storage-classes/ for more information) and Cross region replication(https://docs.aws.amazon.com/AmazonS3/latest/dev/crr.html) to see how they can best meet your needs.  These are typically setup as policies on the bucket that will apply to all objects in the bucket.

When you setup a bucket,by default, Amazon S3 stores your data across multiple geographically distant Availability Zones. You can adjust this by tweaking the configuration using storage classes/cross region replication to suit your needs.

**Comment by cbommas** [comment]
@semerda 
Just checking back to see if you had further questions.

**Comment by semerda** [comment]
Works! Thank you.
