### ISSUE TITLE
Getting user profile details after loggingin via GOOGLE and FB

### ISSUE THREAD

**Issue by Geo-Joy** [awslabs/aws-sdk-ios-samples#293]
Iam using AWS Mobile Hub for iOS and wanted help getting user details by using AWS Cognito identity pools.

For example after logging-in via Google and Facebook, along with the secret keys which GOOGLE and FB gives, I also need the userProfile details like his EmailID, Profile_picture from them.

It will be good if someone can post SWIFT code for the same.

**Comment by kvasukib** [comment]
For Google SignInProvider,

```swift
import GoogleSignIn

let googleUser = GIDSignIn.sharedInstance().currentUser
        self.userName = googleUser?.profile.name
        self.imageURL = googleUser?.profile.imageURL(withDimension: GoogleSignInProviderProfileImageDimension)
// Set any additional proflie attributes here. This method is called after a user signs in with a provider.
```

For Facebook SignInProvider,

```swift
import FBSDKCoreKit
import FBSDKLoginKit

let imageGraphRequest = FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "picture.type(large)"])
        let imageConnection = FBSDKGraphRequestConnection()
        imageConnection.add(imageGraphRequest, completionHandler: { (connection, result, error) in
            guard let imageResult = result as? NSDictionary else  { return}
            if let imageURL = URL(string:(((imageResult.value(forKey: "picture") as AnyObject).value(forKey: "data") as AnyObject).value(forKey: "url") as? String)!) {
                self.imageURL = imageURL
            }
        })
        imageConnection.start()
        
        let userGraphRequest = FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "id, name, email"])
        let userConnection = FBSDKGraphRequestConnection()
        userConnection.add(userGraphRequest, completionHandler: { (connection, result, error) in
            guard let userResult = result as? NSDictionary else { return }
                if let userName = userResult.value(forKey: "name")  as? String {
                    self.userName = userName
                }
        })
userConnection.start()
```

**Comment by Sreekanth1234** [comment]
@kvasukib very thank dude... I got Facebook details from your code.. I'm following this link [https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in-customize.html](url) it comes UI with AWS Logo, Facebook and Google Button.. Facebook button working but Google button not working .. May i know reason?....
Thanks in advance....

**Comment by kvasukib** [comment]
@SreekanthGudisi Thank you for the response.

Can you post the code snippet and the dependencies section of your app/build.gradle? 
Also, do you have `GoogleSignIn` snippet in `awsconfiguration.json` file? 
What version of Android SDK are you using? 
What version of Google play services are you using?

**Comment by SreekanthGudisi** [comment]
@kvasukib thanks for the response. I have uploaded my initial registration iOS code on Github. Please have a look and do update me with the changes.
[iOS Code repo](https://github.com/SreekanthGudisi/aws-cognito-identity-pool-ios.git)

**Comment by SreekanthGudisi** [comment]
@kvasukib hey dude unfortunately Google button also working .. thanks for the immediately response..

**Comment by kvasukib** [comment]
@SreekanthGudisi Thank you for the confirmation. Please feel free to comment or open a new issue if you have any further questions!
