### ISSUE TITLE
Aws Cognito User pools or Identity pools

### ISSUE THREAD

**Issue by SreekanthGudisi** [awslabs/aws-sdk-ios-samples#294]
Hi,  

I'm trying implement Lex in iOS app with Cognito User pool or Identity pools... 

**1. If use Cognito User pool** 

I'm using source code which u have developed [https://github.com/awslabs/aws-sdk-ios-samples/tree/master/Lex-Sample/swift-3](url) .. In this code **AppDelegate.swift** 

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.APSouth1, identityPoolId: "ap-south-1_************")
        let configuration = AWSServiceConfiguration(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        let chatConfig = AWSLexInteractionKitConfig.defaultInteractionKitConfig(withBotName: "LamboBot", botAlias: "$LATEST")
        AWSLexInteractionKit.register(with: configuration!, interactionKitConfiguration: chatConfig, forKey: "AWSLexVoiceButton")
        chatConfig.autoPlayback = false
        AWSLexInteractionKit.register(with: configuration!, interactionKitConfiguration: chatConfig, forKey: "chatConfig")
        return true
    }
```

 In ChatViewController  for example, I typed Hi but i'm not able to get any response..

**2. If use Cognito Identity pool**  , 
   
Following this link [https://medium.com/libertyit/how-to-build-an-aws-lex-chatbot-for-an-ios-app-9fd7693353b](url) .... Then how to get profile details using Cognito Identity pool in iOS app.

Any links or code help full for me

Thanks in Advance…

**Comment by rohandubal** [comment]
Hello,

I think the issue is that you are using Cognito User Pool ID instead of Cognito Identity ID. 
```
let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.APSouth1, identityPoolId: "ap-south-1_************")
```

The Cognito Identity Pool ID should look something like: `ap-south-1:fsfdsa-dfasdf-asdf23-d324234`

Thanks,
Rohan

**Comment by Sreekanth1234** [comment]
@rohandubal thanks for the response.. I have few doubts .
1) Is it posible to Lex integration with **Cognito User pool** ?
2) [https://github.com/awslabs/aws-sdk-ios-samples/tree/master/Lex-Sample/swift-3](url) In **AppDelegate.swift**  i changed `let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.APSouth1, identityPoolId: "ap-south-1:6a54d2ac-1278-4db1-b238")` .. In ChatViewController,  I typed Hi but i'm not able to get any response

**Comment by rohandubal** [comment]
Hello @SreekanthGudisi 

The sample works correctly with a working backend.

If you want to use User Pools, you will have to use it in combination with Cognito Identity Pool as Lex uses IAM authentication. 

Does the bot work correctly in console?

**Comment by SreekanthGudisi** [comment]
@rohandubal I didn't check dude

**Comment by kvasukib** [comment]
@SreekanthGudisi Please feel free to reopen or open a new issue if you have any other questions.
