### ISSUE TITLE
PollySample[2444:1094470] CredStore - performQuery - Error copying matching creds

### ISSUE THREAD

**Issue by kiri11ko** [awslabs/aws-sdk-ios-samples#295]
Polly demo on swift not working. Press button Synthesize, no voice and error: 
2018-09-05 12:56:18.981559+0300 PollySample[2444:1094470] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}

**Comment by rohandubal** [comment]
What is the authorization mechanism you are using? What is the Device OS version and AWS SDK version with which you are facing this issue?

**Comment by kiri11ko** [comment]
authorization mechanism - Cognito
Device OS version 11.4.1
AWS SDK version  from github sample

**Comment by kiri11ko** [comment]
Yes, I changed the sample, because it did not work at the beginning, the project code is here https://github.com/kiri11ko/PollySample

I saw your link, but it's not clear what parameters to write to the host and port

**Comment by rohandubal** [comment]
I was able to run the sample app which you provided on my machine. This might be a problem with your local Xcode setup. I am closing this issue since there is not further actionable item for the SDKs.

**Comment by kiri11ko** [comment]
Does the speech synthesizer work for you? I run the project, the error is output to the console when the sound is synthesized and there is no sound.
