### ISSUE TITLE
AWS Cognito Identity Pool "GetID failed"

### ISSUE THREAD

**Issue by SreekanthGudisi** [awslabs/aws-sdk-ios-samples#296]
Hi,

I'm integrating CognitoIdentityPool with Lex..Following this link [https://medium.com/libertyit/how-to-build-an-aws-lex-chatbot-for-an-ios-app-9fd7693353b](url) ... Sometimes lex is working, but sometimes Lex is getting error when return clicked `GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]
interactionKit error: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}` 

Anyone has a answer ?

Thanks in advance

**Comment by behrooziAWS** [comment]
Seems like that sample requires you enable unauthenticated access on your pool, can you double check your pool configuration?  Likely you didn't enable it.

**Comment by behrooziAWS** [comment]
By working you mean it can actually interact with Lex?  Because if you have set it up in the same way as the sample but with authenticated only, it should fail to get an id and credentials and not be able to interact with Lex.

**Comment by SreekanthGudisi** [comment]
@behrooziAWS Yes interact with Lex.. I'm giving hi, Lex is giving response back to me .. That too response getting sometimes only..

**Comment by SreekanthGudisi** [comment]
> By working you mean it can actually interact with Lex? Because if you have set it up in the same way as the sample but with authenticated only, it should fail to get an id and credentials and not be able to interact with Lex.

Then what should i do ?

**Comment by desokroshan** [comment]
This is being tracked in [Issue#302](https://github.com/awslabs/aws-sdk-ios-samples/issues/302). Closing this instance.
