### ISSUE TITLE
Crash in drainSenderQueue

### ISSUE THREAD

**Issue by quanguyen** [awslabs/aws-sdk-ios-samples#299]
Hi,

I just updated AWS libraries to their latest version:

My `Podfile.lock`:

>  - AWSAuthCore (2.6.28):
>     - AWSCore (= 2.6.28)
>   - AWSAuthUI (2.6.28):
>     - AWSAuthCore (= 2.6.28)
>     - AWSCore (= 2.6.28)
>   - AWSCognitoIdentityProvider (2.6.28):
>     - AWSCognitoIdentityProviderASF (= 1.0.1)
>     - AWSCore (= 2.6.28)
>   - AWSCognitoIdentityProviderASF (1.0.1)
>   - AWSCore (2.6.28)
>   - AWSIoT (2.6.28):
>     - AWSCore (= 2.6.28)
>   - AWSMobileClient (2.6.28):
>     - AWSAuthCore (= 2.6.28)
>   - AWSUserPoolsSignIn (2.6.28):
>     - AWSAuthCore (= 2.6.28)
>     - AWSCognitoIdentityProvider (= 2.6.28)

However, I often hits a crash from AWS library:

![screen shot 2018-09-14 at 10 14 35 am](https://user-images.githubusercontent.com/11938078/45527859-eb7e3980-b807-11e8-9fb3-b0c648bc6b85.png)

This problem does not always, but it does occur (around 20-30%).

What could potentially cause this issue? Is there something that I could fix this?

Regards,

**Comment by therobwatson** [comment]
This issue has occurred repeatedly for my production app, occurring both before and after the MQTT client refactor that was released a few versions back.

So far, I have only been able to observe a sort-of pattern where it is more likely to occur during a weak network connection.  Users generally report have a weak cell or wifi signal at the time.

**Comment by desokroshan** [comment]
This is an SDK issue that is currently being tracked in [SDK repo Issue#1071](https://github.com/aws/aws-sdk-ios/issues/1071). Please update that thread if you have any comments.
