### ISSUE TITLE
build failed with issues in launch screen.storyboard

### ISSUE THREAD

**Issue by yeshao** [awslabs/aws-sdk-ios-samples#30]
file:///Users/yeshao/cognito/aws-sdk-ios-samples/S3TransferManager-Sample/Objective-C/S3TransferManagerSample/Launch%20Screen.storyboard: error: Illegal Configuration: Launch screens may not use instances of IBUISceneExitPlaceholder.

file:///Users/yeshao/cognito/aws-sdk-ios-samples/S3TransferManager-Sample/Objective-C/S3TransferManagerSample/Launch%20Screen.storyboard: error: Illegal Configuration: Launch screens may only have one top level object, which must be a UIView or a kind of UIViewController.

file:///Users/yeshao/cognito/aws-sdk-ios-samples/S3TransferManager-Sample/Objective-C/S3TransferManagerSample/Launch%20Screen.storyboard: error: Illegal Configuration: Launch screens may not use instances of IBUIStoryboardEntryPointIndicator.

**Comment by yosuke-matsuda** [comment]
If you are using Xcode 6, please update it to Xcode 7 and try again. Thanks.

**Comment by yeshao** [comment]
yes it compiles with xcode 7.
