### ISSUE TITLE
How to refreshSession using refreshToken to get new accessToken iOS | AWSCognitoIdentityProvider

### ISSUE THREAD

**Issue by qaisershehzad** [awslabs/aws-sdk-ios-samples#300]
How can I refresh Session using refreshToken to obtain new accessToken in iOS. 

I have seen javascript functions but couldn't find how we do it in iOS.

**Comment by minbi** [comment]
If you are using the AWSCognitoIdentityProvider, this should be handled automatically when the accessToken is within 5 minutes (subject to change) of expiry.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
