### ISSUE TITLE
enable sharing of the  KeyChain across access groups | iOS Extension (Share Extension)

### ISSUE THREAD

**Issue by qaisershehzad** [awslabs/aws-sdk-ios-samples#301]
Hello, 
I want to check is there a way we can getSession() in iOS Extension (Share Extension). As I need to access session token for my api calls. It is again loading Login View Controller while it should give same Identity. Like how I can enable sharing of the  KeyChain across access groups.

I looked into  AWSCognitoIdentityUser.m and in this function 
-(AWSTask<AWSCognitoIdentityUserSession*> *) getSession  and AWSUICKeyChainStore and where keychain is initialized. 
We actually need to initialize keychain with custom Service and AccessGroup so that it can be accessed from extension.

Like currently it is like this in AWSCognitoIdentityUserPool
        _keychain = [AWSUICKeyChainStore keyChainStoreWithService:[NSString stringWithFormat:@"%@.%@", [NSBundle mainBundle].bundleIdentifier, [AWSCognitoIdentityUserPool class]]];

 while we want something like this in AWSCognitoIdentityUserPool where we can provide group and service       
        _keychain = [AWSUICKeyChainStore keyChainStoreWithService:@"OUR OWN SERVICE STRING" accessGroup:@"OUR OWN SHARE ACCESS GROUP"];

https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L168

**Comment by desokroshan** [comment]
This is being tracked as [SDK Issue#1106](https://github.com/aws-amplify/aws-sdk-ios/issues/1106).
