### ISSUE TITLE
AWS CognitoIdentityPool "GetID failed"

### ISSUE THREAD

**Issue by SreekanthGudisi** [awslabs/aws-sdk-ios-samples#302]
Hi,

I'm integrating CognitoIdentityPool with Lex..Sometimes lex is working, but sometimes Lex is getting error when return clicked `GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}] interactionKit error: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}`

Anyone has Swift code of SignIn , SignOut, clearCache , refresh, token and getUserCredentials within **AWSAuthUIConfiguration** please drop here.. Or else i will give my code please check it, which functions are i have missed..

**Comment by minbi** [comment]
Hi @SreekanthGudisi ,

Can you provide the relevant code that you are using to invoke Lex and CognitoIdentityPool?

The problem appears to be that the session may have expired or the user never signed-in; and unauthenticated (guest) credentials are trying to be obtained. Do you require users to be signed-in when using your app?

**Comment by SreekanthGudisi** [comment]
@minbi very thanks for given reply ...  [This is code link](https://github.com/SreekanthGudisi/aws-cognito-identity-pool-ios) ....

This is my way, 1st SignIn with **CognitoIdentityPools** after that it will to home scrren... In Home screen ChatView is there. If i type hello in my textfield Lex will give response  something.. Once i clicked SignOut button i'm facing
 `GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]` in console.

And just stop app run app again 

```
2018-09-28 15:00:28:379 SampleApp[22645:259186] GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]     

2018-09-28 14:50:47:915 SampleApp[20339:246036] Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]

2018-09-28 14:50:47:916 SampleApp[20339:245975] Welcome to AWS! You are connected successfully.
2018-09-28 14:50:47:916 SampleApp[20339:245975] result = (null),error = Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}
```
 it is coming in console ...


Again SignIn with **CognitoIdentityPools**, type hi in my textfield at that time Lex facing error 
`2018-09-28 15:00:28:379 SampleApp[22645:259186] GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}] interactionKit error: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}`

And Some times **GetId Credentials** also failed.. 

If i'm correct, i have to call functions ( mergelogins, clearCache, refresh and assignToken to IdentityId from SignInprovider ) while SignIn and SignOut ... But i'm struct here ..I don't know how to do..

**Comment by minbi** [comment]
The AuthUI SDK currently tries to retrieve an identity id the moment it is signed-out. Because of this you may need to turn on unauthenticated identities in the pool, but give the users no permissions when they are in this state. The team will look into fixing this issue.

**Comment by SreekanthGudisi** [comment]
@minbi any updates ?

**Comment by muellerfr** [comment]
@SreekanthGudisi, we're working on improvements to the AWSMobileClient to address this issue. We will update the thread when we release the fix.

**Comment by muellerfr** [comment]
Hi @SreekanthGudisi,

we recently release an improvements to the AWSMobileClient to make it easier to authenticate users. The corresponding documentation can be found here: https://aws-amplify.github.io/docs/ios/authentication

There are Swift code samples for SignIn , SignOut, Token fetch and refresh. We recommend using the AWSMobileClient for your use case. Please take a look and let us know if you have any questions.

**Comment by muellerfr** [comment]
Hi @SreekanthGudisi,

we're now tracking all AWS SDK for iOS related issues in the SDK repo itself. I am going to close this issue. If you still need help please open an issue [here](https://github.com/aws-amplify/aws-sdk-ios/issues).
