### ISSUE TITLE
Users still going to unauth identity in ID pool

### ISSUE THREAD

**Issue by Linger-ing** [awslabs/aws-sdk-ios-samples#306]
@karthiksaligrama @aws-dash @AWSRandall  I have followed all the steps as given in the AWS doc and also tried methods shows here. But still, my user is going to unauthenticated access in the ID pool. I have my code here. Can anyone please tell me where I am going wrong. 

```
func login(){
        
        
        self.fetchUserAttributes()
        
       
        //cognito
        
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USWest2, identityPoolId: "us-west-2:555da9bf-410a-41da-8a39-XXXXXXXX", identityProviderManager: pool)
        let serviceConfiguration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: credentialsProvider)!
        AWSServiceManager.default().defaultServiceConfiguration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: credentialsProvider)
    
       credentialsProvider.getIdentityId().continueWith { (task) -> Any? in
            
          //  print(credentialsProvider.credentials())
            
            
            let client = APPTIMEUserAppTimeClient.default()
            
            
            let testbody = APPTIMEPostRequestModel()
            testbody?.userId="2"
            testbody!.appTime=100
            
            
            client.apptimePost(body: testbody! ).continueWith{ (task: AWSTask?) -> AnyObject? in
                if let error = task!.error {
                    print("Error occurred: \(error)")
                    return nil
                }
                
                if let result = task!.result {
                    // Do something with result
                    print(result)
                }
                
                return nil
            }
        return nil
        }
            
        self.user?.signOut()
        
        alertCustom("Go to setup profile page", self)
    }
```
I am calling the above code after sign in. I need to make the API call. but it is showing not authorised exception. here is the error in the console 

> > Request headers:
> {
>     "Content-Type" = "application/x-amz-json-1.1";
>     Host = "cognito-identity.us-west-2.amazonaws.com";
>     "User-Agent" = "aws-sdk-iOS/2.6.13 iOS/12.0 en_US";
>     "X-Amz-Date" = 20181003T075610Z;
>     "X-Amz-Target" = "AWSCognitoIdentityService.GetId";
> }
> 
> 2018-10-03 13:26:10:731 loopstalk[7306:81118] Request body:
> {"IdentityPoolId":"us-west-2:555da9bf-410a-41da-8a39-be6d86315097"}
> 2018-10-03 13:26:10.740715+0530 loopstalk[7306:81337] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x7f9b61cd0210] get output frames failed, state 8196
> 2018-10-03 13:26:10.742152+0530 loopstalk[7306:81337] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x7f9b61cd0210] get output frames failed, state 8196
> 2018-10-03 13:26:10.742979+0530 loopstalk[7306:81337] TIC Read Status [3:0x0]: 1:57
> 2018-10-03 13:26:10.743119+0530 loopstalk[7306:81337] TIC Read Status [3:0x0]: 1:57
> 2018-10-03 13:26:11:041 loopstalk[7306:81116] Response headers:
> {
>     "Content-Length" = 111;
>     "Content-Type" = "application/x-amz-json-1.1";
>     Date = "Wed, 03 Oct 2018 07:56:10 GMT";
>     "x-amzn-errormessage" = "Unauthenticated access is not supported for this identity pool.";
>     "x-amzn-errortype" = "NotAuthorizedException:";
>     "x-amzn-requestid" = "caeb9d51-c6e1-11e8-baa6-fd6e9c8f3891";
> }
> 2018-10-03 13:26:11:041 loopstalk[7306:81116] Response body:
> {"__type":"NotAuthorizedException","message":"Unauthenticated access is not supported for this identity pool."}
> 2018-10-03 13:26:11:041 loopstalk[7306:81116] GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]
> 2018-10-03 13:26:11:042 loopstalk[7306:81360] Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]
> 
> > 
> 

here is the Cognito code in appDelegate 
```
` func setupCognitoUserPool() {
        let clientId:String = "53mqhcXXXXXXXXXXq3b3v1"
        let poolId:String = "us-west-2_22yXXXXXZg85"
        let clientSecret:String = "1aqr772ddXXXXXXXXXXXXXXu5ochdfsjc2ergnrna48"
      //  let region: AWSRegionType = AWSRegionType.USWest2
        
        
        
        
        let serviceConfiguration = AWSServiceConfiguration(region: .USWest2, credentialsProvider: nil)
        let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: clientId, clientSecret: clientSecret, poolId: poolId)
        AWSCognitoIdentityUserPool.register(with: serviceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: "UserPool")
        let pool = AWSCognitoIdentityUserPool(forKey: "UserPool")
         pool.delegate = self`}
```

**Comment by neil-oliver** [comment]
I am having the same issue. I have doubled checked my setup several times and i am pretty sure it was working for me before i recreated my project in the MobileHub. I spent 14 hours going over it and creating everything and i cannot get it to authenticate. I think i have narrowed it down to either me recreating the project or updating my pods. Any help appreciated!

**Comment by rohandubal** [comment]
Hello,

Are you logging in to your user pool before you make the getIdentity call? 

Based on the response which I see, it seems that the response body does not have the logins map which contains the token from user pools.

The error which you are seeing is "Unauthenticated access" is not supported which means that the API is trying to fetch un-auth credentials instead of auth credentials using user pools token.

Thanks,
Rohan

**Comment by Linger-ing** [comment]
@rohandubal how to set logins map in iOS. It was easy and straightforward in android. But we did not find specific code to do the same in iOS. Please let me know

**Comment by kvasukib** [comment]
@Linger-ing Sorry for the delayed response. It's a bit different from how you set the logins map in iOS compared to Android. Apologies for the confusion. 

For example, if you want to federate Facebook token with `Cognito` and retrieve AWSCredentials, the first step is to create a class that conforms to the `AWSIdentityProviderManager` protocol. The `logins` method in this class should return the dictionary that has the token.

```swift
class MyFacebookSignInProvider: NSObject, AWSIdentityProviderManager {
        
    func logins() -> AWSTask<NSDictionary> {
                if let token = AccessToken.current?.authenticationToken {
                    return AWSTask(result: [AWSIdentityProviderFacebook: token])
                }
                return AWSTask(error: NSError(domain: "Facebook SignIn", code: -1 , userInfo: ["Facebook" : "Facebook access token is not valid or available"]))
            }
        }
```

The second step would be to construct an object of `FacebookProvider` and pass it to the `AWSCognitoCredentialsProvider` you have.

```swift
 let fbProvider = MyFacebookSignInProvider()
 let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: "XXX", identityProviderManager: fbProvider)
```

Hope this helps. Please let me know if you have any questions!

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
