### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=4099

### ISSUE THREAD

**Issue by Amornthep** [awslabs/aws-sdk-ios-samples#309]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.

Cocoapods
Using AWSCognito (2.6.31)
Using AWSCognitoAuth (2.6.31)
Using AWSCognitoIdentityProvider (2.6.31)
Using AWSCognitoIdentityProviderASF (1.0.1)
Using AWSCore (2.6.31)

Xcode Version 10.0 (10A255)
iOS version 12.0
Init
```
let serviceConfiguration = AWSServiceConfiguration(region: CognitoIdentityUserPoolRegion, credentialsProvider: nil)
        let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: CognitoIdentityUserPoolAppClientId, clientSecret: CognitoIdentityUserPoolAppClientSecret, poolId: CognitoIdentityUserPoolId)
        AWSCognitoIdentityUserPool.register(with: serviceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: AWSCognitoUserPoolsSignInProviderKey)
     var   pool = AWSCognitoIdentityUserPool(forKey: AWSCognitoUserPoolsSignInProviderKey)

//Call
pool?.signUp(email, password: password, userAttributes: attributes, validationData: nil).continueWith {(task) -> Any? in
    
            DispatchQueue.main.async(execute: {
                if let error = task.error as NSError? {
                    result(error)
                } else if task.result != nil  {
                    result(nil)
                }
            })
            return nil
        }
```

**Comment by kvasukib** [comment]
@Amornthep From the error message you posted:

```
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.
```

I see that this message is not coming from AWS. Can you give a summary of what is the error you're getting?

**Comment by Amornthep** [comment]
@kvasukib 
Sorry i'm bad . I see that log from console .

I'm try log from response. Got problem  thx.

`pool?.signUp(email, password: password, userAttributes: attributes, validationData: nil).continueWith {(task) -> Any? in
    
            DispatchQueue.main.async(execute: {
                if let error = task.error as NSError? {
                    print(error.userInfo["message"])
                    print(error.localizedDescription)
                    result(error)
                } else if task.result != nil  {
                    result(nil)
                }
            })
            return nil
        }`

response

Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
Optional(App client xxxxxxxxxxxxx is not configured for secret but secret hash was received)
The operation couldn’t be completed. (com.amazonaws.AWSCognitoIdentityProviderErrorDomain error 13.)

**Comment by kvasukib** [comment]
@Amornthep It looks like you have the Cognito Secret not configured on the userpools however you are passing in a secret hash.
