### ISSUE TITLE
Unable to install pod

### ISSUE THREAD

**Issue by manishnath** [awslabs/aws-sdk-ios-samples#31]
Downloading dependencies
Installing AWSCore (2.2.7)

[!] Error installing AWSCore
[!] /usr/bin/git clone https://github.com/aws/aws-sdk-ios.git /Users/Manish/Downloads/aws-sdk-ios-samples-master/S3BackgroundTransfer-Sample/Objective-C/Pods/AWSCore --single-branch --depth 1 --branch 2.2.7

Cloning into '/Users/Manish/Downloads/aws-sdk-ios-samples-master/S3BackgroundTransfer-Sample/Objective-C/Pods/AWSCore'...

fatal: unable to access 'https://github.com/aws/aws-sdk-ios.git/': Could not resolve host: github.com

**Comment by rohandubal** [comment]
Could you please post the contents of your pod file? It should look something like this : 
https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferManager-Sample/Swift/Podfile

**Comment by yosuke-matsuda** [comment]
Based on the log, it seems like your DNS cannot resolve "github.com". What happens when you type the following in Terminal?

    $ ping github.com

**Comment by manishnath** [comment]
Yea you are right. Working now thank you.
