### ISSUE TITLE
Polly running on XCUITest with no audio sound

### ISSUE THREAD

**Issue by jingyul** [awslabs/aws-sdk-ios-samples#312]
I made a small test app using Polly to speak some text and it plays well. I then moved the same piece of code to XCUITest, there is no compile or run-time error when the code runs through, but there is no sound came out. Any clue what to look for to solve this problem? Just want to let you know that XCUITest is running on a background thread.

**Comment by desokroshan** [comment]
This issue is being tracked in [aws-sdk-ios repo Issue#1086](https://github.com/aws/aws-sdk-ios/issues/1086).
