### ISSUE TITLE
error in 'sudo gem install cocoapods'

### ISSUE THREAD

**Issue by timwukp** [awslabs/aws-sdk-ios-samples#313]
pls change to 
sudo gem install -n /usr/local/bin cocoapods

**Comment by desokroshan** [comment]
@timwukp ```sudo gem install cocoapods``` seems to work well for me and is the recommended way for installing cocoapods as described in the [cocoapods documentation](https://cocoapods.org/). Please open an issue with [cocoapods](https://github.com/CocoaPods) if you are having trouble installing cocoapods.
