### ISSUE TITLE
not able do to signin, (if it gives wrong details "user does not exits" , if gives true details) getting these issues

### ISSUE THREAD

**Issue by santhoshappdev** [awslabs/aws-sdk-ios-samples#317]
reason: '*** -[Swift._NSContiguousString substringFromIndex:]: Index 9223372036854775808 out of bounds; string length 47'
![screen shot 2018-10-29 at 5 56 07 pm](https://user-images.githubusercontent.com/35039366/47654633-4221b600-dbb1-11e8-9dfb-7462f1d4dd3a.png)

please help me...login with get success token

**Comment by santhoshappdev** [comment]
I need help for login and get token (many sample i checked but not able to get success ).

**Comment by santhoshappdev** [comment]
please help me any one .

**Comment by muellerfr** [comment]
Hello @santhoshappdev,

Let's track this issue in the SDK repo: https://github.com/aws/aws-sdk-ios/issues/1075
