### ISSUE TITLE
Token renew token after expiration

### ISSUE THREAD

**Issue by evgzor** [awslabs/aws-sdk-ios-samples#319]
According to https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-refresh-token

The Mobile SDK for iOS and the Mobile SDK for Android automatically refresh your ID and access tokens if there is a valid (non-expired) refresh token present, and the ID and access tokens have a minimum remaining validity of 5 minutes. If the refresh token is expired, your app user must reauthenticate by signing in again to your user pool.

Could u please provide example in swift how to renew the token ? Just to be sure that we r on right way?

**Comment by desokroshan** [comment]
For SDK related questions please open a github issue in the [iOS SDK repo](https://github.com/aws-amplify/aws-sdk-ios). We will track this as a [SDK Issue](https://github.com/aws-amplify/aws-sdk-ios/issues/1092). Closing this sample issue.
