### ISSUE TITLE
Value of type 'ViewController' has no member 'indexOfDownloadRequest'

### ISSUE THREAD

**Issue by datomnurdin** [awslabs/aws-sdk-ios-samples#32]
I got this error message in Swift 2.0.

```
/Users/ZERO/Documents/Xcode/XXXXX/ViewController.swift:139:40: Value of type 'ViewController' has no member 'indexOfDownloadRequest'
```

For this file

https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferManager-Sample/Swift/S3TransferManagerSampleSwift/DownloadViewController.swift

The code on line 139

```
if let index = self.indexOfDownloadRequest(self.downloadRequests, downloadRequest: downloadRequest) {
                            /* -- */
                        }
```

Please advice. Thank you.

**Comment by rohandubal** [comment]
Which version of Xcode are you using? I am not able to re-produce the issue. Do you have any steps by which we can reproduce this? Thanks.

**Comment by datomnurdin** [comment]
I'm using xcode 7.0.1.

**Comment by rohandubal** [comment]
Could you check out a fresh version of the sample app and try building it without any modifications to the code? If it builds fine, you can then modify the constants.swift file and add the identity and bucket details there to check the working of the sample app. Please let me know if that works out fine. Thanks.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. If you continue to experience the issue, please feel free to update the thread with the request information. Thanks.
