### ISSUE TITLE
How to upload image as public with ACL

### ISSUE THREAD

**Issue by purnimaSingh** [awslabs/aws-sdk-ios-samples#34]
I am using this method to upload image:

AWSS3TransferUtilityUploadExpression *expression = [AWSS3TransferUtilityUploadExpression new];
    expression.uploadProgress = self.uploadProgress;
    
    AWSS3TransferUtility *transferUtility1 = [AWSS3TransferUtility defaultS3TransferUtility];
    [[transferUtility1 uploadFile:self.saved_Video_Url
                          bucket:@"staticapp"
                             key:videoNamekey
                    contentType:@"movie/quicktime"
                      expression:expression
                completionHander:self.completionHandler] continueWithBlock:^id(AWSTask *task)
    {
        if (task.error) {
            NSLog(@"Error: %@", task.error);
        }
        if (task.exception) {
            NSLog(@"Exception: %@", task.exception);
        }
        if (task.result) {
            dispatch_async(dispatch_get_main_queue(), ^{
                NSLog(@"Uploading...");
            });
        }
        
        [self.collection insertObject:transferUtility atIndex:0];
        
        return nil;
    }];

this image is not uploading as public but as private and when i hit the url on browser then shows the error access dined because of ACL permission

**Comment by yosuke-matsuda** [comment]
The upload methods take an expression object. You can call [`- setValue:forRequestParameter:`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtilityExpression.html#//api/name/setValue:forRequestParameter:) to modify the ACL using `x-amz-acl` header. Refer to Amazon S3 [API Reference](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) for more details.

**Comment by ericleiyang** [comment]
Just for anyone experiencing the same issue,

The method for setting ACL: "read", "public-read", or etc., is:

expression. setValue: forRequestHeader:
Happy coding!!

Cheers.

**Comment by hcn1519** [comment]
To do this, your `expression` should be like this.(Swift)

```swift
let expression = AWSS3TransferUtilityUploadExpression()
expression.setValue("public-read", forRequestHeader: "x-amz-acl")
```

**Comment by saroar** [comment]
@hcn1519 thanks man you save my life :)
