### ISSUE TITLE
How do I download multiple files in the background using AWSS3TransferUtility?

### ISSUE THREAD

**Issue by ftvs** [awslabs/aws-sdk-ios-samples#36]
It is not obvious from the sample or the source code that each download task will be assigned a single identifier.

**Comment by yosuke-matsuda** [comment]
You can call the download method for each file you want to download. Each task has a [`taskIdentifier`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtilityTask.html#//api/name/taskIdentifier) per API Reference.

**Comment by ftvs** [comment]
Looks like the taskIdentifier is automatically generated to be unique. In short, just download them without any special handling besides the standard background downloading and whatever is required by the app. Thanks.
