### ISSUE TITLE
Problem with transferUtility?.getUploadTasks()

### ISSUE THREAD

**Issue by aTylerRice** [awslabs/aws-sdk-ios-samples#38]
I am trying to get the list of current upload tasks. For some reason when I call getUploadTasks on my AWSS3TransferUtility object I am being returned an AWSTask rather than an array of AWSS3TransferUtilityUploadTask objects as the documentation suggests here http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html#//api/name/getAllTasks

Here is my code: 
let transferUtility = AWSS3TransferUtility.defaultS3TransferUtility()
if let uploadTasks = transferUtility?.getUploadTasks() {
        for uploadTask in uploadTasks {
            print("uploadTask")
        }
}

**Comment by yosuke-matsuda** [comment]
You need to use `- continueWithBlock:` and retrieve the list of tasks from `task.result`. See [Working with AWSTask](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html) for more details.

**Comment by yosuke-matsuda** [comment]
This seems like a cross post of [this issue](https://github.com/aws/aws-sdk-ios/issues/287#issuecomment-162061855). Closing this in favor of the original issue.
