### ISSUE TITLE
Failed to import bridging header for /aws-sdk-ios-samples-master/CognitoSync-Sample/Swift

### ISSUE THREAD

**Issue by joebernard** [awslabs/aws-sdk-ios-samples#39]
After running pod install, the build fails with the following:

/opt/demos/aws-sdk-ios-samples-master/CognitoSync-Sample/Swift/CognitoSyncDemo/CognitoSyncDemo-Bridging-Header.h:19:9: note: in file included from /opt/demos/aws-sdk-ios-samples-master/CognitoSync-Sample/Swift/CognitoSyncDemo/CognitoSyncDemo-Bridging-Header.h:19:
#import "DeveloperAuthenticatedIdentityProvider.h"
        ^
/opt/demos/aws-sdk-ios-samples-master/CognitoSync-Sample/Swift/CognitoSyncDemo/DeveloperAuthenticated/DeveloperAuthenticatedIdentityProvider.h:16:9: error: 'AWSCore/AWSCore.h' file not found
#import <AWSCore/AWSCore.h>
        ^
<unknown>:0: error: failed to import bridging header '/opt/demos/aws-sdk-ios-samples-master/CognitoSync-Sample/Swift/CognitoSyncDemo/CognitoSyncDemo-Bridging-Header.h'

Looks like it isn't find AWSCore.h even though cocoapods shows it was loaded.

XCode 7.2

**Comment by nishkrishnan** [comment]
Hey, I tried reproing this and the .xcworkspace builds fine for me in both Xcode 7.1 and Xcode 7.2.  I get the same error as you if I try to build the .xcodeproj, is this what you are doing? If so, you need to use the .xcworkspace that gets generated by cocoapods.

Thanks,
Nish

**Comment by joebernard** [comment]
Ah, you are correct. I had the project open. Thanks for the help.
