### ISSUE TITLE
AWS Lambda example in Swift 2.1

### ISSUE THREAD

**Issue by n8sabes** [awslabs/aws-sdk-ios-samples#40]
An iOS Swift 2.1 sample to invoke Lambda functions would be appreciated.

**Comment by yosuke-matsuda** [comment]
I'll share this as a feature request with the team. Thanks.

**Comment by kyleroche** [comment]
@n8sabes : You could invoke Lambda functions via AWS IoT as well. Publish a message over MQTT:
**Swift example**: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift/ 

Then put a rule in place to invoke the Lambda function:
**Rules doc**: http://docs.aws.amazon.com/iot/latest/developerguide/aws-iot-create-rule.html

That might hold you over until a Swift example directly to Lambda invoke is ready.

**Comment by n8sabes** [comment]
Thanks @kyleroche. Will take a look at it.

**Comment by simoami** [comment]
@n8sabes  I found this example online:

```
    let invocationRequest = AWSLambdaInvokerInvocationRequest()
    invocationRequest.functionName = "myFunction"
    invocationRequest.invocationType = AWSLambdaInvocationType.RequestResponse
    invocationRequest.payload = ["email" : "example@example.com", "name" : "example"]

    let lambdaInvoker = AWSLambdaInvoker.defaultLambdaInvoker()
    let task = lambdaInvoker.invoke(invocationRequest).continueWithSuccessBlock() { (task) -> AWSTask! in
        print("response: ", task.result)
    }
```

Your other option and the one I recommend for a stronger and more flexible architecture is to expose the lambda function as an API gateway end-point. This will give you a web api to interact with from the outside via https regardless of the client (web/mobile,IoT). This also gives you to flexibility to rename or replace your lambda without affecting clients.

Check out this [article](https://d0.awsstatic.com/whitepapers/AWS_Serverless_Multi-Tier_Architectures.pdf) (page 15)

**Comment by RyPoints** [comment]
> Your other option and the one I recommend for a stronger and more flexible architecture is to expose the lambda function as an API gateway end-point.

I'd actually recommend against this for many use-cases.  I understand exposing the Lambda functions as an REST API is a more familiar method of access for many.  One benefit of using Amazon's SDKs are that they provide additional security and identity verification options.  The API Gateways also have a 10 second time limit: http://stackoverflow.com/questions/31973388/amazon-api-gateway-timeout I definitely have functions in Lambda that will always take more than 10 seconds to process.

I happen to be doing the same thing in Swift right now.  I tried this code:

```
   let invocationRequest = AWSLambdaInvokerInvocationRequest()
    invocationRequest.functionName = "myFunction"
    invocationRequest.invocationType = AWSLambdaInvocationType.RequestResponse
    invocationRequest.payload = ["email" : "example@example.com", "name" : "example"]

    let lambdaInvoker = AWSLambdaInvoker.defaultLambdaInvoker()
    let task = lambdaInvoker.invoke(invocationRequest).continueWithSuccessBlock() { (task) -> AWSTask! in
        print("response: ", task.result)
    }
```

It errors out on print("response: ", task.result) with the error:

```
No 'print' candidates produce the expected contextual result type 'AWSTask!'
```

**Comment by RyPoints** [comment]
It looks like this is the functional version of that sample code:

```
func initializeLambda() {
        
        let credentialsProvider = AWSStaticCredentialsProvider.init(accessKey:Constants.AWS_ACCESS_KEY, secretKey: Constants.AWS_SECRET_KEY)
        let defaultServiceConfiguration = AWSServiceConfiguration(region: AWSRegionType.USWest2, credentialsProvider: credentialsProvider)
        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = defaultServiceConfiguration
    }
``` 

```
    self.initializeLambda()
    let invocationRequest = AWSLambdaInvokerInvocationRequest()
    invocationRequest.functionName = "myFunction"
    invocationRequest.invocationType = AWSLambdaInvocationType.RequestResponse
    invocationRequest.payload = ["email" : "example@example.com", "name" : "example"]
    let lambdaInvoker = AWSLambdaInvoker.defaultLambdaInvoker()
    lambdaInvoker.invoke(invocationRequest).continueWithSuccessBlock() { (task: AWSTask?) -> AWSTask? in
            print("response: %@", task!.result)
            return task;
        }
```

**Comment by minbi** [comment]
Lex samples available [here](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/Lex-Sample)

**Comment by muellerfr** [comment]
Hello @n8sabes,

Do you still require help with this issue? The recommended approach is to use API Gateway. Please view the documentation here: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-cloud-logic.html#ios-swift

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
