### ISSUE TITLE
where are the source codes in "DeveloperAuthenticated" folder from?

### ISSUE THREAD

**Issue by zhihuitang** [awslabs/aws-sdk-ios-samples#42]
Hi, 

in the "DeveloperAuthenticated" folder of CognitoSyncDemo-Swift, there are 6 files:
```
Crypto.h
Crypto.m
DeveloperAuthenticatedIdentityProvider.h
DeveloperAuthenticatedIdentityProvider.m
DeveloperAuthenticationClient.h
DeveloperAuthenticationClient.m
````

Where are these files from? Are they generated from APIGateway or written by you?
If they are written by you why not Swift? Since the project is a Swift project.
Could you please also provide Swift example? thank you very much.

**Comment by MarkMerc123** [comment]
Hello,

These are written by the app developer (in this case us). We will work on updating these files to be Swift in the future.

In the mean time, you can see sample Swift code for these classes in the Amazon Cognito developer guide here (make sure you select Swift from the drop down):
http://docs.aws.amazon.com/cognito/devguide/identity/developer-authenticated-identities/

**Comment by zhihuitang** [comment]
Hi MarkMerc123,

Thank you for you reply. They are exactly what I am looking for.

**Comment by zhihuitang** [comment]
hi MarkMerc123,


In the tutorial http://docs.aws.amazon.com/cognito/devguide/identity/developer-authenticated-identities/,

the providerName is readonly in AWSAbstractCognitoIdentityProvider, how can we set it in its sub-class?

```
class DeveloperAuthenticatedIdentityProvider: AWSAbstractCognitoIdentityProvider {
    let developerProvider = "<Developer_provider_name>"

    init(regionType: AWSRegionType, identityId: String!, accountId: String!, identityPoolId: String!, logins: [NSObject : AnyObject]!, providerName: String!) {
        super.init(regionType: regionType, identityId: identityId, accountId: accountId, identityPoolId: identityPoolId, logins: logins)
        **self.providerName = providerName**
        // Initialize any other objects needed here
    }
    ..........
```

**Comment by MarkMerc123** [comment]
Hi,

It is not shown in the sample code, but you can override the variable in your subclass to make it read/write to set it.

-Mark
