### ISSUE TITLE
implement a developer authenticated identity

### ISSUE THREAD

**Issue by LamourBt** [awslabs/aws-sdk-ios-samples#46]
I am create the stack and have my url to use in my IOS app, however I am trouble to create the other the provider.. Any Help please

**Comment by yosuke-matsuda** [comment]
This [end-to-end example](https://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en) should help you understand the developer authenticated identities.

**Comment by LamourBt** [comment]
I understand the concept however I am having trouble to implement the refresh function 

override func refresh() -> AWSTask! {
        self.logins = // what should be the logins 
        self.identityId = // are they asking for IdentityPoolID or Developer provider name 
        self._token = // what is the token  ? is the URLApplication 
        return AWSTask(result: self.identityId)
    }

**Comment by rachitdhall** [comment]
Hi,

When using developer authenticated identities, the way to get the identityId and token is through the [GetOpenIdTokenForDeveloperIdentity](http://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetOpenIdTokenForDeveloperIdentity.html) API. You would need a backend or authentication server of your own which takes in the username and password from the application, then call the above mentioned API. This would return an identityId and a token which you can pass it back to you application. You can always post your questions on our [forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)

Thanks,
Rachit

**Comment by LamourBt** [comment]
So where I would had those code can you provide more information if you can please @rachitdhall

**Comment by rachitdhall** [comment]
Our [blog](https://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en) talks about how you can implement refresh and getIdentityId methods. It also has Objective C code samples.

**Comment by helloniklas** [comment]
That blog doesn't really help much, I find this posting helpful. http://baczuk.com/2015/12/AWS-Cognito-in-Swift/

**Comment by rachitdhall** [comment]
I hope that our documentation and community efforts resolved your issue. If there are still some issues, please feel free to post in our [forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).
