### ISSUE TITLE
ALAssetTypePhoto deprecated

### ISSUE THREAD

**Issue by jmolayem** [awslabs/aws-sdk-ios-samples#47]
For the S3FileTransfer starter file,

UploadViewController - 'ALAssetTypePhoto' was deprecated in iOS 9.0: Use PHAssetMediaTypeImage from the Photo frameworks instead.

**Comment by yosuke-matsuda** [comment]
Since our samples support iOS 8 and above, we should move to the `PHAssetMediaTypeImage` constant. Thanks.

**Comment by muellerfr** [comment]
Hello @jmolayem,

we're deprecating the S3TransferManager sample in favor of the  S3TransferUtility sample. I marked the sample accordingly and we will remove it from the repo in two weeks. If you require help with using S3TransferUtility, please view the sample or open an issue in aws/aws-sdk-ios.
