### ISSUE TITLE
Demo builds not working for latest Xcode (7.2.1) and Cocoapods (0.39.0)

### ISSUE THREAD

**Issue by colinmadere** [awslabs/aws-sdk-ios-samples#48]
New to these environments so maybe there's an obvious fix, but I was having trouble getting the AWS Mobile SDK instructions to work with cocoapods for the AWS libraries, so I tried these demos and also am getting similar build failures.

Following the instructions exactly with clean install of CocoaPods leads to a failure to find header 'AWSCore/AWSCore.h' and "Failed to import bridging header" errors:

![screen shot 2016-02-04 at 2 36 14 pm](https://cloud.githubusercontent.com/assets/601220/12832081/d6a4a206-cb4c-11e5-94bb-1e8c069bd26b.png)

**Comment by yosuke-matsuda** [comment]
Have you made sure you opened `CognitoSyncDemo.xcworkspace` instead of `CognitoSyncDemo.xcodeproj`? Also, are you using the latest version of CocoaPods?

**Comment by colinmadere** [comment]
Sorry, forgot to mention CocoaPods version.  Using latest (just installed) 0.39.0.  Also tried 1.0 pre-release 3.  And you're right, I'm new to Xcode and so I thought I was opening the right file (workspace) but was probably opening the `xcodeproj` via the initial project selection dialog.  It appears to be working now, thanks for making me double-check!
