### ISSUE TITLE
CognitoSync-Sample / Swift / DeveloperAuthenticated files are in Objective-C

### ISSUE THREAD

**Issue by vince-marco** [awslabs/aws-sdk-ios-samples#49]
All the files under CognitoSync-Sample/Swift/DeveloperAuthenticated are the same Objective-C files that are under CognitoSync-Sample/Objective-C/DeveloperAuthenticated.  These are exactly the files that should represent a Swift example of Cognito auth integration.  The files that are Swift are just standard AppDelegate and view controller files that are in every swift application.

**Comment by vince-marco** [comment]
Any possibility of added an example accessing a Lambda, such as the github project at https://github.com/danilop/LambdAuth.git ?

**Comment by helloniklas** [comment]
I managed to use the LambdAuth now but it's confusing to try and use that with this old messy code sample. See this blog post for how to integrate with a lambda back end, http://baczuk.com/2015/12/AWS-Cognito-in-Swift/

Also, you need to set up the API Gateway for the LambdAuth to be able to use it for logging in.

**Comment by vince-marco** [comment]
Any possibility you could share your APIGateway client class and usage?  I am very close to working, but still have an issue in calling my API.

**Comment by helloniklas** [comment]
Seth up resources and method as POST on AWS.

This my refresh method in my class that extends AWSAbstractCognitoIdentityProvider

```
    override func refresh() -> AWSTask! {
        let task = AWSTaskCompletionSource()
        let request = NSMutableURLRequest(URL: NSURL(string: "https://asdsadasdasd.execute-api.us-east-1.amazonaws.com/test/auth/login")!)
        let session = NSURLSession(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())
        request.HTTPMethod = "POST"
        let params = ["email": self.email, "password": self.password] as Dictionary<String, String>
        request.HTTPBody = try! NSJSONSerialization.dataWithJSONObject(params, options: NSJSONWritingOptions())
        request.addValue("application/json", forHTTPHeaderField: "Content-Type")
        request.addValue("application/json", forHTTPHeaderField: "Accept")

        let sessionTask = session.dataTaskWithRequest(request) { (data, response, error) -> Void in
            if let data = data {
                if let json = try! NSJSONSerialization.JSONObjectWithData(data, options: .MutableLeaves) as? NSDictionary {
                    self.logins = [self.developerProvider : self.email]
                    // Get the properties from my server response
                    let identityId = json.objectForKey("identityId") as! String
                    let token = json.objectForKey("token") as! String

                    // Set the identityId and token
                    self.identityId = identityId
                    self._token = token
                    task.setResult(self.identityId)
                }
                else {
                    print("json error")
                }
            }
            else if let error = error {
                print(error.localizedDescription)
                task.setError(error)
            }
            else {
                print("error in call")
            }
        }
        sessionTask.resume()
        return task.task
    }
```

**Comment by EZWrighter** [comment]
5 months down the road and these examples that are supposed to be swift are objective-C!  Trying to find any working example of developer authentication using cognito 2.4.0

**Comment by muellerfr** [comment]
Hello @vince-marco,

Please use AWS AppSync instead of Amazon Cognito Sync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.

It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

Please let us know if you have any questions about AppSync.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
