### ISSUE TITLE
How to get device token?

### ISSUE THREAD

**Issue by DrakeW** [awslabs/aws-sdk-ios-samples#5]
```Objective-C
NSString *const DeviceTokenKey = @"DeviceToken";
NSString *const CognitoDeviceTokenKey = @"CognitoDeviceToken";
NSString *const CognitoPushNotification = @"CognitoPushNotification";
```
How to get these values from the Amazon Cognito Console? I failed to find them

**Comment by turacma** [comment]
These values do no not need to be changed in order to use the sample. My apologies for any confusion.

**Comment by DrakeW** [comment]
Thanks but my sample still doesn't work, it shows me this error when I tried to build and run
```
ld: library not found for -lPods-AWSCognitoSync
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by turacma** [comment]
It sounds like you are opening the `.xcodeproj` file and not the `.xcworkspace` file. When using cocoapods you must always open the workspace file.

**Comment by DrakeW** [comment]
It works now! And one more question, in the cognito sync demo, step 5 it said set the app name to the app name in the server side application, does the server side application's name mean the identity pool's name?

**Comment by turacma** [comment]
Step 5 is only necessary if you want to use our example authentication backend, which is available in [its own repo](https://github.com/awslabs/amazon-cognito-developer-authentication-sample) with documentation. The appname in the iOS sample should match the appname in the server authentication sample.

**Comment by DrakeW** [comment]
Thanks :)
