### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by hmehran** [awslabs/aws-sdk-ios-samples#50]
How would Registering a new user for  Developer Authenticated look like?
Been trying to figure that out.

**Comment by wdane** [comment]
I would begin by looking at the Cognito docs (http://docs.aws.amazon.com/cognito/devguide/identity/developer-authenticated-identities/ make sure to select iOS as the platform in the upper right) and the blog post https://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en

**Comment by hmehran** [comment]
Thanks. I was able to register inside the ios cognitosyncdemo app. But it isn't secure because i am solely passing a url unencrypted to /registeruser. If anyone wants to see my implementation let me know.
