### ISSUE TITLE
Is there a step missing in setting up the code?

### ISSUE THREAD

**Issue by farshidhss** [awslabs/aws-sdk-ios-samples#54]
About the AWS Cognito sample, I have been struggling for a while to make this code work, and I finally figured out that you also need to grant access to your identity in amazon IAM console under the Roles (at least AmazonCognitoReadOnly or AmazonCognitoPowerUser policy). I recommend that you update your instructions to reflect this step.

**Comment by yosuke-matsuda** [comment]
Are you trying out CognitoSync-Sample?

**Comment by farshidhss** [comment]
Yes exactly. I used it with Facebook external provider for the log-in.

**Comment by kushwahavinay** [comment]
Did you use Cognito console to create the role? By default it creates a role which allows access to "cognito-sync:*" in the policy.

**Comment by farshidhss** [comment]
I created it using the Mobile Hub service in AWS which also asked in the process if I need to login with Facebook but apparently it fails in granting the correct permissions to the role. Now I tested and create an identity pool in the Cognito console and that automatically assigned the correct policy. So I guess there is a reason Mobile Hub is still in beta ;) many thanks for your help.

**Comment by yosuke-matsuda** [comment]
Did you enable **User Data Storage** using the AWS Mobile Hub Console? Unless you enable it, Mobile Hub does not generate policy that allows access to Amazon Cognito Sync.

**Comment by farshidhss** [comment]
Oh now I see! You are totally right. I created it without enabling user data storage since I needed that one for another project but later I used the same one to test this example here. I really appreciate your clarification. Sorry for my misunderstanding.
