### ISSUE TITLE
S3 Transfer Manager Error

### ISSUE THREAD

**Issue by NathanTruong** [awslabs/aws-sdk-ios-samples#55]
I followed the Read Me and seem to be given a downcast error - 

Downcast from '[AWS S3Object]?' to '[AWS S3Object]' only unwraps optionals; did you mean to use '!'?

For the following code -  
if let contents = listObjectsOutput.contents as? [AWSS3Object] 
This is from the downloadviewcontroller.swift

**Comment by rohandubal** [comment]
Hi,

Thanks for reporting this. We will update the samples. If you need a immediate fix, please change the mentioned line to:
_

> if let contents = listObjectsOutput.contents {

_

Thanks.

-Rohan
