### ISSUE TITLE
No "DynamoDB.h" file found

### ISSUE THREAD

**Issue by matrixstone** [awslabs/aws-sdk-ios-samples#6]
When I tried to run the code, it has issue: No "DynamoDB.h" file found.

It happened in code "DDBDetailViewController.m". The code tried to import "DynamoDB.h" file. But it failed to find it.

Where could we find the "DynamoDB.h" file?

**Comment by yosuke-matsuda** [comment]
Starting with 2.1.0, you need to import like the following:

    #import <AWSDynamoDB/AWSDynamoDB.h>

See this [blog post](http://mobile.awsblog.com/post/Tx3OJX4PLAUJEH0/The-AWS-Mobile-SDK-for-iOS-2-1-x-Split-Frameworks) for more details.
