### ISSUE TITLE
Issues with type casting in DynamoDB Swift Sample

### ISSUE THREAD

**Issue by surpher** [awslabs/aws-sdk-ios-samples#60]
Xcode 7.2, Swift 2.1

../DynamoDBObjectMapper-Sample/DynamoDBSample/Swift/
DDBMainTableViewController.swift
**Line 181** : **'NSMutableArray' is not implicitly convertible to '[AnyObject]'; did you mean to use 'as' to explicitly convert?**

<img width="900" alt="screen shot 2016-03-07 at 11 37 31 am" src="https://cloud.githubusercontent.com/assets/1733327/13558447/1326485e-e459-11e5-87a1-a68e2e286f12.png">

Funny thing, build succeeds using double type cast `tasks as [AnyObject] as? [AWSTask] `.

----

../DynamoDBObjectMapper-Sample/DynamoDBSample/Swift/
DDBDynamoDBManager.swift
**Line: 97** : **'NSMutableArray' is not implicitly convertible to '[AnyObject]'; did you mean to use 'as' to explicitly convert?**

<img width="894" alt="screen shot 2016-03-07 at 11 37 11 am" src="https://cloud.githubusercontent.com/assets/1733327/13558450/1b52154e-e459-11e5-86e0-15b744da28b2.png">

But build succeeds using double type cast `gsiArray as [AnyObject] as? [AWSDynamoDBGlobalSecondaryIndex]`

**Comment by rohandubal** [comment]
Thanks for reporting this. We will update the thread once we update the samples.

**Comment by yosuke-matsuda** [comment]
The DynamoDB Object Mapper sample app was updated for the latest version of Swift and AWS Mobile SDK. Thanks.
