### ISSUE TITLE
Need help to setup connection to Iot platform

### ISSUE THREAD

**Issue by BharathChandrashekarFluke** [awslabs/aws-sdk-ios-samples#63]
Am trying to connect my iOS app to AWS IoT.  I have the 3 files in my app bundle - rootCA.pem, certificate.pem.crt and private.pem.key.  I have to connect to host -  ssl://xxxxx.iot.us-west-2.amazonaws.com:8883.   

When I look at the sample app here, the API to connect is  "self.iotDataManager.connectWithClientId( uuid, cleanSession:true, certificateId:certificateId, statusCallback: mqttEventCallback)".  This API does not accept the host address. Also this API requires the certificateID. The certificateID of which of the 3 files mentioned above should be passed here. 

Any help is appreciated.

**Comment by gkwicker** [comment]
Hi @BharathChandrashekarFluke, the previous versions of the iOS SDK and sample application didn't allow you to use a pre-existing certificate and private key.  However, we've just released new versions of the iOS SDK and sample applications which support importing identities (certificate + private key) from an application bundle into the keychain.  Have a look at [the latest code and README.md](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift) and let us know if you're able to get connected using your own certificate and private key.  Thanks for using AWS IoT.

**Comment by BharathChandrashekarFluke** [comment]
We are now able to connect. Thanks a lot for the help. Keep up the good work.

**Comment by gkwicker** [comment]
You're welcome, @BharathChandrashekarFluke.  I'm glad we were able to help.  Please let us know if you have any other questions, and thanks again for using AWS IoT.
