### ISSUE TITLE
Swift demo won't build using latest AWS SDK

### ISSUE THREAD

**Issue by joebernard** [awslabs/aws-sdk-ios-samples#66]
When using the 2.4.0 SDK the build fails with an error:

> /opt/demos/aws-sdk-ios-samples/CognitoSync-Sample/Swift/CognitoSyncDemo/CognitoSyncDemo-Bridging-Header.h:19:9: note: in file included from /opt/demos/aws-sdk-ios-samples/CognitoSync-Sample/Swift/CognitoSyncDemo/CognitoSyncDemo-Bridging-Header.h:19:
> # import "DeveloperAuthenticatedIdentityProvider.h"
> 
> ```
>     ^
> ```
> 
> /opt/demos/aws-sdk-ios-samples/CognitoSync-Sample/Swift/CognitoSyncDemo/DeveloperAuthenticated/DeveloperAuthenticatedIdentityProvider.h:20:53: error: cannot find interface declaration for 'AWSAbstractCognitoIdentityProvider', superclass of 'DeveloperAuthenticatedIdentityProvider'
> @ interface DeveloperAuthenticatedIdentityProvider : AWSAbstractCognitoIdentityProvider
>                                                     ^
> <unknown>:0: error: failed to import bridging header '/opt/demos/aws-sdk-ios-samples/CognitoSync-Sample/Swift/CognitoSyncDemo/CognitoSyncDemo-Bridging-Header.h'

Will it be updated to use the latest APIs?

**Comment by lakhman** [comment]
This is linked to this issue:

https://github.com/aws/aws-sdk-ios/issues/357

If you use `2.3.6` it should work, we're waiting for the samples to be updated.

**Comment by yosuke-matsuda** [comment]
All sample apps are tied to specific versions of the SDK as configured in `Podfile`. Currently, they don't support 2.4.0. We will update the samples when they are ready. Thanks.

**Comment by Stradix** [comment]
@yosuke-matsuda is there any news? I'm eagerly awaiting for this fix

**Comment by abhishek-nyllabs** [comment]
Any updates on this?

**Comment by EZWrighter** [comment]
It is now almost August....3 months down the road and STILL no working example!  Has amazon dumped support for Cognito?

**Comment by Marini83** [comment]
Where is support for 2.4.0?

**Comment by minbi** [comment]
Hi @Marini83,

Have you tried the samples locating in the this [branch](https://github.com/awslabs/aws-sdk-ios-samples/tree/developer-authenticated-identities-2-4) ?

**Comment by minbi** [comment]
Swift demo has been update [link](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoSync-Sample/Swift)
