### ISSUE TITLE
Cognito Swift example. Error in identityPoolId "Member must satisfy regular expression pattern: [\\w-]+:[0-9a-f-]+"}]"

### ISSUE THREAD

**Issue by Stradix** [awslabs/aws-sdk-ios-samples#67]
Following the instructions to run the Cognito Swift example, in constants.swift when you fill up:
`static let COGNITO_IDENTITY_POOL_ID = "us-east-1_XXXXXXXXXX"`

you get an xCode  error: 

> 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w-]+:[0-9a-f-]+"}]

It looks like AWS Cognito platform is running under Beta version, and the Pool_ID that provides is not compatible with format that accepts the swift example.
<img width="1092" alt="captura de pantalla 2016-04-24 a las 22 01 55" src="https://cloud.githubusercontent.com/assets/915781/14770069/881591a8-0a68-11e6-8585-1faee5033cee.png">

**Comment by yosuke-matsuda** [comment]
What you need is Amazon Cognito Identity Pool Id (not Your User Pool ARN). You need to go to **Manage Federated Identities** section of the Management Console to create an identity pool.

**Comment by behrooziAWS** [comment]
Closing because it appears you were using a user pool id where an identity pool was required, please reopen if you still have issues.

**Comment by TijenderSingh** [comment]
You need to add "Manage Federated Identities" keys instead of "Manage User Pools" section.Hope this helps.
https://ap-south-1.console.aws.amazon.com/cognito/home?region=ap-south-1
