### ISSUE TITLE
Bug in CognitoSync Swift version

### ISSUE THREAD

**Issue by Stradix** [awslabs/aws-sdk-ios-samples#68]
Found a bug doing this flow:
-Log in via Facebook -->  Logout/Wipe --> Log in via Facebook again. It doesn't show the Facebook popup to authorize facebook again. It remains in the white screen where the 3 options are disabled.
If you fully close app and open again, then it shows the popup.

**Comment by Stradix** [comment]
Found the solution.
```
    func fbLogout() {
        if self.fbLoginManager == nil {
            self.fbLoginManager = FBSDKLoginManager()
        }
        self.fbLoginManager?.logOut()
        self.keyChain[FB_PROVIDER] = nil
        self.fbLoginManager = nil // <--Needs to be set as nil
    }
```
If is not nil, then will never show the Facebook Login window:

```
    func fbLogin() {
        if FBSDKAccessToken.currentAccessToken() != nil {
            self.completeFBLogin()
        } else {
            if self.fbLoginManager == nil { //<--If not nil, never will step over
```

**Comment by Stradix** [comment]
Made a Pull Request

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity and the PR was merged. If there's still an issue, please open it in the aws/aws-sdk-ios repo.
