### ISSUE TITLE
How to run the Amazon S3 TransferManager Sample if Cognito is not available?

### ISSUE THREAD

**Issue by bagusflyer** [awslabs/aws-sdk-ios-samples#7]
I'm wondering if there is a way to upload file to my S3 storage if my zone doesn't support cognito? Thanks.

**Comment by turacma** [comment]
The region for Cognito is independent of the region you might want to access S3, this is why they are different values in the [constants files](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/S3TransferManager-Sample/Objective-C/S3TransferManagerSample/Constants.m). 

You can use an identity pool in `AWSRegionUSEast1` to access S3 in `AWSRegionSAEast1`, for instance.

**Comment by bagusflyer** [comment]
I'm using free tier of AWS currently. Should I have to pay by using Cognito in different region ? Thanks

**Comment by turacma** [comment]
As long as you do not use the data synchronization features or Amazon Cognito, there is no charge to use the service. If you do use the synchronization features, Amazon Cognito has a generous [free tier](http://aws.amazon.com/cognito/pricing/).

**Comment by bagusflyer** [comment]
Thank you so much.

**Comment by turacma** [comment]
You're very welcome. Do feel free to open a new issue should you encounter any problems getting started.
