### ISSUE TITLE
issues resolving URL

### ISSUE THREAD

**Issue by ebalassanian** [awslabs/aws-sdk-ios-samples#70]
I had the sample transfer manager app working with my pool ID, bucket and regions listed in constants.m. I just tried it again and it's now failing. I get the following error:

NSErrorFailingURLStringKey=https://cognito-identity.us-west-2.amazonaws.com/, NSErrorFailingURLKey=https://cognito-identity.us-west-2.amazonaws.com/, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}]

**Comment by yosuke-matsuda** [comment]
Amazon Cognito Identity is not supported in US West 2. Please use one of the [supported regions](http://docs.aws.amazon.com/general/latest/gr/rande.html#cognito_identity_region).

**Comment by ebalassanian** [comment]
Thanks for following up. If I switch from using US West 2, then I get the another error: 

Amazon S3 - must be addressed using the specified endpoint

My understanding what the cognito pool had to be in the same region as my S3 bucket, no?

**Comment by yosuke-matsuda** [comment]
In general, your Cognito Identity Pool and S3 bucket do not need to be in the same region. Each service client provides the following class methods:

    + register[ServiceClientName]WithConfiguration:forKey:
    + [ServiceClientName]ForKey:

For example, for [`AWSS3TransferUtility`](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html), they are:

    + registerS3TransferUtilityWithConfiguration:forKey:
    + S3TransferUtilityForKey:

In this way, you can pass a different service configuration for each service client
