### ISSUE TITLE
Subscribe topic

### ISSUE THREAD

**Issue by brunoudi** [awslabs/aws-sdk-ios-samples#72]
I'm subscribing to a topic with the code below:

        iotDataManager.subscribeToTopic("device1/status/#", qos: 0, messageCallback: {
            (payload) ->Void in
            
            let stringValue = NSString(data: payload, encoding: NSUTF8StringEncoding)!
            
            print("received: \(stringValue)")
            dispatch_async(dispatch_get_main_queue()) {
                //some code here
            }
        } )

the problem is that when i get a message, i don't know the exactly topic which came from... example "device1/status/on" or "device1/status/value". In the example i'm getting only the payload.

Is there a way to get the full topic and the payload?

**Comment by yosuke-matsuda** [comment]
Duplicates of [this issue](https://github.com/aws/aws-sdk-ios/issues/366). Merging.
