### ISSUE TITLE
Deleting app and reinstalling keeps user logged in

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#74]
If I successfully log in, then delete the app. I expect the user to be logged out, like in Facebook or Instagram apps. Since your code is persisting through keychain that doesn't happen. I've tried to add something to user defaults, as this does get deleted, but still can't get it to log out, as the that service provider is very hard to get rid of and properly log out of a session.

**Comment by jbailey2010** [comment]
The SDK stores the user login information in the key chain upon login, as you mentioned, and the key chain persists across installs. This is expected behavior that you are seeing, and we are aware of it.

**Comment by evankyle** [comment]
Persisting keys across installs is a good default for many use cases. If you want an app start following a reinstall to present the user a logged out state check if its an app start after reinstall and log out the user with clearKeychain.
