### ISSUE TITLE
Adding Facebook and Twitter provider

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#75]
If I attempt to add a Facebook and Twitter provider, I get this to work. But, if user first logs in with DevAuth, then logouts then tries to login with Facebook it will fails, and vice verse. Seems since one can only set the defaultServiceConfig once, it's impossible to properly logout.

If I shut the app down then start it again, I can log in with a different provider.

**Comment by jbailey2010** [comment]
I believe this issue was resolved with [SDK issue 357](https://github.com/aws/aws-sdk-ios/issues/357)
