### ISSUE TITLE
Signing in with AWSCognitoIdentityUserPool does't create an identity in Cognito

### ISSUE THREAD

**Issue by helloniklas** [awslabs/aws-sdk-ios-samples#78]
So I set the user pool id etc in the Cognito Authentication providers. But when I sign up with a user that user doesn't appear as an identity in the Cognito identity browser?

**Comment by helloniklas** [comment]
Ok, I finally get it now. After all the user pool stuff, I then ask for the Credentials from Cognito using the pool for the AWSCognitoCredentialsProvider, then the identity appears in the Cognito browser.

```
            AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"us-east-1:xxxxxxxx" identityProviderManager:pool];
            [[credentialsProvider getIdentityId] continueWithBlock:^id _Nullable(AWSTask<NSString *> * _Nonnull task) {
                NSLog(@"id %@", task.result);
                return nil;
            }];
```

**Comment by MarkMerc123** [comment]
Hello,

I am glad you were able to find a resolution.  You are correct, an Identity will *not* be created in Cognito Federated Identities until you request credentials.

-Mark

**Comment by helloniklas** [comment]
@MarkMerc123 for some reason this has now stopped working and giving an crashed the app:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The service configuration is `nil`. You need to configure `Info.plist` or set `defaultServiceConfiguration` before using this method.'

Not sure what changed, might be related to new AWS SDK?

**Comment by MarkMerc123** [comment]
If you could provide some code samples to replicate the problem I can investigate further.

**Comment by helloniklas** [comment]
In the app delegate I'm doing 
```
        let serviceConfiguration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: nil)
        let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: Constants.Cognito.IdentityUserPoolAppClientId, clientSecret: Constants.Cognito.IdentityUserPoolAppClientSecret, poolId: Constants.Cognito.IdentityUserPoolId)
        AWSCognitoIdentityUserPool.registerCognitoIdentityUserPoolWithConfiguration(serviceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: "UserPool")
        let pool = AWSCognitoIdentityUserPool(forKey: "UserPool")
        pool.delegate = self
```

Then I do signup and confirmSignUp which works. I then do getSession on the user which works. I then do 
```
                let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: Constants.Cognito.IdentityPoolId, identityProviderManager: AWSCognitoIdentityUserPool(forKey: "UserPool"))
                credentialsProvider.getIdentityId().continueWithBlock({ (task) -> AnyObject? in
```

Which cause the app to crash saying the defaultServiceConfiguration is not set...

**Comment by behrooziAWS** [comment]
You need to set your defaultServiceConfiguration prior to calling getIdentityId, something like this:
```
let configuration = AWSServiceConfiguration(
    region: .USEast1,
    credentialsProvider: credentialsProvider)
AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = configuration
```

**Comment by helloniklas** [comment]
@behrooziAWS Thanks that now works.
