### ISSUE TITLE
Google Plus Auth (RE: CognitoSync-Sample/Swift/)

### ISSUE THREAD

**Issue by dperry** [awslabs/aws-sdk-ios-samples#79]
Hello,

A question about the CognitoSync-Sample/Swift/ sample, I noticed you are using the google-plus-ios-sdk module to facilitate the auth with Google. Checking the G+ api here - https://developers.google.com/+/mobile/ios/, I noticed this api is now deprecated and the new api https://developers.google.com/identity/sign-in/ios/ should be used instead. 

Few questions ;)

Is this an issue from your viewpoint? I had got the sample working, but a. I don't want to limit myself to only G users that have G+ accounts AND b. I would like compatibility with my backend site which uses the new G auth api.

Are there any plans to use the new api and update the demo sample?

The AWS cognito documentation mentions Google+ too http://docs.aws.amazon.com/cognito/latest/developerguide/google.html would using the "new api" be an issue for that feature? (aka does Cognito support Google's new auth mechanism) As I understand it, the old and new approaches are similar (aka oAuth2) so it might not be an issue.. but this is unclear.

Any help would be greatly appreciated, Cognito seems like a great tool but these questions would help us know if investing more time is worthwhile.

Cheers

Dan

**Comment by behrooziAWS** [comment]
Hi Dan,

Taking a quick look at the [migration guide](https://developers.google.com/identity/sign-in/ios/quick-migration-guide#1_changes_for_the_viewcontroller_header_file) it looks like it should work.  It will take some time for us to test this and update our guides and samples and we don't currently have someone tasked to it.  If you want to go ahead and try the migration steps and report back if you have issues, that will help us prioritize how urgently we need to update.

**Comment by dperry** [comment]
Hey,

Thanks for getting back so quickly. We have been working on using the new modules and making the suggested changes mentioned in the migration guide. It seems to be working (managed to login and sync data this afternoon). The iOS developer working on the code can raise a PR with what we got working if that helps?

It might be worth mentioning this to the AWS Cognito team that maintains the portal and documentation to change references to 'Google+'. Otherwise it could put people off using the product.

Thanks :)

Dan

**Comment by chetanme** [comment]
Thank you Dan. We will update the documentation in our future releases. I will close this issue in favor of the linked pull request.
