### ISSUE TITLE
How to get s3 object url after uploading?

### ISSUE THREAD

**Issue by bagusflyer** [awslabs/aws-sdk-ios-samples#8]
I went through the S3TransferManager-Sample demo. It works well. But my question is how to get the s3 object url (the uploaded file url)? Thanks

**Comment by bagusflyer** [comment]
By the way, how to show the progress. I follow the demo, it seems I only got one callback. I don't know it's because of the size of the file is too small.

**Comment by yyzhu** [comment]
Hi bagusflyer,

For first question, you can use AWSS3PreSignedURL to generated a pre-signed downloadURL that can be used to download a file in S3 Bucket.  For usage details, please check out the sample app: S3BackgroundTransfer-Sample.

For second question,  `AWSS3TransferManagerUploadRequest` and `AWSS3TransferManagerDownloadRequest` supports uploading/downloading progress through  blocks:

```
 AWSS3TransferManagerUploadRequest *uploadRequest = [AWSS3TransferManagerUploadRequest new];
uploadRequest.uploadProgress = ^(int64_t bytesSent, int64_t totalBytesSent, int64_t totalBytesExpectedToSend) {
};
...
```
For more details, You can check out UploadViewController.m and DownloadViewController.m in S3TransferManagerSample app.
