### ISSUE TITLE
How to pass logins token to user pool identity provider?

### ISSUE THREAD

**Issue by simoami** [awslabs/aws-sdk-ios-samples#81]
Hello,

I've added user pool as provider to the function `initializeClients()` from CognitoSyncDemo as show below.

However, I don't know how to pass the tokens in logins over to the userPool identity provider, like we do with custom Identity providers. Or is supposed to work differently?

```
func getUserPool() -> AWSCognitoIdentityUserPool? {
    if self.userPool == nil {
        let serviceConfiguration = AWSServiceConfiguration(region: Constants.COGNITO_REGIONTYPE, credentialsProvider: nil)
        let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(
            clientId: Constants.COGNITO_USER_POOL_CLIENT_ID,
            clientSecret: Constants.COGNITO_USER_POOL_CLIENT_SECRET,
            poolId: Constants.COGNITO_USER_POOL_ID
        )
        AWSCognitoIdentityUserPool.registerCognitoIdentityUserPoolWithConfiguration(
            serviceConfiguration,
            userPoolConfiguration: userPoolConfiguration,
            forKey: "UserPool")
        self.userPool = AWSCognitoIdentityUserPool(forKey: "UserPool")
    }
    return self.userPool
}

func initializeClients(logins: [String: String]?) -> AWSTask? {
  if let logins = logins {
      let identityProviderManager : AWSIdentityProviderManager
      if self.loginSource == COGNITO_PROVIDER {
          identityProviderManager = self.getUserPool()!
      } else {
          identityProviderManager = CustomIdentityProvider(tokens: logins)
      }
      self.credentialsProvider = AWSCognitoCredentialsProvider(
          regionType: Constants.COGNITO_REGIONTYPE,
          identityPoolId: Constants.COGNITO_IDENTITY_POOL_ID,
          identityProviderManager: identityProviderManager
      )
  }
}
```

**Comment by behrooziAWS** [comment]
AWSCognitoIdentityUserPool implements the [AWSIdentityProviderManager protocol](http://docs.aws.amazon.com/AWSiOSSDK/latest/Protocols/AWSIdentityProviderManager.html).  If you look at the [implementation](https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.m#L194) it attempts to get a session for the current logged in user and populate the logins map using that.  If you are trying to do something more advanced, like link a CognitoIdentityUser with your CustomIdentityProvider user, you would need to provide your own implementation of the IdentityProviderManager protocol.  You can use how it is implemented in AWSCognitoIdentityUserPool to set the UserPool token in the logins map and setting the token from your CustomIdentityProvider would be similar.  I'm not sure I've answered your question, so if I'm misunderstanding please clarify.

**Comment by helloniklas** [comment]
@behrooziAWS So is AWSCognitoIdentityUserPool meant to set the logins form the user pool on sign in / up. It does not seem to happen. If not, how to I set the logins on the AWSCognitoIdentityUserPool? Do I need to subclass my own class then provide the logins task with the dictionary?

**Comment by behrooziAWS** [comment]
If you use `AWSCognitoIdentityUserPool` as your `AWSIdentityProviderManager`, it will set the logins map for the currently authenticated user.  If there is no authenticated user, it will start the signin flow.  You should not be setting the logins map for the `AWSCognitoIdentityUserPool`, it will handle the process.  If you need to provide support for other login providers (Facebook et. all) or unauthenticated users, that is when you implement your own `AWSIdentityProviderManager`.

**Comment by helloniklas** [comment]
@behrooziAWS And does this AWSIdentityProviderManager setting the logins map for me mean the user will appear in the Cognito Identity Browser? This does not happen, which is causing confusion. I'm trying to get that simple step working before I get to merging this with Facebook provider.

**Comment by helloniklas** [comment]
@behrooziAWS I what I'm missing is how to use the pool as a AWSIdentityProviderManager. The sample code has to create the AWSServiceConfiguration first, then the pool.

**Comment by helloniklas** [comment]
@behrooziAWS or how else do I get the authenticated user to assume an auth IAM role?

**Comment by helloniklas** [comment]
@behrooziAWS ok, I finally get it now. After all the user pool stuff, I then ask for the Credentials from Cognito using the pool for the AWSCognitoCredentialsProvider, then the identity appears in the Cognito browser.

```
            AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"us-east-1:xxxxxxxx" identityProviderManager:pool];
            [[credentialsProvider getIdentityId] continueWithBlock:^id _Nullable(AWSTask<NSString *> * _Nonnull task) {
                NSLog(@"id %@", task.result);
                return nil;
            }];
```

**Comment by simoami** [comment]
@behrooziAWS Sorry for the delay. Yes, I use user pools in conjunction with other 3rd party providers. So I followed your advice:

> If you need to provide support for other login providers (Facebook et. all) or unauthenticated users, that is when you implement your own AWSIdentityProviderManager.

So I created a custom implementation of AWSIdentityProviderManager for the sole purpose of passing login tokens:

```
    class CustomIdentityProvider: NSObject, AWSIdentityProviderManager {
        var tokens : [String : String]?
        init(tokens: [String : String]) {
            self.tokens = tokens
        }
        func logins() -> AWSTask {
            return AWSTask(result: tokens)
        }
    }
```

I now use this regardless of the provider, even in the case of user pools, and this helped simplify implementation:

```
func initializeClients(logins: [String: String]?) -> AWSTask? {
    if let logins = logins {
        let identityProviderManager = CustomIdentityProvider(tokens: logins)
        self.credentialsProvider = AWSCognitoCredentialsProvider(
            regionType: Constants.COGNITO_REGIONTYPE,
            identityPoolId: Constants.COGNITO_IDENTITY_POOL_ID,
            identityProviderManager: identityProviderManager
        )
    }
    return self.credentialsProvider?.getIdentityId()
}
```

The user pool instance is no longer passed on to any credentials provider. It's only use it to sign up, log the user in, or obtain the idToken which is then fed to:

```
func completeCognitoLogin(token: String) {
    self.cognitoToken = token
    self.switchProvider(COGNITO_PROVIDER, value: "YES")
    self.completeLogin([self.userPool!.identityProviderName : token])
}
```

Can you confirm the approach is correct?

**Comment by behrooziAWS** [comment]
The CredentialsProvider will only use the IdentityProviderManager when it is attempting to refresh the AWSCredentials.  The intent is that in the implementation of logins, you would reach out to the current identity provider, get a current token and return it.  The way you have implemented it appears to be how CredentialsProvider worked previously which was to make you responsible for setting up a timer that would reach out to the identity provider and get a current token each time it expired with no knowledge of whether the CredentialsProvider actually needed the token.  So this approach will work, but it would probably make more sense to actually get the current token from the current identity provider in your logins method so you don't need to manage token expiration yourself.
