### ISSUE TITLE
Is it possible to use AWSMobileAnalytics without enabling unauth access in cognito id pool

### ISSUE THREAD

**Issue by simoami** [awslabs/aws-sdk-ios-samples#83]
I'm trying to get MobileAnalytics to work independent of my auth/unauth configuration in cognito identity pool. My current Cognito config is Auth only. Unauth is disabled. 

Before the user logs in, I send an event "App launched", and then I get the error below:

```
AWSiOSSDK v2.4.2 [Error] AWSIdentityProvider.m line:293 | __52-[AWSCognitoCredentialsProviderHelper getIdentityId]_block_invoke.249 | GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]
AWSiOSSDK v2.4.2 [Error] AWSCredentialsProvider.m line:569 | __44-[AWSCognitoCredentialsProvider credentials]_block_invoke.345 | Unable to refresh. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}]
AWSiOSSDK v2.4.2 [Error] AWSMobileAnalyticsDefaultDeliveryClient.m line:251 | __74-[AWSMobileAnalyticsDefaultDeliveryClient submitEvents:andUpdatePolicies:]_block_invoke | Unable to successfully deliver events to server. Error Message:Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Unauthenticated access is not supported for this identity pool.}
```

Here's my Analytics config:

```
let mobileAnalytics = AWSMobileAnalytics(
  forAppId: Constants.MOBILE_ANALYTICS_APP_ID,
  identityPoolId: Constants.COGNITO_IDENTITY_POOL_ID
)
```

P.S Enabling Unauth in Cognito fixes the problem but creates a layered set of errors I gave up on after a few days of trisl and error, like "Mismatch between session identity id and request identity id". So I'm wondering if I can do without. like to initialize MobileAnalytics without specifying an identity pool.

**Comment by rohandubal** [comment]
Hi,
To achieve the use case you want to, you will have to use the following constructor:

> + (instancetype)mobileAnalyticsForAppId:(NSString *)appId
>                           configuration:(AWSMobileAnalyticsConfiguration *)configuration
>                         completionBlock:(AWSInitializationCompletionBlock)completionBlock

Make sure you initialize after the user is authenticated.

Thanks,
Rohan
