### ISSUE TITLE
How to upload something use my server temporary certificate?

### ISSUE THREAD

**Issue by starjang** [awslabs/aws-sdk-ios-samples#84]
I want to upload image to S3 use my server temporary accessKey, secretKey, sessionKey and expiration, but I can’t use temporary certificate in AWS-SDK-iOS v2 version. I see Amazon documents, in the V1 version is to support it. How I can do this in v2?

**Comment by karthiksaligrama** [comment]
You should use Amazon Cognito Identity for fetching a temporary credentials in the app. Take a look at [Amazon Cognito](http://aws.amazon.com/documentation/cognito/)

**Comment by starjang** [comment]
Thanks

**Comment by starjang** [comment]
Thanks
