### ISSUE TITLE
Static Certificate for AWS IoT

### ISSUE THREAD

**Issue by RochevAV** [awslabs/aws-sdk-ios-samples#85]
Hi!
1. Drop the PKCS #12 archive in the 'Supporting Files' folder 
2. Select all targets you want to import the identity into
3. Build and run the application, and it will use this identity rather than creating one dynamically. 

Don't work for me!

1. In the documentation method - (BOOL)connectWithClientId:(NSString *)clientId
               cleanSession:(BOOL)cleanSession
              certificateId:(NSString *)certificateId
             statusCallback:(void (^__strong)(AWSIoTMQTTStatus))callback;
certificateId	
contains the ID of the certificate to use in the connection; must be in the keychain
must be in the keychain ! How add certificateId in the keychain ?

**Comment by RochevAV** [comment]
In old version IoT (2.3.2) I found method + (SecIdentityRef)certificateFromP12:(NSString*)path password:(NSString *)password;
I created SecIdentityRef and add Identity in keychain. Method:
+ (BOOL)addIdentityRef:(SecIdentityRef)identityRef tag:(NSString*)tag {

    NSMutableDictionary * queryIdentity = [[NSMutableDictionary alloc] init];
    
    [queryIdentity setObject:(id)kSecClassIdentity forKey:(id)kSecClass];
    [queryIdentity setObject:tag forKey:(id)kSecAttrApplicationTag];
    [queryIdentity setObject:(__bridge id)identityRef forKey:(id)kSecValueRef];
    [queryIdentity setObject:(id)kSecAttrKeyTypeRSA forKey:(id)kSecAttrKeyType];
    [queryIdentity setObject:[NSNumber numberWithBool:YES] forKey:(id)kSecReturnPersistentRef];
    
    OSStatus sanityCheck = SecItemAdd((CFDictionaryRef)queryIdentity, nil);
    if ((sanityCheck != noErr) && (sanityCheck != errSecDuplicateItem)) {
        NSLog(@"add Identity to keychain with error: %d", (int)sanityCheck);
        return NO;
    }
    return YES;
}

sanityCheck == 0 ! Identity added in the keychain. But when I'm looking for the Identity method:

+ (SecIdentityRef)getIdentityRef:(NSString*)tag {
    OSStatus sanityCheck = noErr;
    SecIdentityRef identityRef = NULL;
    
    NSMutableDictionary * queryIdentityRef = [[NSMutableDictionary alloc] init];
    
    [queryIdentityRef setObject:(id)kSecClassIdentity forKey:(id)kSecClass];
    [queryIdentityRef setObject:tag forKey:(id)kSecAttrApplicationTag]; 
    [queryIdentityRef setObject:(id)kSecAttrKeyTypeRSA forKey:(id)kSecAttrKeyType];
    [queryIdentityRef setObject:[NSNumber numberWithBool:YES] forKey:(id)kSecReturnRef];
    
    sanityCheck = SecItemCopyMatching((CFDictionaryRef)queryIdentityRef, (CFTypeRef *)&identityRef);
    
    if (sanityCheck != noErr){
        AWSLogError(@"getIdentityRef error: %d",(int)sanityCheck);
        identityRef = NULL;
    }
    
    return identityRef;
}

sanityCheck == -25300,  /* The specified item could not be found in the keychain. */

Why?

**Comment by RochevAV** [comment]
Please help me! How add static certificate in project for work with AWS IoT ?
Any working options. Thanks!

**Comment by rongsaws** [comment]
Did you import a ".p12" file into your bundle? The file's extension name must be "p12" so it can be recognized by the sample. The relevant code of importing the .p12 file is here 

https://github.com/awslabs/aws-sdk-ios-samples/blob/master/IoT-Sample/Swift/IoTSampleSwift/ConnectionViewController.swift#L115-L148

For more information, please refer to Step 8 of the Readme file https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift. Thanks.

**Comment by RochevAV** [comment]
Very good ! This work for my. Thanks.
