### ISSUE TITLE
Need for Developer Authenticated Identities?

### ISSUE THREAD

**Issue by awasserman14** [awslabs/aws-sdk-ios-samples#86]
I am struggling to understand the need for creating your own backend authentication system because it seems to me that cognito by itself handles signing up and signing in functionality by itself. For example in the Cognito Your User Pool Example it seems that this handles all sign in/ sign up functionality without a secondary authorization process. Is this correct? Any insight into this would be much appreciated. Thanks.

**Comment by karthiksaligrama** [comment]
developer authenticated identities is different from cognito user pools. You can use one or the other. If you use cognito user pools then you dont need to create your own backend authentication system.
