### ISSUE TITLE
Import AWSCore Swift Error

### ISSUE THREAD

**Issue by awasserman14** [awslabs/aws-sdk-ios-samples#87]
I am trying to create a project in swift and i used Cocoapods to create my xcworkspace. When i try to import AWSCore in the App Delegate it says there is no such module. Any ideas? Thanks

**Comment by rohandubal** [comment]
Hi,
Sorry to hear that your project is not working. Could you please share what version of SDK you are using? Also, what version of cocoa pods you are using? Please let me know.

Thanks,
Rohan

**Comment by awasserman14** [comment]
Thanks for the quick response but I found the error. Stupid mistake.
