### ISSUE TITLE
Access identity pool datasets across multiple user ids

### ISSUE THREAD

**Issue by simoami** [awslabs/aws-sdk-ios-samples#88]
I need to be able to display a list of users whose data is stored in datasets via Cognito Sync, like in this [screenshot](https://www.invisionapp.com/subsystems/main_landing/assets/img/screens/social-5.png). It seems that I cannot access datasets across multiple uses to fetch their names, so what is the recommended approach?
1. Access each user's "Profile" dataset to pull their first, last name, or 
2. Have a separate dynamodb table for "Users" to query multiple users. If so what is private datasets still relevant for?

**Comment by rohandubal** [comment]
Hi, you are correct. You can't use dataset for this purpose. This question is not related to the SDK so I will mark it closed, but I recommend you post this in AWS Forums where you can discuss it.

-Rohan

**Comment by simoami** [comment]
thanks
