### ISSUE TITLE
iOS User Pool Set Up (Swift)

### ISSUE THREAD

**Issue by awasserman14** [awslabs/aws-sdk-ios-samples#89]
I am trying to use User Pools to add sign in/log in functionality to my Swift iOS app. In my App Delegate I have set up my Credentials Provider and Service Configuration with 

`let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.USEast1, identityPoolId: cognitoIdentityPoolId)

    let defaultServiceConfiguration = AWSServiceConfiguration(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)

    AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = defaultServiceConfiguration`

but when i try to set up the user pool configuration with:

`let configurationUserPool = AWSCognitoIdentityUserPoolConfiguration(clientId: "###", clientSecret: "#########", poolId: "###")`

i get a compilation error of "use of unresolved identifier AWSCognitoIdentityUserPoolConfiguration", which i dont understand because i have imported AWSCore and AWSCognito

any help or insight would be much appreciated thanks

**Comment by chetanme** [comment]
I think you had [a SO post](http://stackoverflow.com/questions/37839195/aws-user-pool-setup-swift) for same question and as per the comment there you figured it out. Closing this issue.
