### ISSUE TITLE
Instructions on setting up the table in the console

### ISSUE THREAD

**Issue by dillonhd** [awslabs/aws-sdk-ios-samples#9]
Dear sir or madam,

Do you have instructions on how to set up the table in the AWS console? I was able to build the code of DynamoDB sample successfully but I don't have the table that goes with the code. Thanks a lot!

**Comment by yosuke-matsuda** [comment]
[Getting Started with DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html) is a great starting point on learning how to use Amazon DynamoDB Management Console. Hope it helps,

**Comment by yyzhu** [comment]
The DynamoDBSample project automatically create a testTable during the launch if that table doesn't exists, Therefore you don't need to set up the table for running the sample project.

If you need instructions to set up your own table in AWS Console,  [Get Started Guide](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html) is good place to take a look.
