### ISSUE TITLE
The DynamoDB sample requires the different format of Cognito Pool Id

### ISSUE THREAD

**Issue by woh5050** [awslabs/aws-sdk-ios-samples#90]
Hi,

I was trying to run the DynamoDBObjectMapper-Sample (Object-C), and it requires the Cognito Pool Id to be formatted like "us-east-1:12345678-1234-1234-1234-123456789abc". But the Pool Id I got from the Cognito is different formatted, and that triggers the regular expression error in the code. Could you tell me what is going on there?

Thanks,
Wei

**Comment by rohandubal** [comment]
Hi,

sorry to hear that you are not able to make the sample work. Could you please tell me where did you locate your Cognito Pool Id from? It should look like the one you have mentioned in the post. Could you navigate to the Sample Code of your pool and see if its same as what is mentioned there in Console? 

Thanks,
Rohan

**Comment by bowenisdum** [comment]
@rohandubal format shown in aws cognito dashboard is ```us-east-1_DNvLFUiJQ```

**Comment by jbailey2010** [comment]
Hi,

That is the id of a Cognito User Pool, the format the sample wants is the Cognito Identity Pool id. You can create this from the Federated Identities branch of the Cognito console, and link the Cognito User Pool to it if you want to use both. Cognito Federated Identities is used to leverage public providers (and/or Cognito User Pools) to get AWS Credentials, and is different from Cognito User Pools.

Thanks,
Jeff
