### ISSUE TITLE
Which PolicyName should be used in the Constants.swift file for the IoTSampleSwift?

### ISSUE THREAD

**Issue by edimoldovan** [awslabs/aws-sdk-ios-samples#91]
Here’s the link to the example in the repo: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift

I am unable to figure out which policy to use. I tried `AWSIoTFullAccess` but I get 

```
{"message":"Policy not found”}
```

as a response.

Could anyone clarify which `PolicyName` should be used?

**Comment by dkarchmer** [comment]
Same question

**Comment by edimoldovan** [comment]
I figured this one out. You need to create a policy in the IoT dashboard and provide that policy’s name in the code.
