### ISSUE TITLE
pool.delegate

### ISSUE THREAD

**Issue by onesmalldog** [awslabs/aws-sdk-ios-samples#93]
i find AWSCognitoIdentityInteractiveAuthenticationDelegate will implement end of confirm user, but i can't find the property of delegate in AWSCognitoIdentityUserPool, can you help me?

**Comment by behrooziAWS** [comment]
Hmm, I'm not sure why it doesn't show up in the docs, the sample uses it [here](https://github.com/awslabs/aws-sdk-ios-samples/blob/master/CognitoYourUserPools-Sample/Objective-C/CognitoYourUserPoolsSample/AppDelegate.m#L55).   And it is in AWSCognitoIdentityUserPool.h [here](https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUserPool.h#L41). 

Are you having difficulty using that property?
