### ISSUE TITLE
swift compatability didCompletePasswordAuthenticationStepWithError should pass an Optional NSError

### ISSUE THREAD

**Issue by BruceBuckland** [awslabs/aws-sdk-ios-samples#94]
For swift compatability didCompletePasswordAuthenticationStepWithError should pass an Optional NSError to the delegate.  Swift works better if anything that can be nil is declared as Optional, and in the case of a successful login (authentication) didCompletePasswordAuthenticationStepWithError is passed a nil error.

This is really a problem with the declares in the API and not the sample.

**Comment by karthiksaligrama** [comment]
fixed with 2.4.6

**Comment by BruceBuckland** [comment]
Thanks!
