### ISSUE TITLE
response.codeDeliveryDetails.destination is null after resendConfirmationCode()

### ISSUE THREAD

**Issue by BruceBuckland** [awslabs/aws-sdk-ios-samples#95]
response.codeDeliveryDetails.destination is null after resendConfirmationCode()

it should not be null.

This means in the CognitoYourUserPools sample app if you click resend confirmation code in the sample app, the alert says "confirmation code resent to (Null).

I don't think it is a sample bug, I think the API is not providing the correct task.result

(the confirmation code is ACTUALLY sent in response to the call, but the App displays Null as the "code sent to:"

**Comment by behrooziAWS** [comment]
Yep you are correct it's an SDK bug, I have fixed it for the next release of the SDK.  If you need a temporary patch if you add:

`[response aws_copyPropertiesFromObject:task.result];`

between line 92 and 93 [here](https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L92-L93), that should fix it.

**Comment by behrooziAWS** [comment]
This was fixed in 2.4.6.  Thanks for the report.

**Comment by BruceBuckland** [comment]
Thank you!
