### ISSUE TITLE
CognitoYourUserPools-Sample configuration issue outside of AWSRegionUSEast1

### ISSUE THREAD

**Issue by mitch-dm** [awslabs/aws-sdk-ios-samples#96]
Hi,

When initialising AWSServiceConfiguration the default region is hard-coded (as AWSRegionUSEast1). This causes ResourceNotFoundException when pool is outside of AWSRegionUSEast1.. Move to Constants.m?

Cheers,
Mitch

**Comment by behrooziAWS** [comment]
I've made this change locally and there was a incomplete pull request for the same, will fix shortly.

**Comment by behrooziAWS** [comment]
It's in Constants.m now.
