### ISSUE TITLE
iOS Build Error Using Quickblox Pod file in AWS Mobile SDK 

### ISSUE THREAD

**Issue by aanchalkalani** [awslabs/aws-sdk-ios-samples#97]
We have an download application that is referencing the AWS Mobile frameworks directly and several other libraries using CocoaPods. The project builds fine

But, when we add the 'Quickblox-SDK' as an additional library to reference in the PodFile and run pod install I get several build/linker errors:

`Undefined symbols for architecture x86_64:
  "_AWSSNSErrorDomain", referenced from:
      ___88-[AWSPushManager interceptApplication:didRegisterForRemoteNotificationsWithDeviceToken:]_block_invoke.239 in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNS", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSCreatePlatformEndpointInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSGetEndpointAttributesInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSSetEndpointAttributesInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSSubscribeInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSUnsubscribeInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_FBSDKAccessToken", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_FBSDKApplicationDelegate", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_FBSDKGraphRequest", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_FBSDKLoginManager", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSGoogleSignInProvider.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

If we remove the $(inherited) flag from the Other Linker Flags build setting, getting below errors:-

bash: /User/..../AWSCore.framework/strip-frameworks.sh: No such file or directory uploadDSYM[13005:219405] Fabric.framework/run 1.4.1 (160) uploadDSYM[13005:219405] Launched uploader in validation mode bash: /Users/..../Frameworks/Quickblox.framework/strip-framework.sh: No such file or directory

Any Help will be appreciated..

**Comment by rohandubal** [comment]
Cocoapods sometimes sets the -ObjC linker flag on in the project which requires all the libraries to be present in your app even if you are not using them in your application. You should instead use -force_load flag with the Quickblox-SDK so that it only force loads the required SDK rather than all of them.

-Rohan

**Comment by aanchalkalani** [comment]
Hi,

Could you please help us where and how could we set the -force_load flag with the Quickblox-SDK.

As our Other Linker Flag is like :- 

$(inherited)
-ObjC
-l"resolv"
-l"stdc++"
-l"xml2"
-l"z"
-framework
"AVFoundation"
-framework
"Accelerate"
-framework
"AudioToolbox"
-framework
"CFNetwork"
-framework
"CoreData"
-framework
"CoreGraphics"
-framework
"CoreLocation"
-framework
"CoreMedia"
-framework
"CoreVideo"
-framework
"MobileCoreServices"
-framework
"SystemConfiguration"
-framework
"UIKit"
"Quickblox"
-framework

Thanks,

**Comment by rohandubal** [comment]
Hi,

You should first remove the -ObjC flag from the Other Linker Flag. It force loads all the libraries and dependencies even if they are not used in the app. You should be using the -force_load flag which only force loads the required library and its dependencies. To force load the Quickblox SDK, you need add the following flag:

-force_load $(PROJECT_DIR)/Path_To_QuickbloxFramework/Quickblox-SDK.framework

Thanks,
Rohan
